### ISSUE TITLE
2.5.1 on a Bungee cord version is completely broken

### ISSUE THREAD

**Issue by ghost** [retrooper/packetevents#1007]
Using PLHidePRO 2.10.4 on Proxy Server + Backend Servers.
Using Packetevents-spigot on all backend servers.
Using Packetevents-bungeecord 2.5.1 and even some 2.5.0 builds 
Result: Will prevent everyone from joining the network.

Error:
[06:51:56 INFO]: [SeppyGG] disconnected with: NullPointerException : Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "io.github.retrooper.packetevents.injector.CustomPipelineUtil.BUNGEE_PACKET_ENCODE_BYTEBUF" is null @ io.github.retrooper.packetevents.injector.CustomPipelineUtil:145
[06:52:37 ERROR]: java.lang.NoSuchMethodException: net.md_5.bungee.compress.PacketCompressor.encode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List)
[06:52:37 ERROR]:       at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848)
[06:52:37 ERROR]:       at io.github.retrooper.packetevents.injector.CustomPipelineUtil.callPacketEncodeByteBuf(CustomPipelineUtil.java:137)
[06:52:37 ERROR]:       at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.recompress(PacketEventsEncoder.java:147)
[06:52:37 ERROR]:       at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.read(PacketEventsEncoder.java:78)
[06:52:37 ERROR]:       at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:102)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
[06:52:37 ERROR]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
[06:52:37 ERROR]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
[06:52:37 ERROR]:       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:956)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:982)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:950)
[06:52:37 ERROR]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1019)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:310)
[06:52:37 ERROR]:       at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:143)
[06:52:37 ERROR]:       at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:163)
[06:52:37 ERROR]:       at net.md_5.bungee.ServerConnector.cutThrough(ServerConnector.java:407)
[06:52:37 ERROR]:       at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:189)
[06:52:37 ERROR]:       at net.md_5.bungee.protocol.packet.LoginSuccess.handle(LoginSuccess.java:83)
[06:52:37 ERROR]:       at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:168)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[06:52:37 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[06:52:37 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[06:52:37 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[06:52:37 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[06:52:37 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[06:52:37 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[06:52:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[06:52:37 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
[06:52:37 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
[06:52:37 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
[06:52:37 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
[06:52:37 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
[06:52:37 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:52:37 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[06:52:37 INFO]: [SeppyGG] disconnected with: NullPointerException : Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "io.github.retrooper.packetevents.injector.CustomPipelineUtil.BUNGEE_PACKET_ENCODE_BYTEBUF" is null @ io.github.retrooper.packetevents.injector.CustomPipelineUtil:145

It works fine in earlier versions, but as mentioned 2.5.1 and 2.5.0 gives these errors.

**Comment by ghost** [comment]
Forgot to mention my server is also fully Paper 1.21

**Comment by Krakenied** [comment]
Update your BungeeCord

**Comment by booky10** [comment]
See above, update

**Comment by ghost** [comment]
> Update your BungeeCord

> See above, update

Problem is, that it is fully updated, as I'm using FlameCord 2.1.8 https://builtbybit.com/resources/flamecord-ultimate-anti-bot-solution.13492/

And i've never had issues with PlHidePRO and Flamecord combo for a year straight - until now

**Comment by Krakenied** [comment]
BungeeCord made a change some time ago https://github.com/SpigotMC/BungeeCord/pull/3737 and its forks need to be updated to be compatible with plugins made for latest BungeeCord version

**Comment by ghost** [comment]
> BungeeCord made a change some time ago [SpigotMC/BungeeCord#3737](https://github.com/SpigotMC/BungeeCord/pull/3737) and its forks need to be updated to be compatible with plugins made for latest BungeeCord version

Gotcha, thank you. I'll notify the developer of this

**Comment by ghost** [comment]
Pain.. seems like Flamecord will have an incompatibility with PlHidePro from now on. Probably best to disclose that on the plugin page so others dont stress about this issue in the future too :( 
![image](https://github.com/user-attachments/assets/c4294a26-3928-40f0-99cc-537b57c9aab2)
