### ISSUE TITLE
IndexOutOfBounds 2 different errors kicking players

### ISSUE THREAD

**Issue by bobhenl** [retrooper/packetevents#1012]
**Describe the bug**
Hello, I have strange issue that starts happening only sometimes on server start, restart can fix it, but it's really weird that it even starts happening sometimes.

```yml
16:32:11] [Netty epoll Worker #6/WARN] [com.github.retrooper.packetevents.PacketEventsAPI]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex: 63, writerIndex: 18 (expected: 0 <= readerIndex <= writerIndex <= capacity(256))
	at io.netty.buffer.AbstractByteBuf.checkIndexBounds(AbstractByteBuf.java:112) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:121) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.github.retrooper.packetevents.impl.netty.buffer.ByteBufOperatorImpl.readerIndex(ByteBufOperatorImpl.java:44) ~[?:?]
	at com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readerIndex(ByteBufHelper.java:39) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:649) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:637) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerRespawn.read(WrapperPlayServerRespawn.java:147) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:276) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:181) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:171) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerRespawn.<init>(WrapperPlayServerRespawn.java:62) ~[?:?]
	at com.github.retrooper.packetevents.manager.InternalPacketListener.onPacketSend(InternalPacketListener.java:114) ~[?:?]
	at com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[?:?]
	at com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[?:?]
	at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.read(PacketEventsEncoder.java:46) ~[?:?]
	at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:70) ~[?:?]
	at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:32) ~[?:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:248) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleGeneric(BackendPlaySessionHandler.java:449) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:154) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:91) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:60) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

```yml
16:38:40] [Netty epoll Worker #0/WARN] [com.github.retrooper.packetevents.PacketEventsAPI]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex(9) + length(1) exceeds writerIndex(9): PooledUnsafeDirectByteBuf(ridx: 9, widx: 9, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.github.retrooper.packetevents.impl.netty.buffer.ByteBufOperatorImpl.readByte(ByteBufOperatorImpl.java:74) ~[?:?]
	at com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readByte(ByteBufHelper.java:67) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.readByte(PacketWrapper.java:353) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.readVarInt(PacketWrapper.java:393) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerJoinGame.read(WrapperPlayServerJoinGame.java:259) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:276) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:181) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:171) ~[?:?]
	at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerJoinGame.<init>(WrapperPlayServerJoinGame.java:68) ~[?:?]
	at com.github.retrooper.packetevents.manager.InternalPacketListener.onPacketSend(InternalPacketListener.java:101) ~[?:?]
	at com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[?:?]
	at com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[?:?]
	at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.read(PacketEventsEncoder.java:46) ~[?:?]
	at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:70) ~[?:?]
	at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:32) ~[?:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:248) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleGeneric(BackendPlaySessionHandler.java:449) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:154) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:91) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:60) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Software brand**
Velocity 3.3.0-SNAPSHOT (git-2016d148-b436)..

**Plugins**
![image](https://github.com/user-attachments/assets/3cec05d3-8c51-4e81-afa0-f77738066567)

**How To Reproduce**
First bug:
1. Open Ender chest
2. Move item there
3. You get kicked (I'm using AdvancedEnderChest plugin but it's not prob related)

Second bug:
1. Open shop from EconomyShopGUI
2. Select some item
3. click on + to add more quantity
4. You get kicked

ERRORS HAPPEN ONLY SOMETIMES WHEN THE PROXY OR PLUGIN PROB LOADS SOMEHOW WEIRD? The restart usually fixes it

**Expected behavior**
No kicks & no errors

**Comment by booky10** [comment]
Which client version and which server version are you testing this with?

**Comment by bobhenl** [comment]
> Which client version and which server version are you testing this with?

Server was 1.21.1, clients were various versions, 1.21.1 most of them, too.

And it's not only related to mentioned plugins, it was happening when clicking on items in deluxemenu, etc. as well 

@booky10 

I noticed that sometimes when I start the proxy it "starts wrongly" and these similar errors keep spamming there, not really sure what's causing it :/ I need to restart, but this time it happened prob on auto restart & this was the result, player gets kicked for:
![image](https://github.com/user-attachments/assets/5b6af6b1-5806-49ec-809f-9939ef3181f4)

**Comment by KozukiYOMA** [comment]
I want to talk about an error in this image.
I have been having trouble with this error as well.
In my case, I was getting kicked with this error when entering my inventory with unstackable, effective potions (including those available in creative inventory) by command, collecting drop items, etc., or opening chests that contain potions.
Perhaps this is the cause.
In my case, this occurred with PaperMC 1.21.3 and PurpurMC 1.21.3.

**Comment by booky10** [comment]
Please try updating packetevents - if this issue still occurs, post the error here and I will re-open this issue
