### ISSUE TITLE
Conflict with AdvancedSlimePaper

### ISSUE THREAD

**Issue by karu724** [retrooper/packetevents#1023]
**Describe the bug**

**Software brand**
Please let us know what software you are using.
Eg. Spigot 1.18.2, Paper 1.18.2, Tuinity 1.18.2, Pufferfish 1.18.2, etc...
Make sure to mention the version of the software.

1.20.4 AdvancedSlimePaper(Fork of Paper)
https://github.com/InfernalSuite/AdvancedSlimePaper

**Plugins**
Please give us a list of your plugins. Sometimes we run into incompatibilities. Having an overview of the plugins on your server can really help identify the problem quicker.
Eg. ViaVersion, ProtocolLib, HolographicDisplays
You may also provide a screenshot.

AdvancedSlimePlugin, Matrix

**How To Reproduce**
*Example:*
1. summon entity
2. error occurred

**Expected behavior**

**Screenshots**

**Additional context**
[23:39:29] [Server thread/INFO]: Error while executing task on main thread
[23:39:29] [Server thread/WARN]: java.lang.IllegalStateException: PacketEvents failed to find a EntityLookup indexed 0 by its type in the com.infernalsuite.aswm.level.SlimeLevelInstance class!
[23:39:29] [Server thread/WARN]:     at Matrix_7.9.22A.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.util.reflection.ReflectionObject.getField(Unknown Source)
[23:39:29] [Server thread/WARN]:     at Matrix_7.9.22A.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.util.reflection.ReflectionObject.read(Unknown Source)
[23:39:29] [Server thread/WARN]:     at Matrix_7.9.22A.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.util.reflection.ReflectionObject.readObject(Unknown Source)
[23:39:29] [Server thread/WARN]:     at Matrix_7.9.22A.jar//me.rerere.matrix.thirdparty.io.github.retrooper.packetevents.util.SpigotReflectionUtil.getEntityByIdWithWorldUnsafe(Unknown Source)
[23:39:29] [Server thread/WARN]:     at Matrix_7.9.22A.jar//me.rerere.matrix.thirdparty.io.github.retrooper.packetevents.util.SpigotReflectionUtil.getEntityById(Unknown Source)
[23:39:29] [Server thread/WARN]:     at Matrix_7.9.22A.jar//me.rerere.matrix.thirdparty.io.github.retrooper.packetevents.util.SpigotConversionUtil.getEntityById(Unknown Source)
[23:39:29] [Server thread/WARN]:     at Matrix_7.9.22A.jar//me.rerere.matrix._.xj.u(Unknown Source)
[23:39:29] [Server thread/WARN]:     at Matrix_7.9.22A.jar//me.rerere.matrix.misc.compatibility.Mainthread.executeOnEventLoop$lambda$6(Unknown Source)
[23:39:29] [Server thread/WARN]:     at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:39:29] [Server thread/WARN]:     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[23:39:29] [Server thread/WARN]:     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[23:39:29] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1469)
[23:39:29] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[23:39:29] [Server thread/WARN]:     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[23:39:29] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1446)
[23:39:29] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1369)
[23:39:29] [Server thread/WARN]:     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[23:39:29] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1347)
[23:39:29] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1236)
[23:39:29] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[23:39:29] [Server thread/WARN]:     at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by rafi67000** [comment]
the issue is that ASP overrides ServerLevel class so the field is in SUBCLASS and not in the SlimeLevelInstance
