### ISSUE TITLE
Cannot invoke "eu.nononitas.plhidepro.api.player.PlHidePlayer.getGroup()" because "<parameter2>" is null

### ISSUE THREAD

**Issue by smscentras** [retrooper/packetevents#1055]
**Software brand**
Purpur 1.21.1

**Plugins**
ViaVersion, ViaBackwards, Pl-Hide-Pro

**How To Reproduce**
Don't know, found in log.

**Describe the bug**
`[17:47:02] [Netty Server IO #2/WARN]: [com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: Cannot invoke "eu.nononitas.plhidepro.api.player.PlHidePlayer.getGroup()" because "<parameter2>" is null
	at Pl-Hide-Pro-2.11.1.jar/eu.nononitas.plhidepro.modifier.SuggestionEditor.editSuggestion(SuggestionEditor.java:14) ~[Pl-Hide-Pro-2.11.1.jar:?]
	at Pl-Hide-Pro-2.11.1.jar/eu.nononitas.plhidepro.listener.packetevents.DeclareCommandsListener.onPacketSend(DeclareCommandsListener.java:42) ~[Pl-Hide-Pro-2.11.1.jar:?]
	at Pl-Hide-Pro-2.11.1.jar/eu.nononitas.plhidepro.spigot.miscellaneous.PacketEventsHook$1.onPacketSend(PacketEventsHook.java:33) ~[Pl-Hide-Pro-2.11.1.jar:?]
	at packetevents-spigot-2.6.0.jar/com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[packetevents-spigot-2.6.0.jar:?]
	at packetevents-spigot-2.6.0.jar/com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[packetevents-spigot-2.6.0.jar:?]
	at packetevents-spigot-2.6.0.jar/com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:61) ~[packetevents-spigot-2.6.0.jar:?]
	at packetevents-spigot-2.6.0.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:88) ~[packetevents-spigot-2.6.0.jar:?]
	at packetevents-spigot-2.6.0.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:73) ~[packetevents-spigot-2.6.0.jar:?]
	at packetevents-spigot-2.6.0.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:52) ~[packetevents-spigot-2.6.0.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at packetevents-spigot-2.6.0.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:107) ~[packetevents-spigot-2.6.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]`

**Comment by booky10** [comment]
Please report this error to Pl-Hide-Pro, this doesn't seem like a packetevents issue
