### ISSUE TITLE
НЕ ЗАХОДИТ

### ISSUE THREAD

**Issue by int3iku** [retrooper/packetevents#1056]
[18:08:13] [Netty epoll Worker #5/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [initial connection] /here.my.ip.:3:777: exception encountered in net.elytrium.limboapi.server.LimboSessionHandlerImpl@67808dc2
io.netty.handler.codec.EncoderException: com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 797 to a PacketType constant. Bound: CLIENT, Connection state: LOGIN, Server version: 1.16.4
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at net.elytrium.limboapi.thirdparty.fastprepare.handler.PreparedPacketEncoder.write(PreparedPacketEncoder.java:81) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:964) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:300) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:248) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at net.elytrium.limboapi.server.LimboImpl.onSpawn(LimboImpl.java:567) ~[?:?]
	at net.elytrium.limboapi.server.LimboImpl.spawnPlayerLocal(LimboImpl.java:458) ~[?:?]
	at net.elytrium.limboapi.server.LimboImpl.lambda$spawnPlayerLocal$18(LimboImpl.java:547) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 797 to a PacketType constant. Bound: CLIENT, Connection state: LOGIN, Server version: 1.16.4
	at com.github.retrooper.packetevents.event.ProtocolPacketEvent.<init>(ProtocolPacketEvent.java:90) ~[?:?]
	at com.github.retrooper.packetevents.event.PacketSendEvent.<init>(PacketSendEvent.java:37) ~[?:?]
	at com.github.retrooper.packetevents.event.simple.PacketLoginSendEvent.<init>(PacketLoginSendEvent.java:32) ~[?:?]
	at com.github.retrooper.packetevents.util.EventCreationUtil.createSendEvent(EventCreationUtil.java:53) ~[?:?]
	at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.read(PacketEventsEncoder.java:43) ~[?:?]
	at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:70) ~[?:?]
	at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:32) ~[?:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
	... 33 more
	
	
Это отправляется в консоль при входе, моя версия 1.16.5 ForgeOptiFine

я использую все плагины Limbo и ядро Velocity последних версий (dev builds), а оно не заходит

список плагинов: crazymotd, limboapi, limboauth, limboauth-social-addon, limbofilter, luckperms, packetevents, pl-hide-pro, skinsrestorer, viaversion, viabackwards, viarewind

ВСЕ ПЛАГИНЫ ПОСЛЕДНИХ ВЕРСИЙ ДЛЯ ПОДДЕРЖКИ 1.21.3 

пробовал ставить packetevents-velocity-2.6.1 но тоже БЕЗУСПЕШНО

Исправьте пожалуйста!!!!!!

**Comment by booky10** [comment]
Activate compatibility mode in limboapi

**Comment by int3iku** [comment]
thx
