### ISSUE TITLE
java.lang.UnsupportedOperationException: Unsupported custom data nbt type: NBTLong

### ISSUE THREAD

**Issue by scarfacered** [retrooper/packetevents#1060]
**Describe the bug**

```
java.lang.UnsupportedOperationException: Unsupported custom data nbt type: NBTLong
	at Grim.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.builtin.item.CustomData.read(CustomData.java:39) ~[Grim.jar:?]
	at Grim.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.StaticComponentType.read(StaticComponentType.java:69) ~[Grim.jar:?]
	at Grim.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStackModern(PacketWrapper.java:483) ~[Grim.jar:?]
	at Grim.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:502) ~[Grim.jar:?]
	at Grim.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotReflectionUtil.decodeBukkitItemStack(SpigotReflectionUtil.java:810) ~[Grim.jar:?]
	at Grim.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotConversionUtil.fromBukkitItemStack(SpigotConversionUtil.java:155) ~[Grim.jar:?]
	at Grim.jar/ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.checkThatBukkitIsSynced(CorrectingPlayerInventoryStorage.java:104) ~[Grim.jar:?]
	at Grim.jar/ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.tickWithBukkit(CorrectingPlayerInventoryStorage.java:148) ~[Grim.jar:?]
	at Grim.jar/ac.grim.grimac.manager.tick.impl.TickInventory.tick(TickInventory.java:11) ~[Grim.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
	at Grim.jar/ac.grim.grimac.manager.TickManager.tickAsync(TickManager.java:34) ~[Grim.jar:?]
	at Grim.jar/ac.grim.grimac.manager.init.start.TickRunner.lambda$start$2(TickRunner.java:21) ~[Grim.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.3.jar:1.21.3-DEV-9fd3ae0]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.3.jar:1.21.3-DEV-9fd3ae0]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.3.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Software brand**
Paper 1.21.3

**Plugins**
Grim, ViaVersion, ViaBackwards

**How To Reproduce**
Not sure

**Expected behavior**
No error

**Comment by booky10** [comment]
This error shouldn't happen, vanilla also rejects long tags there
Packetevents may have tried to read some other type of component, but without a clear way to reproduce this, we can't fix this

If you can reproduce this however, comment here with a screenshot/paste of `/paper dumpitem` with the item which is causing this issue
