### ISSUE TITLE
[BUG] No enum constant: WrappedPacketOutChat.ChatPosition.SYSTEM

### ISSUE THREAD

**Issue by True-cc** [retrooper/packetevents#107]
```
java.lang.IllegalArgumentException: No enum constant io.github.retrooper.packetevents.packetwrappers.play.out.chat.WrappedPacketOutChat.ChatPosition.SYSTEM
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_252]
	at io.github.retrooper.packetevents.packetwrappers.play.out.chat.WrappedPacketOutChat$ChatPosition.valueOf(WrappedPacketOutChat.java:231) ~[?:?]
	at io.github.retrooper.packetevents.packetwrappers.play.out.chat.WrappedPacketOutChat.getChatPosition(WrappedPacketOutChat.java:220) ~[?:?]
	at uwu.smsgamer.spygotutils.listener.spigot.SPacketProcessor.onPacketPlaySend(SPacketProcessor.java:15) ~[?:?]
	at io.github.retrooper.packetevents.event.impl.PacketPlaySendEvent.call(PacketPlaySendEvent.java:94) ~[?:?]
	at io.github.retrooper.packetevents.event.manager.EventManagerDynamic.callEvent(EventManagerDynamic.java:66) ~[?:?]
	at io.github.retrooper.packetevents.event.manager.EventManager.callEvent(EventManager.java:57) ~[?:?]
	at io.github.retrooper.packetevents.processor.PacketProcessorInternal.write(PacketProcessorInternal.java:169) ~[?:?]
	at io.github.retrooper.packetevents.injector.earlyinjector.modern.PlayerChannelHandler.write(PlayerChannelHandler.java:66
[...]
```
This server is running CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
packetevents version 1.8-pre-6

**Comment by retrooper** [comment]
The field is called SYSTEM_MESSAGE now. I tried following CraftBukkits naming. I forgot I made this change. Thanks for the notice.
