### ISSUE TITLE
Java 16 blocking illegal access

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#108]
```
[17:43:58 WARN]: java.lang.IllegalStateException: PacketEvents failed to inject with the Early Injector. Reverting to the Compatibility/Late Injector... Please report this!
[17:43:58 WARN]:        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.GlobalChannelInjector.inject(GlobalChannelInjector.java:43)
[17:43:58 WARN]:        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.PacketEvents.load(PacketEvents.java:130)
[17:43:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[17:43:58 WARN]: Caused by: java.lang.IllegalStateException: PacketEvents failed to inject!
[17:43:58 WARN]:        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.earlyinjector.modern.EarlyChannelInjectorModern.inject(EarlyChannelInjectorModern.java:106)
[17:43:58 WARN]:        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.GlobalChannelInjector.inject(GlobalChannelInjector.java:36)
[17:43:58 WARN]:        ... 2 more
[17:43:58 WARN]: Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[] java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @18e77517
[17:43:58 WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[17:43:58 WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[17:43:58 WARN]:        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[17:43:58 WARN]:        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[17:43:58 WARN]:        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.utils.reflection.Reflection.getModifiersField(Reflection.java:219)
[17:43:58 WARN]:        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.utils.reflection.Reflection.getFieldWithoutFinalModifier(Reflection.java:199)
[17:43:58 WARN]:        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.earlyinjector.modern.EarlyChannelInjectorModern.injectChannelFuture(EarlyChannelInjectorModern.java:154)
[17:43:58 WARN]:        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.earlyinjector.modern.EarlyChannelInjectorModern.inject(EarlyChannelInjectorModern.java:97)
[17:43:58 WARN]:        ... 3 more
```

Works fine with the jvm flag "--illegal-access=permit"

**Comment by retrooper** [comment]
I am looking for an alternative solution that works without that JVM Flag. If anyone knows any solution, lmk.

**Comment by retrooper** [comment]
For now in the packetevents settings you can enable the compatInjector.

**Comment by retrooper** [comment]
Has been fixed in my dev commits, will be fixed in the next pre-release.
