### ISSUE TITLE
Console error 1.21.4

### ISSUE THREAD

**Issue by ghost** [retrooper/packetevents#1083]
```
[14:31:25 WARN]: Exception in thread "pool-16-thread-1" java.lang.NoClassDefFoundError: ac/grim/grimac/shaded/kyori/adventure/util/ARGBLike
[14:31:25 WARN]:        at grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureSerializer.getNBTSerializer(AdventureSerializer.java:73)
[14:31:25 WARN]:        at grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureSerializer.fromNbt(AdventureSerializer.java:110)
[14:31:25 WARN]:        at grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readComponentAsNBT(PacketWrapper.java:697)
[14:31:25 WARN]:        at grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readComponent(PacketWrapper.java:693)
[14:31:25 WARN]:        at grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.StaticComponentType.read(StaticComponentType.java:71)
[14:31:25 WARN]:        at grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.item.type.ItemTypes.parseComponents(ItemTypes.java:1529)
[14:31:25 WARN]:        at grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.item.type.ItemTypes.<clinit>(ItemTypes.java:1550)
[14:31:25 WARN]:        at grim.jar//ac.grim.grimac.manager.init.load.PacketEventsInit.lambda$start$0(PacketEventsInit.java:34)
[14:31:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[14:31:25 WARN]: Caused by: java.lang.ClassNotFoundException: ac.grim.grimac.shaded.kyori.adventure.util.ARGBLike
[14:31:25 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[14:31:25 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[14:31:25 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[14:31:25 WARN]:        ... 9 more
```

latest grim commit https://github.com/GrimAnticheat/Grim/commit/ff1c3043b34332cf2f4be674c1ca38ef3cde9835 built with latest packetevents commit d6c81f32cd7ba4a6f03e6e07712306dc14949007 running on latest paper commit https://github.com/PaperMC/Paper/commit/71a367ec8489c8a61a4c009f6a3c536438707158

**Comment by ghost** [comment]
very odd, can't find ARGBLike anywhere? what is going on here I wonder

**Comment by ghost** [comment]
Found it, its only in this specific adventure PR branch https://github.com/KyoriPowered/adventure/pull/1124/

**Comment by booky10** [comment]
This should be worked around by #1085
