### ISSUE TITLE
Kick Issue

### ISSUE THREAD

**Issue by Godl1nk** [retrooper/packetevents#1090]
**Describe the bug**
When in SURVIVAL mode, clicking a RENAMED Netherrite Pickaxe will get you kicked for. (sometimes t=only happens if the durability bar appears) (not when its full dura)
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: writerIndex(52) + minWritableBytes(6) exceeds maxCapacity(52): PooledSlicedByteBuf(ridx: 0, widx: 52, cap: 52/52, unwrapped: PooledUnsafeDirectByteBuf(ridx: 53, widx: 53, cap: 192)) [11:06:55 INFO]: [DiscordSRV] Player Godl1nk quit with silent quitting

**Software brand**
Please let us know what software you are using.
Eg. Spigot 1.18.2, Paper 1.18.2, Tuinity 1.18.2, Pufferfish 1.18.2, etc...
Make sure to mention the version of the software.

**Plugins**
Please give us a list of your plugins. Sometimes we run into incompatibilities. Having an overview of the plugins on your server can really help identify the problem quicker.
ViaVersion, ProtocolLib, HolographicDisplays, Vulcan, Other plugins not sharing sry
You may also provide a screenshot.

**How To Reproduce**
*Example:*
1. Join with the 1.21.1 client
2. get yourself a netherrite pickaxe
3. damage it abit
4. rename it to anything
5. open ur inv and click it

**Expected behavior**
Nothing should happen but instead i get kicked

**Screenshots**
none

**Additional context**
fix fast pls tysm

**Comment by booky10** [comment]
Please post the full stacktrace

**Comment by Godl1nk** [comment]
> Please post the full stacktrace

? how

**Comment by booky10** [comment]
If there is no full stacktrace in the log, activate `debug` in `server.properties`
Also, please provide the software and version which you are using

**Comment by Godl1nk** [comment]
[12:04:32 WARN]: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: writerIndex(46) + minWritableBytes(6) exceeds maxCapacity(50): PooledUnsafeDirectByteBuf(ridx: 0, widx: 46, cap: 49/50)
[12:04:32 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:101)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:04:32 WARN]:        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[12:04:32 WARN]:        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:04:32 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:04:32 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[12:04:32 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:04:32 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[12:04:32 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:04:32 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:04:32 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:04:32 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[12:04:32 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:04:32 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
[12:04:32 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
[12:04:32 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
[12:04:32 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
[12:04:32 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[12:04:32 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:04:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[12:04:32 WARN]: Caused by: java.lang.IndexOutOfBoundsException: writerIndex(46) + minWritableBytes(6) exceeds maxCapacity(50): PooledUnsafeDirectByteBuf(ridx: 0, widx: 46, cap: 49/50)
[12:04:32 WARN]:        at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:294)
[12:04:32 WARN]:        at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:280)
[12:04:32 WARN]:        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1073)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.writeBytes(ByteBufOperatorModernImpl.java:201)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.writeBytes(ByteBufHelper.java:211)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.netty.buffer.ByteBufOutputStream.write(ByteBufOutputStream.java:48)
[12:04:32 WARN]:        at java.base/java.io.DataOutputStream.write(DataOutputStream.java:118)
[12:04:32 WARN]:        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:400)
[12:04:32 WARN]:        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:330)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.netty.buffer.ByteBufOutputStream.writeUTF(ByteBufOutputStream.java:107)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.protocol.nbt.serializer.NBTSerializer.writeTagName(NBTSerializer.java:122)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.protocol.nbt.serializer.DefaultNBTSerializer.lambda$new$23(DefaultNBTSerializer.java:149)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.protocol.nbt.serializer.NBTSerializer.writeTag(NBTSerializer.java:131)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.protocol.nbt.serializer.DefaultNBTSerializer.lambda$new$21(DefaultNBTSerializer.java:126)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.protocol.nbt.serializer.NBTSerializer.writeTag(NBTSerializer.java:131)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.protocol.nbt.serializer.DefaultNBTSerializer.lambda$new$23(DefaultNBTSerializer.java:150)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.protocol.nbt.serializer.NBTSerializer.writeTag(NBTSerializer.java:131)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.protocol.nbt.serializer.NBTSerializer.serializeTag(NBTSerializer.java:72)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.protocol.nbt.codec.NBTCodec.writeNBTToBuffer(NBTCodec.java:195)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.writeNBTRaw(PacketWrapper.java:633)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.writeComponentAsNBT(PacketWrapper.java:714)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.writeComponent(PacketWrapper.java:707)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.protocol.component.StaticComponentType.write(StaticComponentType.java:77)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.writeItemStackModern(PacketWrapper.java:559)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.writeItemStack(PacketWrapper.java:584)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientClickWindow.write(WrapperPlayClientClickWindow.java:115)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:110)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:57)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:64)
[12:04:32 WARN]:        at packetevents-spigot-2.7.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:41)
[12:04:32 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:91)
[12:04:32 WARN]:        ... 40 more

**Comment by Godl1nk** [comment]
Tested on
Paper 1.21.1
Client 1.21

**Comment by Godl1nk** [comment]
Solved, because i made my spigot Implement Velocity's packet decoder, thats the cause
