### ISSUE TITLE
Another Kick bug

### ISSUE THREAD

**Issue by ItsHarshXD** [retrooper/packetevents#1092]
**Describe the bug**
Players are being kicked when they try to join server.

**Software brand**
PaperMC 1.21.3

**Stacktrace**
`[12:56:23 WARN]: [lol.pyr.znpcsplus.libraries.packetevents.api.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex(29) + length(1) exceeds writerIndex(29): PooledUnsafeDirectByteBuf(ridx: 29, widx: 29, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.impl.netty.buffer.ByteBufOperatorModernImpl.readByte(ByteBufOperatorModernImpl.java:74) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.api.netty.buffer.ByteBufHelper.readByte(ByteBufHelper.java:67) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.api.wrapper.PacketWrapper.readByte(PacketWrapper.java:347) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.api.wrapper.PacketWrapper.readBoolean(PacketWrapper.java:359) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.api.wrapper.login.server.WrapperLoginServerLoginSuccess.read(WrapperLoginServerLoginSuccess.java:80) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.api.wrapper.PacketWrapper.readEvent(PacketWrapper.java:270) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.api.wrapper.PacketWrapper.<init>(PacketWrapper.java:175) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.api.wrapper.PacketWrapper.<init>(PacketWrapper.java:165) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.api.wrapper.login.server.WrapperLoginServerLoginSuccess.<init>(WrapperLoginServerLoginSuccess.java:40) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.api.manager.InternalPacketListener.onPacketSend(InternalPacketListener.java:68) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.api.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.api.event.EventManager.callEvent(EventManager.java:52) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.api.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:45) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.impl.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.impl.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.impl.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.impl.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection$2.write(Connection.java:762) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at ProtocolLib-1.21.1.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib-1.21.1.jar:?]
        at ProtocolLib-1.21.1.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib-1.21.1.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:513) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at ProtocolLib-1.21.1.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49) ~[ProtocolLib-1.21.1.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:56:23 WARN]: [com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex(29) + length(1) exceeds writerIndex(29): PooledUnsafeDirectByteBuf(ridx: 29, widx: 29, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at packetevents-spigot-2.5.0.jar/io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readByte(ByteBufOperatorModernImpl.java:74) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readByte(ByteBufHelper.java:67) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readByte(PacketWrapper.java:353) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readBoolean(PacketWrapper.java:365) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/com.github.retrooper.packetevents.wrapper.login.server.WrapperLoginServerLoginSuccess.read(WrapperLoginServerLoginSuccess.java:80) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:276) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:181) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:171) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/com.github.retrooper.packetevents.wrapper.login.server.WrapperLoginServerLoginSuccess.<init>(WrapperLoginServerLoginSuccess.java:40) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/com.github.retrooper.packetevents.manager.InternalPacketListener.onPacketSend(InternalPacketListener.java:58) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:45) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:87) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:72) ~[packetevents-spigot-2.5.0.jar:?]
        at packetevents-spigot-2.5.0.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:51) ~[packetevents-spigot-2.5.0.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at packetevents-spigot-2.5.0.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:106) ~[packetevents-spigot-2.5.0.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at ZNPCsPlus-2.0.0-SNAPSHOT (1).jar/lol.pyr.znpcsplus.libraries.packetevents.impl.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[ZNPCsPlus-2.0.0-SNAPSHOT (1).jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection$2.write(Connection.java:762) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at ProtocolLib-1.21.1.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib-1.21.1.jar:?]
        at ProtocolLib-1.21.1.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib-1.21.1.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:513) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at ProtocolLib-1.21.1.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49) ~[ProtocolLib-1.21.1.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:56:23 INFO]: [packetevents] lol.pyr.znpcsplus.libraries.packetevents.api.exception.PacketProcessException: Failed to map the Packet ID 12 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.21
[12:56:23 INFO]: [packetevents] lol.pyr.znpcsplus.libraries.packetevents.api.exception.PacketProcessException: Failed to map the Packet ID 12 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.21
[12:56:23 INFO]: [packetevents] Disconnected null due to invalid packet!`

**Plugins**
![image](https://github.com/user-attachments/assets/189b9423-85e2-42d1-a8fb-ab44bba7cb5c)

**How To Reproduce**
*Example:*
1. Join with the 1.21.3 fabric minecraft client.
2. Get kick

**Expected behavior**
Join simply

**Comment by danielmillar** [comment]
Make sure that both **ZNPCsPlus** and **PacketEvents** are updated to the latest version.

- You're using a **Snapshot** version of **ZNPCsPlus**. It's always better to stick with stable builds. You can download the latest stable version [here](https://github.com/Pyrbu/ZNPCsPlus/releases/tag/2.0.0).  
- You're currently running **PacketEvents 2.5.0**, but the latest version is **2.7.0**.

Please report back if making these changes fixes your issue.

**Comment by booky10** [comment]
Update `ZNPCsPlus` or tell them to update packetevents
