### ISSUE TITLE
Players can't join when packetevents-bungeecord is loaded

### ISSUE THREAD

**Issue by LoliColleen** [retrooper/packetevents#1095]
Server:
XCord v1.63 (Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:c5fd43a:565)

Client:
1.21.1 Fabric

Code:
```
@Override
    public void onLoad() {
        PacketEvents.setAPI(BungeePacketEventsBuilder.build(this));
        PacketEvents.getAPI().load();
    }
```
```
dependencies {
    compileOnly fileTree('libs')
    compileOnly 'com.mojang:brigadier:1.0.18'
    compileOnly "net.md-5:bungeecord-api:1.21-R0.1-SNAPSHOT"
    compileOnly 'net.luckperms:api:5.4'
    shadow 'com.github.retrooper:packetevents-bungeecord:2.7.0'
    shadow "com.alkaidmc.alkaid:alkaid-bungeecord:5da8e5d-SNAPSHOT"

    // https://mvnrepository.com/artifact/com.huaban/jieba-analysis
    implementation 'com.huaban:jieba-analysis:1.0.2'
    implementation 'org.jetbrains:annotations:24.0.0'
}
```

Logs:
```
[01:28:41] [hades Pool Thread #0/INFO] [hades]: Creating new connection ...
[01:28:41] [epollEventLoopGroup-3-3/INFO]: [Kolleen|/192.168.1.29:46274] <-> ServerConnector [MainLobby#1] has connected
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: java.lang.NoSuchMethodException: aw.encode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.github.retrooper.packetevents.injector.CustomPipelineUtil.callPacketEncodeByteBuf(CustomPipelineUtil.java:137)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.recompress(PacketEventsEncoder.java:147)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.read(PacketEventsEncoder.java:78)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:102)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.handler.codec.MessageToByteEncoder.write(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.handler.codec.MessageToByteEncoder.write(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at net.md_5.bungee.netty.ChannelWrapper.write(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at net.md_5.bungee.UserConnection$1.sendPacket(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at net.md_5.bungee.ServerConnector.cutThrough(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at net.md_5.bungee.ServerConnector.handle(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at net.md_5.bungee.protocol.packet.LoginSuccess.handle(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at net.md_5.bungee.netty.HandlerBoss.channelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at v.channelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at net.md_5.bungee.protocol.MinecraftDecoder.channelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.run(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(Unknown Source)
[01:28:41] [epollEventLoopGroup-3-3/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[01:28:41] [epollEventLoopGroup-3-3/INFO]: [Kolleen] disconnected with: NullPointerException : Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "io.github.retrooper.packetevents.injector.CustomPipelineUtil.BUNGEE_PACKET_ENCODE_BYTEBUF" is null @ io.github.retrooper.packetevents.injector.CustomPipelineUtil:145
```

**Comment by booky10** [comment]
Have you reported this to XCord? We don't know how their compression is set up, packetevents can only be designed to work with open-source BungeeCord forks (e.g. Waterfall)

**Comment by LoliColleen** [comment]
It still happens on waterfall-1.20-565.
But it doesnt happen on waterfall-1.21-582.

**Comment by booky10** [comment]
Are you using Waterfall or XCord?

**Comment by LoliColleen** [comment]
> Are you using Waterfall or XCord?

I m using XCord.
I mean packetevents have problem on Waterfall 1.20 and the latest XCord is forked from Waterfall 1.20.

**Comment by booky10** [comment]
if this is still an issue, please write a comment and i'll re-open this - but note that we won't support old waterfall versions

**Comment by xbaimiao** [comment]
> 如果这仍然是一个问题，请发表评论，我会重新打开它 - 但请注意，我们不支持旧的瀑布版本

![Image](https://github.com/user-attachments/assets/e7ef606c-d863-458f-9498-0e4efc8796a4) 
bungeecord is also this issue
This server is running BungeeCord version git:BungeeCord-Bootstrap:1.21-R0.1-SNAPSHOT:477ea59:1867 by md_5

**Comment by booky10** [comment]
this is an unrelated issue, please update your bungeecord version, the one your are using is nearly 6 months old
