### ISSUE TITLE
[Bug] NPE getMessage reflected method is null (1.16.5 paper)

### ISSUE THREAD

**Issue by True-cc** [retrooper/packetevents#115]
```
[00:58:34 ERROR]: [packetevents] PacketEvents found an exception while calling a packet listener.
java.lang.NullPointerException: null
        at io.github.retrooper.packetevents.utils.nms.NMSUtils.readIChatBaseComponent(NMSUtils.java:473) ~[?:?]
        at io.github.retrooper.packetevents.packetwrappers.play.out.chat.WrappedPacketOutChat.getMessage(WrappedPacketOutChat.java:190) ~[?:?]
        at uwu.smsgamer.spygotutils.listener.spigot.SPacketProcessor.onPacketPlaySend(SPacketProcessor.java:21) ~[?:?]
        at io.github.retrooper.packetevents.event.impl.PacketPlaySendEvent.call(PacketPlaySendEvent.java:66) ~[?:?]
        at io.github.retrooper.packetevents.event.manager.EventManagerModern.callEvent(EventManagerModern.java:63) ~[?:?]
        at io.github.retrooper.packetevents.event.manager.EventManager.callEvent(EventManager.java:58) ~[?:?]
        at io.github.retrooper.packetevents.processor.PacketProcessorInternal.write(PacketProcessorInternal.java:170) ~[?:?]
        at io.github.retrooper.packetevents.injector.modern.PlayerChannelHandlerModern.write(PlayerChannelHandlerModern.java:59) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.16.5.jar:git-Paper-545]
        at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:57) ~[?:?]
        at protocolsupport.utils.netty.MessageToMessageCodec.write(MessageToMessageCodec.java:61) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.16.5.jar:git-Paper-545]
        at su.nexmedia.engine.nms.packets.PacketManager$1.write(PacketManager.java:109) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.16.5.jar:git-Paper-545]
        at kernitus.plugin.OldCombatMechanics.utilities.packet.PacketInjector.write(PacketInjector.java:178) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294) ~[patched_1.16.5.jar:git-Paper-545]
        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:305) ~[patched_1.16.5.jar:git-Paper-545]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:352) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.16.5.jar:git-Paper-545]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.16.5.jar:git-Paper-545]
        at java.lang.Thread.run(Thread.java:834) [?:?]
eval
```

**Comment by retrooper** [comment]
This has been fixed. Thank you so much for reporting. If you urgently need a Maven/Gradle dependency tag for the fix you can use this: https://jitpack.io/#retrooper/packetevents/dev-0d284e674a-1
If you urgently need a PacketEvents build that has this fixed you can download this: [Build](https://cdn.discordapp.com/attachments/743118267039744061/835598707599999016/packetevents-1.8-pre-13.jar)
Otherwise please wait for the next pre-release!
