### ISSUE TITLE
Metrics error

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#129]
> [19:27:26 WARN]: [GrimAC] Task #5420 for GrimAC v0.0.1-indev generated an exception
java.lang.NoClassDefFoundError: ac/grim/grimac/shaded/packetevents/bstats/Metrics$CustomChart
        at ac.grim.grimac.shaded.packetevents.bstats.Metrics$MetricsBase.submitData(Metrics.java:296) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-768]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-768]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-768]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-768]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-768]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-768]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-768]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: ac.grim.grimac.shaded.packetevents.bstats.Metrics$CustomChart
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.16.5.jar:git-Paper-768]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-768]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 9 more

Output of version command:
> [19:54:42 INFO]: Checking version, please wait...
[19:54:42 INFO]: This server is running Paper version git-Paper-768 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 8 version(s) behind
Previous version: git-Airplane-"3485304" (MC: 1.16.5)

PacketEvents version: 18a5656

**Comment by MWHunter** [comment]
I'll test on java 11 and report the results in around an hour, could be related to using java 16.

**Comment by MWHunter** [comment]
Unable to reproduce, strange.

**Comment by retrooper** [comment]
Odd
