### ISSUE TITLE
Async getEntities call in 1.17

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#132]
[18:39:18 WARN]: java.lang.reflect.InvocationTargetException
[18:39:18 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:39:18 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[18:39:18 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:39:18 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[18:39:18 WARN]:        at ac.grim.grimac.shaded.packetevents.utils.entityfinder.EntityFinderUtils.getEntityByIdWithWorld(EntityFinderUtils.java:106)
[18:39:18 WARN]:        at ac.grim.grimac.shaded.packetevents.utils.entityfinder.EntityFinderUtils.getEntityById(EntityFinderUtils.java:79)
[18:39:18 WARN]:        at ac.grim.grimac.shaded.packetevents.utils.nms.NMSUtils.getEntityById(NMSUtils.java:414)
[18:39:18 WARN]:        at ac.grim.grimac.shaded.packetevents.packetwrappers.api.helper.WrappedPacketEntityAbstraction.getEntity(WrappedPacketEntityAbstraction.java:75)
[18:39:18 WARN]:        at ac.grim.grimac.shaded.packetevents.packetwrappers.api.helper.WrappedPacketEntityAbstraction.getEntity(WrappedPacketEntityAbstraction.java:79)
[18:39:18 WARN]:        at ac.grim.grimac.events.packets.PacketEntityReplication.onPacketPlaySend(PacketEntityReplication.java:35)
[18:39:18 WARN]:        at ac.grim.grimac.shaded.packetevents.event.impl.PacketPlaySendEvent.call(PacketPlaySendEvent.java:78)
[18:39:18 WARN]:        at ac.grim.grimac.shaded.packetevents.event.manager.EventManagerModern.callEvent(EventManagerModern.java:58)
[18:39:18 WARN]:        at ac.grim.grimac.shaded.packetevents.event.manager.EventManager.callEvent(EventManager.java:52)
[18:39:18 WARN]:        at ac.grim.grimac.shaded.packetevents.processor.PacketProcessorInternal.write(PacketProcessorInternal.java:163)
[18:39:18 WARN]:        at ac.grim.grimac.shaded.packetevents.injector.modern.PlayerChannelHandlerModern.write(PlayerChannelHandlerModern.java:53)
[18:39:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[18:39:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[18:39:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[18:39:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[18:39:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[18:39:18 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:39:18 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:39:18 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[18:39:18 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[18:39:18 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[18:39:18 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[18:39:18 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[18:39:18 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[18:39:18 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:39:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[18:39:18 WARN]: Caused by: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
[18:39:18 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[18:39:18 WARN]:        at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2091)
[18:39:18 WARN]:        at net.minecraft.server.level.WorldServer.getEntity(WorldServer.java:1522)
[18:39:18 WARN]:        ... 30 more

Line that is causing this issue: https://github.com/MWHunter/Grim/blob/703adfb83ac86d1bb51ce4757c6a808eb1de67bc/src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java#L35

**Comment by MWHunter** [comment]
Seems to only occur when doing this for spawn entities packets sent immediately on login.  I've worked around this by indirectly waiting a bit before getting the entity, but this is still an issue for anyone who wants to get the entity immediately when the player has joined.

**Comment by retrooper** [comment]
Fixed in https://github.com/retrooper/packetevents/commit/f09617b2c2ac74499e6a1cc1b107e80efc5fcbf5
