### ISSUE TITLE
WrappedPacketInUseEntity null pointer

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#134]
> java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "io.github.retrooper.packetevents.packetwrappers.play.in.useentity.WrappedPacketInUseEntity.getObfuscatedEntityUseActionMethod" is null
        at io.github.retrooper.packetevents.packetwrappers.play.in.useentity.WrappedPacketInUseEntity.getAction(WrappedPacketInUseEntity.java:119) ~[?:?]
        at ac.grim.grimac.events.packets.PacketPlayerAttack.onPacketPlayReceive(PacketPlayerAttack.java:23) ~[?:?]
        at io.github.retrooper.packetevents.event.impl.PacketPlayReceiveEvent.call(PacketPlayReceiveEvent.java:61) ~[?:?]
        at io.github.retrooper.packetevents.event.manager.EventManagerModern.callEvent(EventManagerModern.java:58) ~[?:?]
        at io.github.retrooper.packetevents.event.manager.EventManager.callEvent(EventManager.java:52) ~[?:?]
        at io.github.retrooper.packetevents.processor.PacketProcessorInternal.read(PacketProcessorInternal.java:108) ~[?:?]
        at io.github.retrooper.packetevents.injector.modern.PlayerChannelHandlerModern.channelRead(PlayerChannelHandlerModern.java:40) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.jar:git-Paper-53]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.jar:git-Paper-53]
        at java.lang.Thread.run(Thread.java:831) [?:?]

Code that will cause this:
if (event.getPacketId() == PacketType.Play.Client.USE_ENTITY) {
WrappedPacketInUseEntity action = new WrappedPacketInUseEntity(event.getNMSPacket());
action.getAction()

**Comment by MWHunter** [comment]
Reproduce by right clicking an entity on 1.17

**Comment by retrooper** [comment]
Failed to reproduce on https://github.com/retrooper/packetevents/commit/267468f731d0426f8939a72431a058088b71acb6

**Comment by retrooper** [comment]
Oh no, different result on Paper, now I need to account for paper?

**Comment by MWHunter** [comment]
Able to reproduce on paper, unable to reproduce on spigot

**Comment by retrooper** [comment]
I'm failing to understand why its not working on Paper, I will try again in a bit.

**Comment by retrooper** [comment]
Fixed in https://github.com/retrooper/packetevents/commit/8722dd0c34e3869c377a5a4cf36f6b771160187a
