### ISSUE TITLE
1.17.1 issue with PacketPlayOutEntityDestroy

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#139]
> io.github.retrooper.packetevents.exceptions.WrapperFieldNotFoundException: PacketEvents failed to find a int indexed 0 by its type in the net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy class!
        at io.github.retrooper.packetevents.packetwrappers.WrappedPacket.getField(WrappedPacket.java:508) ~[?:?]
        at io.github.retrooper.packetevents.packetwrappers.WrappedPacket.read(WrappedPacket.java:288) ~[?:?]
        at io.github.retrooper.packetevents.packetwrappers.WrappedPacket.readInt(WrappedPacket.java:194) ~[?:?]
        at io.github.retrooper.packetevents.packetwrappers.play.out.entitydestroy.WrappedPacketOutEntityDestroy.getEntityId(WrappedPacketOutEntityDestroy.java:89) ~[?:?]
        at io.github.retrooper.packetevents.packetwrappers.play.out.entitydestroy.WrappedPacketOutEntityDestroy.getEntityIds(WrappedPacketOutEntityDestroy.java:121) ~[?:?]
        at ac.grim.grimac.events.packets.PacketFireworkListener.onPacketPlaySend(PacketFireworkListener.java:61) ~[?:?]
        at io.github.retrooper.packetevents.event.impl.PacketPlaySendEvent.call(PacketPlaySendEvent.java:78) ~[?:?]
        at io.github.retrooper.packetevents.event.manager.EventManagerModern.callEvent(EventManagerModern.java:58) ~[?:?]
        at io.github.retrooper.packetevents.event.manager.EventManager.callEvent(EventManager.java:52) ~[?:?]
        at io.github.retrooper.packetevents.processor.PacketProcessorInternal.write(PacketProcessorInternal.java:163) ~[?:?]
        at io.github.retrooper.packetevents.injector.modern.PlayerChannelHandlerModern.write(PlayerChannelHandlerModern.java:46) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Paper-97]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[patched_1.17.1.jar:git-Paper-97]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[patched_1.17.1.jar:git-Paper-97]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[patched_1.17.1.jar:git-Paper-97]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[patched_1.17.1.jar:git-Paper-97]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[patched_1.17.1.jar:git-Paper-97]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[patched_1.17.1.jar:git-Paper-97]
        at net.minecraft.network.Connection.a(Connection.java:315) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$4(Connection.java:295) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.17.1.jar:git-Paper-97]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.17.1.jar:git-Paper-97]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[patched_1.17.1.jar:git-Paper-97]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Paper-97]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Paper-97]
        at java.lang.Thread.run(Thread.java:831) [?:?]

Occurs on paper 1.17.1 and spigot 1.17.1  Does not occur on paper 1.17 and spigot 1.17.

**Comment by MWHunter** [comment]
The code causing this is 

WrappedPacketOutEntityDestroy destroy = new WrappedPacketOutEntityDestroy(event.getNMSPacket());
destroy.getEntityIds()

destroy.getEntityId() also works

**Comment by retrooper** [comment]
Thanks
