### ISSUE TITLE
Metadata wrong on 1.16

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#227]
Listening to the metadata packet will create invalid metadata packets:

[14:03:41 WARN]: {Packet Type: ENTITY_METADATA, Type: MetaData List, Data: [Pair{Type|VarInt, 25}], Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$6 (Anonymous), Packet ID: 77}
[14:03:41 WARN]: Actual Error:
[14:03:41 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(1) exceeds writerIndex(9): PooledUnsafeDirectByteBuf(ridx: 9, widx: 9, cap: 256)
[14:03:41 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477)
[14:03:41 WARN]:        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:731)

**Comment by retrooper** [comment]
Thanks for reporting, will look into it.
