### ISSUE TITLE
1.7 clients disconnected for right clicking block

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#265]
[04:17:08 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 7
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.BlockFace.getBlockFaceByValue(BlockFace.java:90) ~[grimac-2.0.17-all.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientPlayerDigging.readData(WrapperPlayClientPlayerDigging.java:63) ~[grimac-2.0.17-all.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:91) ~[grimac-2.0.17-all.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:74) ~[grimac-2.0.17-all.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientPlayerDigging.<init>(WrapperPlayClientPlayerDigging.java:35) ~[grimac-2.0.17-all.jar:?]
        at ac.grim.grimac.events.packets.CheckManagerListener.onPacketReceive(CheckManagerListener.java:384) ~[grimac-2.0.17-all.jar:?

**Comment by retrooper** [comment]
Why is the face -1?

**Comment by retrooper** [comment]
I see, this can't be only on 1.7, right

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/3a6778eee7de853764f7ede26880ae318fd477fb
