### ISSUE TITLE
PacketEvents 2.0 is broken

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#281]
[22:05:33 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.NoSuchMethodError: 'net.kyori.adventure.util.Codec net.kyori.adventure.util.Codec.codec(net.kyori.adventure.util.Codec$Decoder, net.kyori.adventure.util.Codec$Encoder)'
        at net.kyori.adventure.text.serializer.gson.legacyimpl.NBTLegacyHoverEventSerializerImpl.<clinit>(NBTLegacyHoverEventSerializerImpl.java:43) ~[grim.jar:?]
        at net.kyori.adventure.text.serializer.gson.legacyimpl.NBTLegacyHoverEventSerializer.get(NBTLegacyHoverEventSerializer.java:43) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.AdventureSerializer.<clinit>(AdventureSerializer.java:37) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.MappingHelper.getJSONObject(MappingHelper.java:47) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.states.WrappedBlockState.loadModern(WrappedBlockState.java:161) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.states.WrappedBlockState.<clinit>(WrappedBlockState.java:47) ~[grim.jar:?]
        at ac.grim.grimac.utils.latency.CompensatedWorld.<clinit>(CompensatedWorld.java:36) ~[grim.jar:?]
        at ac.grim.grimac.player.GrimPlayer.<init>(GrimPlayer.java:230) ~[grim.jar:?]
        at ac.grim.grimac.utils.anticheat.PlayerDataManager.getPlayer(PlayerDataManager.java:36) ~[grim.jar:?]
        at ac.grim.grimac.events.packets.CheckManagerListener.onPacketSend(CheckManagerListener.java:877) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:47) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:63) ~[grim.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.latest.handlers.PacketEncoderLatest.read(PacketEncoderLatest.java:54) ~[grim.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.latest.handlers.PacketEncoderLatest.encode(PacketEncoderLatest.java:87) ~[grim.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:428) ~[?:?]
        at net.minecraft.network.Connection.lambda$writePacket$8(Connection.java:402) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by retrooper** [comment]
Hopefully fixed by https://github.com/retrooper/packetevents/commit/16c4c749e98ac1f18fd475537d3f7a1a87f1a025
