### ISSUE TITLE
Login success broken on 1.8

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#283]
[11:30:57 WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.RuntimeException: The received encoded string buffer length is longer than maximum allowed (1633962 > 144)
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:366) ~[grim.jar:?]
        at com.github.retrooper.packetevents.wrapper.login.server.WrapperLoginServerLoginSuccess.readData(WrapperLoginServerLoginSuccess.java:66) ~[grim.jar:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:153) ~[grim.jar:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:100) ~[grim.jar:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:90) ~[grim.jar:?]
        at com.github.retrooper.packetevents.wrapper.login.server.WrapperLoginServerLoginSuccess.<init>(WrapperLoginServerLoginSuccess.java:37) ~[grim.jar:?]
        at com.github.retrooper.packetevents.manager.InternalPacketListener.onPacketSend(InternalPacketListener.java:55) ~[grim.jar:?]
        at com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:47) ~[grim.jar:?]
        at com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:63) [grim.jar:?]
        at io.github.retrooper.packetevents.injector.latest.handlers.PacketEncoderLatest.read(PacketEncoderLatest.java:54) [grim.jar:?]
        at io.github.retrooper.packetevents.injector.latest.handlers.PacketEncoderLatest.encode(PacketEncoderLatest.java:87) [grim.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]

**Comment by retrooper** [comment]
Always give me information on what commit you’re using and plugins

**Comment by MWHunter** [comment]
Plugins (4): ViaVersion, ViaBackwards, ViaRewind, GrimAC
Latest 2.0

Works fine on a9876a0cec

**Comment by MWHunter** [comment]
seems to work now, was viaversion issue

**Comment by MWHunter** [comment]
probably got fixed by shading adventure correctly, as that was the thing I changed when it started working
