### ISSUE TITLE
PacketEvents exception after reload on 1.18.1 whenever a user joins.

### ISSUE THREAD

**Issue by modern158** [retrooper/packetevents#289]
Server version: 1.18.1
Plugins: Geyser, Floodgate 2.0 and the my plugin
It throws this error when trying to log in with Minecraft Bedrock through Geyser 
```
[19:52:32 ERROR]: Could not pass event PlayerJoinEvent to MyPlugin v1.0-SNAPSHOT
java.lang.IllegalStateException: PacketEvents failed to find a List indexed 0 by its type in the com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler class!
        at com.github.retrooper.packetevents.util.reflection.ReflectionObject.getField(ReflectionObject.java:297) ~[MyPlugin-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.packetevents.util.reflection.ReflectionObject.read(ReflectionObject.java:159) ~[MyPlugin-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.packetevents.util.reflection.ReflectionObject.readList(ReflectionObject.java:284) ~[MyPlugin-1.0-SNAPSHOT.jar:?]
        at io.github.retrooper.packetevents.handlers.modern.early.EarlyChannelInjectorModern.getEncoder(EarlyChannelInjectorModern.java:281) ~[MyPlugin-1.0-SNAPSHOT.jar:?]
        at io.github.retrooper.packetevents.handlers.modern.early.EarlyChannelInjectorModern.updateUser(EarlyChannelInjectorModern.java:203) ~[MyPlugin-1.0-SNAPSHOT.jar:?]
        at io.github.retrooper.packetevents.handlers.SpigotChannelInjector.updateUser(SpigotChannelInjector.java:86) ~[MyPlugin-1.0-SNAPSHOT.jar:?]
        at io.github.retrooper.packetevents.manager.player.PlayerManagerImpl.getUser(PlayerManagerImpl.java:101) ~[MyPlugin-1.0-SNAPSHOT.jar:?]
        at io.github.retrooper.packetevents.processor.InternalBukkitListener.onJoin(InternalBukkitListener.java:41) ~[MyPlugin-1.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor11.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-216]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:305) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:555) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by retrooper** [comment]
Are you perhaps reloading or so?

**Comment by modern158** [comment]
> Are you perhaps reloading or so?

Yeah it was caused by reload. But now I dont receive any packet from Geyser player. Btw I am using 2.0-97b7e81908-1 spigot packetevents.

**Comment by retrooper** [comment]
Maybe try it again, but this specifically shouldn't happen anymore.

**Comment by MWHunter** [comment]
https://github.com/MWHunter/Grim/issues/518

**Comment by MWHunter** [comment]
actually this isn't related
