### ISSUE TITLE
1.7 players are broken

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#339]
[19:42:08 INFO]: DefineOutside joined the game
[19:42:08 INFO]: DefineOutside[/127.0.0.1:51317] logged in with entity id 489 at ([world]203.49666077218595, 65.0, 140.4802544136537)
[19:42:08 WARN]: [ViaVersion] ERROR IN Protocol1_16_4To1_17 IN REMAP OF WINDOW_CONFIRMATION (0x07)
[19:42:08 WARN]: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[19:42:08 WARN]: {Packet Type: null, Type: Unsigned Byte, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$4 (Anonymous), Packet ID: -1}
[19:42:08 WARN]: Actual Error:
[19:42:08 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477)
[19:42:08 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:42:08 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[19:42:08 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:42:08 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:42:08 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:42:08 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:42:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[19:42:08 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[19:42:08 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
[19:42:08 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
[19:42:08 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
[19:42:08 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[19:42:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[19:42:08 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:42:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[19:42:08 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template

Paper 1.18.2.  Send ping packet and you will break something.

**Comment by MWHunter** [comment]
Also broken on 1.8:

[19:44:30 INFO]: DefineOutside[/127.0.0.1:51389] logged in with entity id 2083 at ([world]211.5, 76.0, 248.5)
[19:44:32 WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex(103) + length(102400) exceeds writerIndex(12934): UnpooledHeapByteBuf(ridx: 103, widx: 12934, cap: 16384)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:676) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:684) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readBytes(ByteBufOperatorModernImpl.java:185) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readBytes(ByteBufHelper.java:187) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readBytes(PacketWrapper.java:507) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerChunkDataBulk.read_1_8(WrapperPlayServerChunkDataBulk.java:78) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerChunkDataBulk.read(WrapperPlayServerChunkDataBulk.java:53) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:151) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:100) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:90) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerChunkDataBulk.<init>(WrapperPlayServerChunkDataBulk.java:47) ~[grim.jar:?]
        at ac.grim.grimac.events.packets.worldreader.BasePacketWorldReader.handleMapChunkBulk(BasePacketWorldReader.java:64) ~[grim.jar:?]
        at ac.grim.grimac.events.packets.worldreader.BasePacketWorldReader.onPacketSend(BasePacketWorldReader.java:37) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:48) ~[grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) [grim.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:39) [grim.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEncoder.encode(PacketEncoder.java:59) [grim.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by retrooper** [comment]
Can you please give me more information by following the format. Server brand (including server version) and plugins so I know what I need to reproduce.

**Comment by retrooper** [comment]
Related to any other issue?

**Comment by MWHunter** [comment]
it's broken on 1.8 and 1.18 servers.  Not related to any server brand.  Via* is being used for 1.7 support.

**Comment by retrooper** [comment]
1.7 players work for me.

**Comment by retrooper** [comment]
Assume its a chunk packet issue?

**Comment by Tofaa2** [comment]
> Can you please give me more information by following the format. Server brand (including server version) and plugins so I know what I need to reproduce.

in 1.8 players dont really work properly. Same with my issue where it returns null

**Comment by MWHunter** [comment]
> i think the title need to be a bit more precise. Just looking at "1.7 players are broken" makes me think they cannot even log in or so.

I still can't log in with a 1.7 player.  Enable the debug listener and you won't be able to log in either.  Might need protocollib too


[21:59:37 WARN]: [ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF UPDATE_SCORE (0x3C)
[21:59:37 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[21:59:37 WARN]: {Packet Type: UPDATE_SCORE, Type: Byte, Data: [Pair{Type|String, DefineOutside}], Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.ScoreboardPackets$2 (Anonymous), Packet ID: 60}
[21:59:37 WARN]: Actual Error:
[21:59:37 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[21:59:37 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[21:59:37 WARN]:        at spigot.jar//io.github.retrooper.packetevents.injector.handlers.PacketEncoder.write(PacketEncoder.java:98)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:697)
[21:59:37 WARN]:        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[21:59:37 WARN]:        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
[21:59:37 WARN]:        at ProtocolLib(3).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:195)
[21:59:37 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:462)
[21:59:37 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$10(NetworkManager.java:431)
[21:59:37 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[21:59:37 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[21:59:37 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
[21:59:37 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[21:59:37 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:59:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MWHunter** [comment]
[03:04:46 INFO]: DefineOutside[/MY.IP.WAS.HERE:62202] logged in with entity id 303 at ([AnticheatTest]-2.569144773992287, 5.0, -77.01910864592618)
[03:04:46 WARN]: [ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF UPDATE_SCORE (0x3C)
[03:04:46 INFO]: Welcome DefineOutside!
[03:04:46 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[03:04:46 WARN]: {Packet Type: UPDATE_SCORE, Type: Byte, Data: [Pair{Type|String, §9§r}], Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.ScoreboardPackets$2 (Anonymous), Packet ID: 60}
[03:04:46 WARN]: Actual Error: 
[03:04:46 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[03:04:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[03:04:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[03:04:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[03:04:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[03:04:46 WARN]:        at grimac-2.3.5-all(1).jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:98)
[03:04:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[03:04:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[03:04:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[03:04:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[03:04:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[03:04:46 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[03:04:46 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[03:04:46 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:463)
[03:04:46 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:437)
[03:04:46 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[03:04:46 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[03:04:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[03:04:46 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
[03:04:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[03:04:46 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[03:04:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[03:04:46 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template

Still an issue

**Comment by MWHunter** [comment]
Not the fault of PacketEvents, will be fixed with https://github.com/ViaVersion/ViaBackwards/pull/462
