### ISSUE TITLE
ServerChatMessage exception

### ISSUE THREAD

**Issue by ilovefuud** [retrooper/packetevents#404]
**Describe the bug**
Exception below, errors on achievement being sent to player.

**Software brand**
Latest Spigot 1.8.8 

**Plugins**
Please give us a list of your plugins. Sometimes we run into incompatibilities. Having an overview of the plugins on your server can really help identify the problem quicker.
Eg. ViaVersion, ProtocolLib, HolographicDisplays
You may also provide a screenshot.

**How To Reproduce**
Send some achievement to a player.

**Expected behavior**
No exception

**Screenshots**
None

**Additional context**

    @Override
    public void handle(PacketSendEvent event, PlayerData playerData) {
        if (event.getPacketType() == PacketType.Play.Server.CHAT_MESSAGE) {
            WrapperPlayServerChatMessage wrapper = new WrapperPlayServerChatMessage(event); <--- this line exceptions
            if (wrapper.getChatComponentJson().contains("$jndi:ldap")) {
                flag(event);
            }
        }
    }

[21:15:00 WARN]: PacketEvents caught an unhandled exception while calling your listener.
com.github.retrooper.titanium.packetevents.libs.com.google.gson.JsonParseException: invalid hover action:  show_achievement
        at com.github.retrooper.titanium.packetevents.libs.net.kyori.adventure.text.serializer.gson.IndexedSerializer.read(IndexedSerializer.java:58) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.Gson.fromJson(Gson.java:932) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.Gson.fromJson(Gson.java:1003) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.Gson.fromJson(Gson.java:975) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:144) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:49) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.Gson.fromJson(Gson.java:932) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.Gson.fromJson(Gson.java:1003) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.Gson.fromJson(Gson.java:975) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:214) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.Gson.fromJson(Gson.java:932) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:173) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.Gson.fromJson(Gson.java:932) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:139) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.Gson.fromJson(Gson.java:932) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.Gson.fromJson(Gson.java:897) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.Gson.fromJson(Gson.java:846) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.com.google.gson.Gson.fromJson(Gson.java:817) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:84) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.libs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.util.AdventureSerializer.parseComponent(AdventureSerializer.java:60) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.wrapper.play.server.WrapperPlayServerChatMessage.read(WrapperPlayServerChatMessage.java:72) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:161) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:103) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:93) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.wrapper.play.server.WrapperPlayServerChatMessage.<init>(WrapperPlayServerChatMessage.java:40) ~[titanium-1.0-SNAPSHOT.jar:?]
        at me.jaden.titanium.check.impl.crasher.CrasherC.handle(CrasherC.java:38) ~[titanium-1.0-SNAPSHOT.jar:?]
        at me.jaden.titanium.check.CheckManager$1.onPacketPlaySend(CheckManager.java:97) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.event.SimplePacketListenerAbstract.onPacketSend(SimplePacketListenerAbstract.java:56) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:48) ~[titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.event.EventManager.callEvent(EventManager.java:51) [titanium-1.0-SNAPSHOT.jar:?]
        at com.github.retrooper.titanium.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:41) [titanium-1.0-SNAPSHOT.jar:?]
        at io.github.retrooper.titanium.packetevents.injector.handlers.PacketEncoder.encode(PacketEncoder.java:67) [titanium-1.0-SNAPSHOT.jar:?]
        at io.github.retrooper.titanium.packetevents.injector.handlers.PacketEncoder.write(PacketEncoder.java:81) [titanium-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by retrooper** [comment]
Use https://pastebin.com and update this message.

**Comment by ilovefuud** [comment]
https://pastebin.com/RJqsJ3d1

**Comment by AbhigyaKrishna** [comment]
its a issue with adventure desrializer

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/a7a9ef52f002741fda0a3eb4f741b19ad2e2e86a
