### ISSUE TITLE
"Crasher" UPDATE SIGN throws vanilla exception.

### ISSUE THREAD

**Issue by jtJava** [retrooper/packetevents#405]
**Describe the bug**
An exception happens when placing a "crasher sign." Not sure if this is a Via or PacketEvents issue. Exception at bottom.

**Software brand**
Latest 1.8.8 Spigot

**Plugins**
ViaVersion, and my own.

**How To Reproduce**

**Expected behavior**
No exception.

**Screenshots**
None

**Additional context**
21:19:30 WARN]: java.lang.reflect.InvocationTargetException

[21:19:30 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)

[21:19:30 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[21:19:30 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[21:19:30 WARN]:        at io.github.retrooper.titanium.packetevents.util.viaversion.CustomPipelineUtil.callDecode(CustomPipelineUtil.java:70)

[21:19:30 WARN]:        at io.github.retrooper.titanium.packetevents.injector.handlers.PacketDecoder.decode(PacketDecoder.java:102)

[21:19:30 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)

[21:19:30 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[21:19:30 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[21:19:30 WARN]:        at com.viaversion.viaversion.util.PipelineUtil.callDecode(PipelineUtil.java:75)

[21:19:30 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:59)

[21:19:30 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)

[21:19:30 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)

[21:19:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

[21:19:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

[21:19:30 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)

[21:19:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

[21:19:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

[21:19:30 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)

[21:19:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

[21:19:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

[21:19:30 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)

[21:19:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

[21:19:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

[21:19:30 WARN]:        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)

[21:19:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

[21:19:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

[21:19:30 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)

[21:19:30 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)

[21:19:30 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)

[21:19:30 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)

[21:19:30 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)

[21:19:30 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)

[21:19:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)

[21:19:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

[21:19:30 WARN]: Caused by: io.netty.handler.codec.DecoderException: The received encoded string buffer length is longer than maximum allowed (32767 > 1536)

[21:19:30 WARN]:        at net.minecraft.server.v1_8_R3.PacketDataSerializer.c(PacketDataSerializer.java:212)

[21:19:30 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInUpdateSign.a(SourceFile:31)

[21:19:30 WARN]:        at net.minecraft.server.v1_8_R3.PacketDecoder.decode(SourceFile:40)

[21:19:30 WARN]:        ... 34 more

**Comment by ilovefuud** [comment]
https://pastebin.com/zNMYVxci

**Comment by retrooper** [comment]
Does this occur without PacketEvents too?

**Comment by ilovefuud** [comment]
It doesn't print exception but says io.netty.handler.codec.DecoderException: The received encoded string buffer length is longer than maximum allowed (32767 > 1536)

**Comment by MWHunter** [comment]
I'd say to not stacktrace when a user throws an exception here.  And to also kick the user for having an exception here.

**Comment by MWHunter** [comment]
closing due to new injector
