### ISSUE TITLE
Complete 1.19 support

### ISSUE THREAD

**Issue by retrooper** [retrooper/packetevents#422]
Still have to make the WrapperPlayServerSystemMessage wrapper and complete some wrappers, might not be a full list but: ChatMessage wrapper, LoginStart wrapper, EncryptionResponse wrapper, LoginSuccess wrapper.

**Comment by retrooper** [comment]
+Mappings

**Comment by MWHunter** [comment]
I’ll take responsibility to update all the json and other custom mappings

**Comment by retrooper** [comment]
Appreciated!

**Comment by MWHunter** [comment]
New 1.19 items, starting with items that are also blocks

mud
mangrove_planks
mangrove_propagule
mangrove_logs
mangrove_roots
muddy_mangrove_roots
stripped_mangrove_log
stripped_mangrove_wood
mangrove_wood
mangrove_leaves
mangrove_slab
mud_brick_slab
mangrove_fence
packed_mud
mud_bricks
reinforced_deepslate
mud_brick_stairs
sculk
sculk_vein
sculk_catalyst
sculk_shrieker
mud_brick_wall
mangrove_button
mangrove_pressure_plate
mangrove_door
mangrove_trapdoor
mangrove_fence_gate
mangrove_sign

tadpole_bucket
recovery_bucket

allay_spawn_egg
frog_spawn_egg
tadpole_spawn_egg
warden_spawn_egg

music_disc_
disc_fragment_

ochre_froglight
verdant_froglight
pearlescent_froglight
frogspawn
echo_shard
goat_horn

oak_chest_boat
spruce_chest_boat
birch_chest_boat
jungle_chest_boat
acacia_chest_boat
dark_oak_chest_boat
mangrove_boat
mangrove_chest_boat

**Comment by MWHunter** [comment]
All that is left to do is to update SpigotReflectionUtil to reflect the new mappings, and add the missing block tags from the BlockTags class (should we keep this class?  Is it overkill?)

**Comment by MWHunter** [comment]
I'll circle back around after updating grim to finish... but feel free to finish it for me.  I've left todo comments in BlockTags with the missing tags.

**Comment by MWHunter** [comment]
[21:31:22] [Server thread/ERROR]: Error occurred while enabling GrimAC v2.2.17 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant com.github.retrooper.packetevents.protocol.packettype.PacketType.Play.Server.SYSTEM_CHAT_MESSAGE
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at com.github.retrooper.packetevents.protocol.packettype.PacketType$Play$Server.valueOf(PacketType.java:399) ~[?:?]
        at com.github.retrooper.packetevents.protocol.packettype.PacketType$Play$Server.loadPacketIds(PacketType.java:556) ~[?:?]
        at com.github.retrooper.packetevents.protocol.packettype.PacketType$Play$Server.load(PacketType.java:566) ~[?:?]
        at com.github.retrooper.packetevents.protocol.packettype.PacketType.prepare(PacketType.java:71) ~[?:?]
        at io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.init(SpigotPacketEventsBuilder.java:142) ~[?:?]
        at ac.grim.grimac.manager.init.start.PacketManager.start(PacketManager.java:41) ~[?:?]
        at ac.grim.grimac.manager.InitManager.start(InitManager.java:44) ~[?:?]
        at ac.grim.grimac.GrimAPI.start(GrimAPI.java:30) ~[?:?]
        at ac.grim.grimac.GrimAC.onEnable(GrimAC.java:19) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:513) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3501-Spigot-63a0604-53b681b]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:427) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3501-Spigot-63a0604-53b681b]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:582) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3501-Spigot-63a0604-53b681b]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3501-Spigot-63a0604-53b681b]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3501-Spigot-63a0604-53b681b]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3501-Spigot-63a0604-53b681b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3501-Spigot-63a0604-53b681b]
        at java.lang.Thread.run(Thread.java:833) [?:?]


@retrooper I'm not fixing this error, you should try to fix this

**Comment by MWHunter** [comment]
I fixed that error, the following now needs work before we are considered released for 1.19:
- SpigotReflectionUtil 
- Sequence ID should be added to existing packets that use sequence ID (this is stupidly easy to do, just reading a varint)
- Sequence ID confirmation packet wrapper.  This is literally a single field packet, stupidly easy to add so you might as well do it

SpigotReflectionUtil is quite important as otherwise PacketEvents sees the server as running 1.8.

Tasks not blocking release but should be added later:
- New tags - not many, if anyone, will be using these tags.  I claim responsibility for the tags system as I added it for grim.
- Other new wrapper packets such as chat

**Comment by MWHunter** [comment]
It's because I write it manually every update because I forgot where I put the code lol.  It takes like 15 minutes to do every half year so whatever.

**Comment by MWHunter** [comment]
Current exception I can't figure out how to debug, I've taken care of the other exceptions that were spamming console:

[21:38:22] [Netty Server IO #1/WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex(53) + length(2) exceeds writerIndex(54): PooledUnsafeDirectByteBuf(ridx: 53, widx: 54, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.76.Final.jar:4.1.76.Final]
        at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749) ~[netty-buffer-4.1.76.Final.jar:4.1.76.Final]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readShort(ByteBufOperatorModernImpl.java:79) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readShort(ByteBufHelper.java:95) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readShort(PacketWrapper.java:429) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerSpawnEntity.read(WrapperPlayServerSpawnEntity.java:110) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:158) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:104) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:94) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerSpawnEntity.<init>(WrapperPlayServerSpawnEntity.java:47) ~[?:?]
        at ac.grim.grimac.events.packets.PacketEntityReplication.onPacketSend(PacketEntityReplication.java:86) ~[?:?]
        at ac.grim.grimac.manager.CheckManager.lambda$onPacketSend$3(CheckManager.java:170) ~[?:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
        at ac.grim.grimac.manager.CheckManager.onPacketSend(CheckManager.java:170) ~[?:?]
        at ac.grim.grimac.events.packets.CheckManagerListener.onPacketSend(CheckManagerListener.java:741) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:48) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:41) ~[?:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[?:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:81) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:227) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3501-Spigot-63a0604-53b681b]
        at net.minecraft.network.NetworkManager.lambda$7(NetworkManager.java:216) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3501-Spigot-63a0604-53b681b]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.76.Final.jar:4.1.76.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-common-4.1.76.Final.jar:4.1.76.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.76.Final.jar:4.1.76.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.76.Final.jar:4.1.76.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.76.Final.jar:4.1.76.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by MWHunter** [comment]
Nevermind, the protocol wiki hasn't been changed yet and that packet changed a bit.  I've fixed the protocol wiki and packetevents.  Theoretically everything should work now.

**Comment by MWHunter** [comment]
Entity type mappings are wrong and are returning null

**Comment by MWHunter** [comment]
I've fixed the entity type mappings and fixed some other bugs

**Comment by MWHunter** [comment]
Tasks that should be added later:
    New tags - not many, if anyone, will be using these tags. I would like to remove BlockTags from PacketEvents.
    Other new wrapper packets such as chat

**Comment by MWHunter** [comment]
ItemType mappings are not implemented

**Comment by MWHunter** [comment]
PlayerInfo packet isn't implemented correctly

**Comment by MWHunter** [comment]
I implemented the above tasks... these are the current tasks separated into bugs and features:

Bugs:
set beacon effect has changed and won't work 
sound, entity sound, named sound are missing a field and will re-serialize incorrectly

New packets:
chat preview
server data packet
serverbound command packet

**Comment by NoJokeFNA** [comment]
The bugs should be fixed now

**Comment by NoJokeFNA** [comment]
Now only the command packet is missing

**Comment by NoJokeFNA** [comment]
Everything is done!

**Comment by LucidAPs** [comment]
Update for 1.19 please!

**Comment by retrooper** [comment]
TODO: Check EntityEffect on 1.19. Seems like we don't write optional factor data.

**Comment by retrooper** [comment]
Done i guess (for 2.0)

**Comment by retrooper** [comment]
Might be lacking some new wrappers for 1.19 like chat preview and so on.

**Comment by retrooper** [comment]
Seems like we have them thanks to a PR.
