### ISSUE TITLE
itemstack conversion throwing exception

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#437]
[13:41:26] [Netty Epoll Server IO #3/WARN]: java.lang.reflect.InvocationTargetException
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotReflectionUtil.writeNMSItemStackPacketDataSerializer(SpigotReflectionUtil.java:631)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotReflectionUtil.decodeBukkitItemStack(SpigotReflectionUtil.java:516)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotConversionUtil.fromBukkitItemStack(SpigotConversionUtil.java:106)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.utils.latency.CompensatedInventory.getBoots(CompensatedInventory.java:105)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.predictionengine.MovementCheckRunner.check(MovementCheckRunner.java:443)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.predictionengine.MovementCheckRunner.processAndCheckMovementPacket(MovementCheckRunner.java:70)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.checks.impl.movement.PredictionRunner.onPositionUpdate(PredictionRunner.java:15)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.manager.CheckManager.lambda$onPositionUpdate$4(CheckManager.java:174)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at com.google.common.collect.ImmutableList.forEach(:408)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.manager.CheckManager.onPositionUpdate(CheckManager.java:174)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.events.packets.CheckManagerListener.handleFlying(CheckManagerListener.java:641)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.events.packets.CheckManagerListener.onPacketReceive(CheckManagerListener.java:348)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:81)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:67)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:89)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.util.PipelineUtil.callDecode(PipelineUtil.java:75)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:59)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(:508)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(:447)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(:276)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:379)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:365)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(:357)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(:324)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(:296)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:379)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:365)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(:357)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(:324)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(:311)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(:432)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(:276)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:379)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:365)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(:357)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(:286)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:379)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:365)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(:357)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(:152)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:379)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:365)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(:357)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(:1410)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:379)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:365)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(:919)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(:795)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(:480)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(:378)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(:989)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(:74)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:41:26] [Netty Epoll Server IO #3/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 256)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(:1478)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at io.netty.buffer.AbstractByteBuf.readByte(:732)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_12_R1.PacketDataSerializer.readByte(:711)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_12_R1.PacketDataSerializer.j(:225)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_12_R1.PacketDataSerializer.setItemTag(:313)
[13:41:26] [Netty Epoll Server IO #3/WARN]: 	... 62 more

**Comment by MWHunter** [comment]
perhaps fixed with 50ef62f4

This error report doesn't make sense though, the only explaination is that the user had an error when writing the packet due to using a shitty MCM fork that renamed this method (now fixed).  But they only submitted the second error that occurred due to the writing failing.  As it's impossible to write 0 bytes as an item, it always has to be at least one byte.
