### ISSUE TITLE
Integer vannot be cast to long

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#444]
[12:21:19 WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
        at com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientKeepAlive.read(WrapperPlayClientKeepAlive.java:46) ~[grim.jar:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:169) ~[grim.jar:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:99) ~[grim.jar:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:89) ~[grim.jar:?]
        at com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientKeepAlive.<init>(WrapperPlayClientKeepAlive.java:36) ~[grim.jar:?]
        at ac.grim.grimac.checks.impl.badpackets.BadPacketsO.onPacketReceive(BadPacketsO.java:35) ~[grim.jar:?]
        at ac.grim.grimac.manager.CheckManager.lambda$onPacketReceive$1(CheckManager.java:161) ~[grim.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_332]
        at ac.grim.grimac.manager.CheckManager.onPacketReceive(CheckManager.java:161) ~[grim.jar:?]
        at ac.grim.grimac.events.packets.CheckManagerListener.onPacketReceive(CheckManagerListener.java:462) ~[grim.jar:?]
        at com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[grim.jar:?]
        at com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) [grim.jar:?]
        at com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:81) [grim.jar:?]
        at io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:67) [grim.jar:?]
        at io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:89) [grim.jar:?]
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at com.viaversion.viaversion.util.PipelineUtil.callDecode(PipelineUtil.java:75) [ViaVersion-4.3.1.jar:?]
        at com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:59) [ViaVersion-4.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]

[12:21:57 INFO]: This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by NoJokeFNA** [comment]
Are you using the latest update from PE? Because this line doesn't make any sense in the current code: https://github.com/retrooper/packetevents/blob/2.0/api/src/main/java/com/github/retrooper/packetevents/wrapper/play/client/WrapperPlayClientKeepAlive.java#L46
