### ISSUE TITLE
error on reloading with reinjecting into a player

### ISSUE THREAD

**Issue by yanjulang** [retrooper/packetevents#469]
**Describe the bug**
When I reload the server with a player online, packetevents fails to inject into that player because the handler hasn't been removed from the player's channel properly

**Software brand**
Paper Spigot 1.8.9 // This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT
packetevents 2.0.0-SNAPSHOT

**Plugins**
just my plugin using packetevents

**How To Reproduce**
make a plugin using packetevents, standard procedure for onLoad, onEnable, onDisable, have a player be on the server, do /reload

**Expected behavior**
unregister the old decoder and don't throw an error

**Additional infos**
Error:
`[00:29:04 WARN]: java.lang.IllegalArgumentException: Duplicate handler name: pe-decoder-<pluginname>
[00:29:04 WARN]:        at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:900)
[00:29:04 WARN]:        at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:189)
[00:29:04 WARN]:        at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:181)
[00:29:04 WARN]:        at packetevents.packetevents.injector.connection.ServerConnectionInitializer.initChannel(ServerConnectionInitializer.java:95)
[00:29:04 WARN]:        at packetevents.packetevents.injector.SpigotChannelInjector.inject(SpigotChannelInjector.java:117)
[00:29:04 WARN]:        at packetevents.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:115)
[00:29:04 WARN]:        at de.yanjulang.xxx.packet.system.PacketEventsPacketSystem.<init>(PacketEventsPacketSystem.java:44)
[00:29:04 WARN]:        at de.yanjulang.xxx.XXXXX.initialize(XXXXX.java:36)
[00:29:04 WARN]:        at de.yanjulang.xxx.plugin.Plugin.onLoad(Plugin.java:19)
[00:29:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298)
[00:29:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:767)
[00:29:04 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:556)
[00:29:04 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[00:29:04 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
[00:29:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[00:29:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629)
[00:29:04 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416)
[00:29:04 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379)
[00:29:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[00:29:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[00:29:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Izibane** [comment]
Can you send your onLoad, onEnable and onDisable methods?

**Comment by yanjulang** [comment]
![grafik](https://user-images.githubusercontent.com/29413262/185595866-fce390db-7d00-431a-bf15-9dd920cc53d4.png)

![grafik](https://user-images.githubusercontent.com/29413262/185595999-89e8fa0d-c6d4-4ecb-a8b0-a4a16136e886.png)

**Comment by yanjulang** [comment]
these are called from another class and in that other class they're called by a plugin's onLoad/onEnable/onDisable methods

**Comment by MWHunter** [comment]
Still able to reproduce this error

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/ce484ecac53ec16806f88e827613335ea4755dbf
