### ISSUE TITLE
Unhandled exception when loggin in on server startup and relogging

### ISSUE THREAD

**Issue by ThomasOM** [retrooper/packetevents#493]
**Describe the bug**
When logging in on server startup, SimplePacketListenerAbstract#onLoginSend does not get called for the login success packet.
After relogging, the next exception is thrown:

```
[14:24:28 WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.RuntimeException: The received string length is longer than maximum allowed (37 > 36)
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:382) ~[test.jar:?]
	at com.github.retrooper.packetevents.wrapper.login.server.WrapperLoginServerLoginSuccess.read(WrapperLoginServerLoginSuccess.java:57) ~[test.jar:?]
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:174) ~[test.jar:?]
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:119) ~[test.jar:?]
	at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:109) ~[test.jar:?]
	at com.github.retrooper.packetevents.wrapper.login.server.WrapperLoginServerLoginSuccess.<init>(WrapperLoginServerLoginSuccess.java:38) ~[test.jar:?]
	at com.github.retrooper.packetevents.manager.InternalPacketListener.onPacketSend(InternalPacketListener.java:58) ~[test.jar:?]
	at com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:48) ~[test.jar:?]
	at com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) [test.jar:?]
	at com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:41) [test.jar:?]
	at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:76) [test.jar:?]
	at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:90) [test.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:184) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:911) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:150) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:157) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.broadcast(CraftServer.java:1306) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.broadcastMessage(CraftServer.java:450) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:292) [patched_1.8.8.jar:git-PaperSpigot-445]
	at pledge.test.PacketEventsTest$1.onPacketLoginSend(PacketEventsTest.java:25) [test.jar:?]
	at com.github.retrooper.packetevents.event.SimplePacketListenerAbstract.onPacketSend(SimplePacketListenerAbstract.java:54) [test.jar:?]
	at com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:48) [test.jar:?]
	at com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) [test.jar:?]
	at com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:41) [test.jar:?]
	at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:76) [test.jar:?]
	at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:90) [test.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
```

**Software brand**
Paper 1.8.9, PacketEvents 2.0

**Plugins**
Only a simple test plugin to reproduce the bug consistently:

```java
public class PacketEventsTest extends JavaPlugin {
    @Override
    public void onEnable() {
        PacketEvents.setAPI(SpigotPacketEventsBuilder.build(this, new PacketEventsSettings().checkForUpdates(false)));
        PacketEvents.getAPI().load();
        PacketEvents.getAPI().init();

        PacketEvents.getAPI().getEventManager().registerListener(new SimplePacketListenerAbstract() {
            @Override
            public void onPacketLoginSend(PacketLoginSendEvent event) {
                if (event.getPacketType() == PacketType.Login.Server.LOGIN_SUCCESS) {
                    WrapperLoginServerLoginSuccess wrapper = new WrapperLoginServerLoginSuccess(event);
                    Bukkit.broadcastMessage("LOGIN: " + wrapper.getUserProfile().getName());
                }
            }
        });
    }
}
```

**How To Reproduce**
1. Join the server when starting up
2. Relog

**Expected behavior**
I expect SimplePacketListenerAbstract#onLoginSend to be called when logging in and not to throw an error when relogging.

**Additional context**
I can see that the player already has a PlayerConnection in the exception so they are definitely not in the LOGIN state anymore.

**Comment by ThomasOM** [comment]
Server logs for the login sequence:
```
[14:24:23 INFO]: Done (1.774s)! For help, type "help" or "?"
[14:24:23 INFO]: Timings Reset
[14:24:23 INFO]: Dualzz[/127.0.0.1:52616] logged in with entity id 264 at ([world]93.21481622387724, 63.0, 270.20704148724025)
[14:24:26 INFO]: UUID of player Dualzz is c8979886-3cb8-3c96-9882-46aec72a89d2
[14:24:26 INFO]: Dualzz lost connection: Disconnected
[14:24:26 INFO]: Dualzz left the game.
[14:24:28 INFO]: Dualzz[/127.0.0.1:52626] logged in with entity id 287 at ([world]93.21481622387724, 63.0, 270.20704148724025)
[14:24:28 WARN]: PacketEvents caught an unhandled exception while calling your listener.
```

**Comment by NoJokeFNA** [comment]
https://github.com/retrooper/packetevents/blob/2.0/api/src/main/java/com/github/retrooper/packetevents/wrapper/login/server/WrapperLoginServerLoginSuccess.java#L57
How can your UUID be longer than 36 characters?

**Comment by retrooper** [comment]
Yeah, somehow your UUID is longer than expected on a vanilla 1.8 server.

**Comment by ThomasOM** [comment]
I assume the wrapper is trying to read data from a different packet since the player already seems to already have a PlayerConnection, so it is definitely no longer in in the LOGIN state which the wrapper is made for...

I can assure you my UUID is not longer than 36 characters 😂

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/5df58a116d06f4022eba38635a640b1af56f5916
Thanks for pointing out the issue.
