### ISSUE TITLE
Packet Events unhandled exception.

### ISSUE THREAD

**Issue by SkyWaves123** [retrooper/packetevents#523]
**Describe the bug**
Theres an error that displays in my consola once 3-4 hours. Its an issue with the GrimAc anticheat but ive already contacted them and they said its a problem on your side. The thing is that i dont even know what Packet Events is. I dont even have the API installed.

**Software brand**
Paper 1.8.8 version 445

**Plugins**
Plugins (43): AsyncWorldEditInjector, killStats, PlaceholderAPI, PlugMan, spark, WeatherTimeLock, Votifier, PebbleAntiVPN, zVoteParty, AsyncWorldEdit, BlocksHub, KSpawn, SetHub, ViaVersion, PlugManX, ViaRewind, LuckPerms, WorldEdit, CrazyCrates, Scoreboard-revision, WorldGuard, ProtocolLib, SkinsRestorer, ChunkCollector, Vault, TokenManager, DecentHolograms, Essentials, BKCommonLib, GrimAC, AuthMe, Economy, LiteBans, AuctionHouse, TabList, ShopGUIPlus, Tokens, SuperiorSkyblock2, SuperiorFall, My_Worlds, WildStacker, WildTools, JetsMinions

**How To Reproduce**
I dont know how to reproduce this error. Just install Paper 1.8.8 and GrimAC and this will popup in the console i think.

**Expected behavior**
I expect to resolve the error.

**Screenshots**
Error: 
[01:46:54] [Netty Server IO #3/WARN]: PacketEvents caught an unhandled exception while calling your listener.
ac.grim.grimac.shaded.com.github.retrooper.packetevents.exception.PacketProcessException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.read(WrapperHandshakingClientHandshake.java:64) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:178) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:108) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:98) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.<init>(WrapperHandshakingClientHandshake.java:40) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.manager.InternalBukkitPacketListener.onPacketReceive(InternalBukkitPacketListener.java:21) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) [grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:43) [grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:51) [grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:58) [grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:35) [grimac-2.3.32%20(1).jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:570) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readByte(ByteBufOperatorModernImpl.java:74) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readByte(ByteBufHelper.java:67) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readByte(PacketWrapper.java:221) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readVarInt(PacketWrapper.java:253) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.read(WrapperHandshakingClientHandshake.java:57) ~[grimac-2.3.32%20(1).jar:?]
	... 31 more

**Additional context**
No additional context.

**Comment by SkyWaves123** [comment]
sorry but i dont understand how to fix this. what do i need to do exactly? Thank you for the response btw!

**Comment by MWHunter** [comment]
update packetevents

**Comment by SkyWaves123** [comment]
i dont know how to compile the plugin . btw ive updated grim anticheat and in the latest version packet events exceptions should be fixed but i still get the error

**Comment by MWHunter** [comment]
I'm not reopening this without a stack trace

**Comment by SkyWaves123** [comment]
Is the stack trace the logs right?

**Comment by MWHunter** [comment]
yes

**Comment by SkyWaves123** [comment]
29.01 17:54:37 [Server] [WARN] PacketEvents caught an unhandled exception while calling your listener.
29.01 17:54:37 [Server] [INFO] ac.grim.grimac.shaded.com.github.retrooper.packetevents.exception.PacketProcessException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 256)
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.read(WrapperHandshakingClientHandshake.java:64) ~[grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:178) ~[grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:108) ~[grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:98) ~[grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.<init>(WrapperHandshakingClientHandshake.java:40) ~[grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.io.github.retrooper.packetevents.manager.InternalBukkitPacketListener.onPacketReceive(InternalBukkitPacketListener.java:21) ~[grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) [grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:43) [grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:51) [grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:58) [grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:35) [grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) [?:?]
29.01 17:54:37 [Server] [INFO] Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 256)
29.01 17:54:37 [Server] [INFO] at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:570) ~[patched_1.8.8.jar:git-PaperSpigot-445]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readByte(ByteBufOperatorModernImpl.java:74) ~[grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readByte(ByteBufHelper.java:67) ~[grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readByte(PacketWrapper.java:221) ~[grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readVarInt(PacketWrapper.java:253) ~[grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.read(WrapperHandshakingClientHandshake.java:57) ~[grimac-2.3.35.jar:?]
29.01 17:54:37 [Server] [INFO] ... 31 more

This happenes every 2 hours.

**Comment by MWHunter** [comment]
should be fixed by https://github.com/retrooper/packetevents/commit/51ebbb7914d439538603ad94bffdc74a9cfc0009

**Comment by SkyWaves123** [comment]
can you compile it for me please ? i have no ideea how to do that

**Comment by SkyWaves123** [comment]
> should be fixed by [51ebbb7](https://github.com/retrooper/packetevents/commit/51ebbb7914d439538603ad94bffdc74a9cfc0009)

Can I replace the integrated packetevents from the plugin? If so can you tell me where is the file located?
