### ISSUE TITLE
Missing entering play state

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#532]
No clue how to reproduce

[01:37:36 WARN]: io.netty.handler.codec.EncoderException: com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 23 to a PacketType constant. Bound: CLIENT, Connection state: STATUS, Server version: 1.19.3
[01:37:36 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[01:37:36 WARN]:        at AntiPopup-5.3.jar//com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:130)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[01:37:36 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[01:37:36 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[01:37:36 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[01:37:36 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.lambda$writeAndFlush$1(NettyChannelProxy.java:223)
[01:37:36 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.lambda$processPacketOutbound$2(NettyChannelProxy.java:266)
[01:37:36 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.processPacketOutbound(NettyChannelProxy.java:268)
[01:37:36 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:223)
[01:37:36 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[01:37:36 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket()
[01:37:36 WARN]:        at net.minecraft.network.NetworkManager.sendPacket()
[01:37:36 WARN]:        at net.minecraft.network.NetworkManager.a()
[01:37:36 WARN]:        at net.minecraft.network.NetworkManager.exceptionCaught()
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[01:37:36 WARN]:        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:92)
[01:37:36 WARN]:        at AntiPopup-5.3.jar//com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.exceptionCaught(PacketEventsEncoder.java:153)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[01:37:36 WARN]:        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:92)
[01:37:36 WARN]:        at ViaVersion-4.5.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.exceptionCaught(BukkitEncodeHandler.java:112)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[01:37:36 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
[01:37:36 WARN]:        at AntiPopup-5.3.jar//com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.exceptionCaught(PacketEventsDecoder.java:64)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[01:37:36 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
[01:37:36 WARN]:        at ViaVersion-4.5.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.exceptionCaught(BukkitDecodeHandler.java:69)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[01:37:36 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.exceptionCaught(FlushConsolidationHandler.java:159)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[01:37:36 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[01:37:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[01:37:36 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
[01:37:36 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.handleReadException(AbstractEpollStreamChannel.java:728)
[01:37:36 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:826)
[01:37:36 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[01:37:36 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[01:37:36 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[01:37:36 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:37:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:37:36 WARN]: Caused by: com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 23 to a PacketType constant. Bound: CLIENT, Connection state: STATUS, Server version: 1.19.3
[01:37:36 WARN]:        at AntiPopup-5.3.jar//com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.event.ProtocolPacketEvent.<init>(ProtocolPacketEvent.java:82)
[01:37:36 WARN]:        at AntiPopup-5.3.jar//com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.event.PacketSendEvent.<init>(PacketSendEvent.java:37)
[01:37:36 WARN]:        at AntiPopup-5.3.jar//com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.event.simple.PacketStatusSendEvent.<init>(PacketStatusSendEvent.java:32)
[01:37:36 WARN]:        at AntiPopup-5.3.jar//com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.EventCreationUtil.createSendEvent(EventCreationUtil.java:50)
[01:37:36 WARN]:        at AntiPopup-5.3.jar//com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:84)
[01:37:36 WARN]:        at AntiPopup-5.3.jar//com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:66)
[01:37:36 WARN]:        at AntiPopup-5.3.jar//com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:45)
[01:37:36 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[01:37:36 WARN]:        ... 64 more

**Comment by MWHunter** [comment]
still an issue

**Comment by MWHunter** [comment]
It's literally always packet 23.  What is going on???

**Comment by MWHunter** [comment]
https://github.com/retrooper/packetevents/commit/0c4709ac575e8f206ad8d448de65119ea4bc83a1
