### ISSUE TITLE
LivingEntityDataProvider decode exception

### ISSUE THREAD

**Issue by jtJava** [retrooper/packetevents#548]
**Describe the bug**
The following exception occurs when breaking a block.

java.lang.ClassCastException: class us.strafe.ffa.packetevents.api.packetevents.protocol.item.ItemStack cannot be cast to class java.lang.Byte (us.strafe.ffa.packetevents.api.packetevents.protocol.item.ItemStack is in unnamed module of loader 'ModernFFA-1.0-SNAPSHOT.jar' @252f14ba; java.lang.Byte is in module java.base of loader 'bootstrap')
        at us.strafe.ffa.packetevents.api.packetevents.protocol.entity.data.provider.LivingEntityDataProvider.decode(LivingEntityDataProvider.java:154) ~[ModernFFA-1.0-SNAPSHOT.jar:?]
        at us.strafe.ffa.packetevents.api.packetevents.protocol.entity.data.provider.PlayerDataProvider.decode(PlayerDataProvider.java:103) ~[ModernFFA-1.0-SNAPSHOT.jar:?]
        at us.strafe.ffa.packet.ghost.GhostMetaTracker.onPacketPlaySend(GhostMetaTracker.java:69) ~[ModernFFA-1.0-SNAPSHOT.jar:?]
        at us.strafe.ffa.packetevents.api.packetevents.event.SimplePacketListenerAbstract.onPacketSend(SimplePacketListenerAbstract.java:56) ~[ModernFFA-1.0-SNAPSHOT.jar:?]
        at us.strafe.ffa.packetevents.api.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[ModernFFA-1.0-SNAPSHOT.jar:?]
        at us.strafe.ffa.packetevents.api.packetevents.event.EventManager.callEvent(EventManager.java:54) ~[ModernFFA-1.0-SNAPSHOT.jar:?]
        at us.strafe.ffa.packetevents.spigot.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:86) ~[ModernFFA-1.0-SNAPSHOT.jar:?]
        at us.strafe.ffa.packetevents.spigot.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:66) ~[ModernFFA-1.0-SNAPSHOT.jar:?]
        at us.strafe.ffa.packetevents.spigot.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:45) ~[ModernFFA-1.0-SNAPSHOT.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at us.strafe.ffa.packetevents.spigot.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:130) ~[ModernFFA-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:459) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Software brand**
Paper 1.19.3

**Plugins**
ProtocolLib, Spark, PacketEvents shaded

**How To Reproduce**
`
        if (event.getPacketType() == PacketType.Play.Server.ENTITY_METADATA) {
            WrapperPlayServerEntityMetadata wrapper = new WrapperPlayServerEntityMetadata(event);
            if (event.getUser().getUUID() == this.entityIdMap.get(wrapper.getEntityId())) {
                return;
            }

            this.metaMap
                    .computeIfAbsent(event.getUser().getUUID(), uuid -> new TrackedMeta())
                    .setMetaData(wrapper.getEntityId(), wrapper.getEntityMetadata());

            PlayerDataProvider newMetaData = new PlayerDataProvider();
            newMetaData.decode(wrapper.getEntityMetadata());
            newMetaData.setInvisible(LockUtil.shouldApplyMeta(
                    Bukkit.getPlayer(event.getUser().getUUID()),
                    Bukkit.getPlayer(this.getByEntityId(wrapper.getEntityId())))
            );

            wrapper.setEntityMetadata(newMetaData.encode());
        }
    }`

**Expected behavior**
No exception

**Comment by MWHunter** [comment]
This class was written by retrooper to only support the latest version.  If you wish to use it on outdated versions - please maintain it yourself as I will not be doing so.  I see the class as out of scope to PacketEvents and candidate for deletion.

**Comment by jtJava** [comment]
> This class was written by retrooper to only support the latest version. If you wish to use it on outdated versions - please maintain it yourself as I will not be doing so. I see the class as out of scope to PacketEvents and candidate for deletion.

This was the latest version at the time of the issue... "1.19.3 Paper"

**Comment by MWHunter** [comment]
must have been written when 1.19.3 wasn't the latest then - still not maintaining this since I see it as out of scope.  I would much rather want a general way to track indexes than this so you can just set an index and version, and not have to change it based on versions.

**Comment by MWHunter** [comment]
Solved by deleting the unmaintained classes https://github.com/retrooper/packetevents/commit/a64978cb0a7607de1a9b8a523b838955bc948f5f
