### ISSUE TITLE
NPE Error with PacketWrapper and WrapperPlayerServerInfo

### ISSUE THREAD

**Issue by C0an** [retrooper/packetevents#581]
**Describe the bug**
Constantly getting an NPE error w/ PacketWrapper & WrapperPlayerServerPlayerInfo 
`[15:03:50 WARN]: [er Thread - 0] java.lang.NullPointerException
[15:03:50 WARN]: [er Thread - 0]        at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:135)
[15:03:50 WARN]: [er Thread - 0]        at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerPlayerInfo.<init>(WrapperPlayServerPlayerInfo.java:66)
[15:03:50 WARN]: [er Thread - 0]        at rip.protocol.plib.tablist.TablistSender.updateFakeName(TablistSender.java:89)
[15:03:50 WARN]: [er Thread - 0]        at rip.protocol.plib.tablist.Tablist.update(Tablist.java:95)
[15:03:50 WARN]: [er Thread - 0]        at rip.protocol.plib.tablist.TablistService.lambda$setup$1(TablistService.java:119)
[15:03:50 WARN]: [er Thread - 0]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[15:03:50 WARN]: [er Thread - 0]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[15:03:50 WARN]: [er Thread - 0]        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:03:50 WARN]: [er Thread - 0]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:03:50 WARN]: [er Thread - 0]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:03:50 WARN]: [er Thread - 0]        at java.lang.Thread.run(Thread.java:750)
`

**Software brand**
ImanitySpigot 1.8.8-R0.1-Snapshot (Modified Paper)

**Plugins**
![image](https://github.com/retrooper/packetevents/assets/43456714/47c67109-3673-4cdf-a8f4-2db936b925dd)

**Code**
![image](https://github.com/retrooper/packetevents/assets/43456714/880b3865-99a9-4b3c-827a-2c7e0df31d03)

I've checked and all the variables being used are not null, it just fails to create the profile.

**Comment by MWHunter** [comment]
My guess is that WrapperPlayServerPlayerInfo is not a valid packet on 1.8

**Comment by C0an** [comment]
> My guess is that WrapperPlayServerPlayerInfo is not a valid packet on 1.8

rip.
