### ISSUE TITLE
WrapperPlayClientChatMessage netty exception for 1.19.3+ clients

### ISSUE THREAD

**Issue by jtJava** [retrooper/packetevents#586]
**Describe the bug**
On a 1.19.3 server, if any 1.19.3+ client sends a message, they will be kicked from the server with a netty exception. 
Any client under 1.19.3 connecting using ViaBackwards can send messages just fine. For the purposes of this issue, I tested with no plugins as well.

I also tested by modifying the "read" method inside of PacketEvents to see if that was the issue. My code is below:
``` 
    @Override
    public void read() {
        int maxMessageLength = serverVersion.isNewerThanOrEquals(ServerVersion.V_1_11) ? 256 : 100;
        this.message = readString(maxMessageLength);
        Instant timestamp = readTimestamp();
        SaltSignature saltSignature = readSaltSignature();
        this.messageSignData = new MessageSignData(saltSignature, timestamp);
        this.lastSeenMessages = readLastSeenMessagesUpdate();
        System.out.println("read finished");
    }
```
The final debug message would print, but the player would still be kicked from the server due to a netty exception.

**Software brand**
1.19.3 Paper latest

**Plugins**
Simple plugin wrapping WrapperPlayClientChatMessage

**How To Reproduce**
1. Join a 1.19.3 server with a 1.19.3+ client
2. Send "hello"
3. Profit

**Expected behavior**
No exception.

**Screenshots**

**Additional context**
When typing "hello" into chat, the following appears
[15:51:53 WARN]: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(24) + length(256) exceeds writerIndex(30): PooledUnsafeDirectByteBuf(ridx: 24, widx: 30, cap: 284)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:489)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:51:53 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:51:53 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:51:53 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
[15:51:53 WARN]:        at ModernFFA-1.0-SNAPSHOT.jar//us.strafe.ffa.packet.nms.ChatBypassHandler.channelRead(ChatBypassHandler.java:22)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:51:53 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:51:53 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:51:53 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:51:53 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:51:53 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[15:51:53 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[15:51:53 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[15:51:53 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[15:51:53 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:51:53 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:51:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:51:53 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(24) + length(256) exceeds writerIndex(30): PooledUnsafeDirectByteBuf(ridx: 24, widx: 30, cap: 284)
[15:51:53 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[15:51:53 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
[15:51:53 WARN]:        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:895)
[15:51:53 WARN]:        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:903)
[15:51:53 WARN]:        at net.minecraft.network.FriendlyByteBuf.readBytes(FriendlyByteBuf.java:1326)
[15:51:53 WARN]:        at net.minecraft.network.chat.MessageSignature.read(MessageSignature.java:25)
[15:51:53 WARN]:        at net.minecraft.network.FriendlyByteBuf.readNullable(FriendlyByteBuf.java:318)
[15:51:53 WARN]:        at net.minecraft.network.protocol.game.ServerboundChatPacket.<init>(ServerboundChatPacket.java:12)
[15:51:53 WARN]:        at net.minecraft.network.ConnectionProtocol$PacketSet.createPacket(ConnectionProtocol.java:305)
[15:51:53 WARN]:        at net.minecraft.network.ConnectionProtocol.createPacket(ConnectionProtocol.java:238)
[15:51:53 WARN]:        at net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:27)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
[15:51:53 WARN]:        ... 49 more
[15:51:53 WARN]: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 122
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:489)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:416)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:383)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:366)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:401)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:366)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:401)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:366)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[15:51:53 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
[15:51:53 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[15:51:53 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[15:51:53 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
[15:51:53 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
[15:51:53 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[15:51:53 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[15:51:53 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[15:51:53 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[15:51:53 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:51:53 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:51:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:51:53 WARN]: Caused by: java.io.IOException: Bad packet id 122
[15:51:53 WARN]:        at net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:29)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
[15:51:53 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
[15:51:53 WARN]:        ... 33 more

**Comment by wordandahalf** [comment]
Are you using the 2.0 branch? I'm also skeptical of the current implementation how the packet is read. However, the altered read method you provided is also not correct. According to [current protocol documentation](https://wiki.vg/Protocol#Chat_Message), there isn't any data related to previously sent messages sent anymore (that was just for 1.19.1-1.19.2).

I've quickly re-written the read method closely following the protocol spec., you can find it [here](https://gist.github.com/wordandahalf/2b891095ac50b37af87b37ab6dc6ec17). I haven't tested it extensively, but I know it works with 1.19.3.

**Comment by jtJava** [comment]
I just removed all the versioning stuff, otherwise I copied it how it is normally. I don't know kotlin but I'll try converting your code to Java and see how it works.

**Comment by jtJava** [comment]
```
    @Override
    public void read() {
        int maxMessageLength = serverVersion.isNewerThanOrEquals(ServerVersion.V_1_11) ? 256 : 100;
        this.message = readString(maxMessageLength);
        if (serverVersion.isNewerThanOrEquals(ServerVersion.V_1_19)) {
            Instant timestamp = readTimestamp();
            long salt = readLong();

            if (serverVersion.isNewerThanOrEquals(ServerVersion.V_1_19_3)) {
                boolean hasSignature = readBoolean();
                byte[] signature = null;
                if (hasSignature) {
                    signature = readBytes(256);
                }

                int messageCount = readVarInt();
                BitSet acknowledged = readBitSet();

                if (hasSignature) {
                    this.messageSignData = new MessageSignData(new SaltSignature(salt, signature), timestamp);
                }
                this.lastSeenMessages = new LastSeenMessages.Update(messageCount, acknowledged);
            } else {
                boolean signedPreview = readBoolean();
                this.messageSignData.setSignedPreview(signedPreview);

                if (serverVersion.isNewerThanOrEquals(ServerVersion.V_1_19_1)) {
                    this.legacyLastSeenMessages = readLegacyLastSeenMessagesUpdate();
                }
            }
        }
    }
    ```

[16:31:37 INFO]: Iowa lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/5 (PacketPlayInChat) was larger than I expected, found 1 bytes extra whilst reading packet 5
[16:31:37 WARN]: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(285) + length(1) exceeds writerIndex(285): PooledUnsafeDirectByteBuf(ridx: 285, widx: 285, cap: 320)
[16:31:37 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499)
[16:31:37 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:426)
[16:31:37 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:393)
[16:31:37 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
[16:31:37 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411)
[16:31:37 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
[16:31:37 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411)
[16:31:37 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
[16:31:37 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
[16:31:37 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
[16:31:37 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
[16:31:37 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
[16:31:37 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
[16:31:37 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[16:31:37 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[16:31:37 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[16:31:37 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[16:31:37 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:31:37 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:31:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:31:37 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(285) + length(1) exceeds writerIndex(285): PooledUnsafeDirectByteBuf(ridx: 285, widx: 285, cap: 320)
[16:31:37 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[16:31:37 WARN]:        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[16:31:37 WARN]:        at net.minecraft.network.FriendlyByteBuf.readByte(FriendlyByteBuf.java:1226)
[16:31:37 WARN]:        at net.minecraft.network.FriendlyByteBuf.readVarInt(FriendlyByteBuf.java:531)
[16:31:37 WARN]:        at net.minecraft.network.protocol.game.ServerboundAcceptTeleportationPacket.<init>(ServerboundAcceptTeleportationPacket.java:14)
[16:31:37 WARN]:        at net.minecraft.network.ConnectionProtocol$PacketSet.createPacket(ConnectionProtocol.java:305)
[16:31:37 WARN]:        at net.minecraft.network.ConnectionProtocol.createPacket(ConnectionProtocol.java:238)
[16:31:37 WARN]:        at net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:27)
[16:31:37 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
[16:31:37 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
[16:31:37 WARN]:        ... 33 more
[16:31:37 INFO]: Iowa left the game

**Comment by wordandahalf** [comment]
Can you show the code in your plugin? I've tested my re-written `read` implementation and it works with all versions.

**Comment by jtJava** [comment]
![image](https://github.com/retrooper/packetevents/assets/37258614/307a0023-da95-4ad2-afa5-ccaf9e7b67aa)

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/cdb48e0ab626c09ac3ac7827528fc0d5ce10323c
