### ISSUE TITLE
NPE on channel initzialization 

### ISSUE THREAD

**Issue by Nononitas** [retrooper/packetevents#602]
**Describe the bug**
NPE on channel initialization 
Basically same issue as #515 but on bungeecord

**Software brand**
Waterfall 805 (1.20)
MC-Server: Paper 1.20.1 98
PacketEvents: bungeecord-2.0.0-20230715.171621-223.jar

**Plugins**
None

**How To Reproduce**

1. Shade specified PacketEvents version into plugin
2. Start proxy
3. Attempt to connect to server (incl. ping)

**Exception**
``` 
[io.netty.channel.ChannelInitializer]: Failed to initialize a channel. Closing: [id: 0x48ed5897, L:/:25567 - R:/:61000]
java.lang.NullPointerException: Cannot assign field "user" because "decoder" is null
        at io.github.retrooper.packetevents.injector.BungeePipelineInjector.updateUser(BungeePipelineInjector.java:125) ~[?:?]
        at com.github.retrooper.packetevents.manager.protocol.ProtocolManager.setUser(ProtocolManager.java:158) ~[?:?]
        at io.github.retrooper.packetevents.injector.ServerConnectionInitializer.initChannel(ServerConnectionInitializer.java:49) ~[?:?]
        at io.github.retrooper.packetevents.injector.PreChannelInitializer.channelRegistered(PreChannelInitializer.java:34) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:176) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:152) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:145) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1383) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:172) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:152) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:815) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:517) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at java.lang.Thread.run(Thread.java:833) [?:?]```

**Comment by retrooper** [comment]
Fixed in https://github.com/retrooper/packetevents/commit/23d06075dda03e64d7a6a022111581d1b3506b25
Although actually sending packets on proxy is not supported yet. It's something I'll be working on, it's not an easy feature to implement since every user can have a different client version, forcing us to make our code-base more dynamic.
