### ISSUE TITLE
Errors/Warns when logging in

### ISSUE THREAD

**Issue by Manered** [retrooper/packetevents#616]
**Describe the bug**
It doesn't seem to impact anything but just spits out errors whenever a player joins.

**Software brand**
Paper 1.20.2

**Plugins**
![image](https://github.com/retrooper/packetevents/assets/133597204/2769a9d1-90c8-4413-b762-ebd09b90ddce)
WorldGuard, ViaVersion, ViaBackwards, VelocityKits (custom), TAB, SpeedyDuels (custom), SpeedyCrystals (uses PacketEvents API) (custom), Spark, Skript-Reflect, Skript-Placeholders, Skript, SkBee, PlaceholderAPI, packetevents-spigot (2.0.2), Multiverse Inventories, Multiverse Core, LuckPerms-Bukkit, LPC, FAWE (FastAsyncWorldEdit), Citizens (2.0.33), Chunky

**How To Reproduce**
*Example:*
1. Join with the 1.19.4 fabric minecraft client.
2. See error

**Expected behavior**
No errors/warns to be shown whenever a player joins

**Screenshots**
None

**Additional context**
Error:
```java
[10:03:30 INFO]: UUID of player Manere_ is 4ad4c78c-d4a4-4d25-91cf-4f001efc46c0
[10:03:30 INFO]: Manere_[/BLURRED IP] logged in with entity id 254 at ([hub]16.5, 66.0, 4.5)
[10:03:30 WARN]: io.netty.handler.codec.EncoderException: com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 111 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.20.1
[10:03:30 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[10:03:30 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[10:03:30 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:943)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[10:03:30 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[10:03:30 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[10:03:30 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[10:03:30 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[10:03:30 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[10:03:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[10:03:30 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[10:03:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[10:03:30 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[10:03:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[10:03:30 WARN]: Caused by: com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 111 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.20.1
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//com.github.retrooper.packetevents.event.ProtocolPacketEvent.<init>(ProtocolPacketEvent.java:88)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//com.github.retrooper.packetevents.event.PacketSendEvent.<init>(PacketSendEvent.java:37)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//com.github.retrooper.packetevents.event.simple.PacketPlaySendEvent.<init>(PacketPlaySendEvent.java:33)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//com.github.retrooper.packetevents.util.EventCreationUtil.createSendEvent(EventCreationUtil.java:53)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:42)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46)
[10:03:30 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[10:03:30 WARN]:        ... 30 more
[10:03:30 WARN]: io.netty.handler.codec.EncoderException: com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 111 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.20.1
[10:03:30 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[10:03:30 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[10:03:30 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:943)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[10:03:30 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[10:03:30 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[10:03:30 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[10:03:30 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[10:03:30 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[10:03:30 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[10:03:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[10:03:30 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[10:03:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[10:03:30 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[10:03:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[10:03:30 WARN]: Caused by: com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 111 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.20.1
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//com.github.retrooper.packetevents.event.ProtocolPacketEvent.<init>(ProtocolPacketEvent.java:88)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//com.github.retrooper.packetevents.event.PacketSendEvent.<init>(PacketSendEvent.java:37)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//com.github.retrooper.packetevents.event.simple.PacketPlaySendEvent.<init>(PacketPlaySendEvent.java:33)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//com.github.retrooper.packetevents.util.EventCreationUtil.createSendEvent(EventCreationUtil.java:53)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:42)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67)
[10:03:30 WARN]:        at packetevents-spigot-2.0.2.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46)
[10:03:30 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[10:03:30 WARN]:        ... 30 more
```

**Comment by Manered** [comment]
fixed it. issue that i'm using 1.19.4 of one of my custom plugins, had to update to 1.20.2
