### ISSUE TITLE
Plugin  loading bug

### ISSUE THREAD

**Issue by Nerd10000** [retrooper/packetevents#650]
**Describe the bug**
`15:59:03 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'Frost-AC-1.0.0.jar' in folder 'plugins'
java.lang.NoClassDefFoundError: com/github/retrooper/packetevents/event/PacketListenerCommon
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.lang.Class.forName(Class.java:513) ~[?:?]
        at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:51) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:29) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:169) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:139) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:524) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.github.retrooper.packetevents.event.PacketListenerCommon
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 15 more`

**Software brand**
I use pupur 1.20.1

**Plugins**
`[15:59:20 INFO]: Paper Plugins: (1):
[15:59:20 INFO]:  - Frost-AC
[15:59:20 INFO]: Bukkit Plugins: (10):
[15:59:20 INFO]:  - Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, packetevents, ProtocolLib, spark, Vault, ViaBackwards, ViaVersion
>`

**How To Reproduce**

`package me.dragon.frostac;

import com.github.retrooper.packetevents.PacketEvents;
import com.github.retrooper.packetevents.event.PacketEvent;
import com.github.retrooper.packetevents.event.PacketListener;
import com.github.retrooper.packetevents.event.PacketListenerPriority;
import io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder;
import me.dragon.frostac.checks.FlyHack;
import org.bukkit.plugin.Plugin;
import org.bukkit.plugin.java.JavaPlugin;

public final class Frost_AC extends JavaPlugin {

    private static Plugin plugin;

    @Override
    public void onLoad() {
        PacketEvents.setAPI(SpigotPacketEventsBuilder.build(this));

        PacketEvents.getAPI().getSettings().reEncodeByDefault(false)
                .bStats(false)
                .checkForUpdates(false);

        PacketEvents.getAPI().load();
    }

    @Override
    public void onEnable() {
        // Plugin startup logic
        plugin = this;

        PacketEvents.getAPI().getEventManager().registerListener(new FlyHack());
        PacketEvents.getAPI().init();

    }

    @Override
    public void onDisable() {
        // Plugin shutdown logic

        PacketEvents.getAPI().terminate();
    }

    public static Plugin getPlugin() {
        return plugin;
    }
}
`

`package me.dragon.frostac.checks;

import com.github.retrooper.packetevents.event.*;
import com.github.retrooper.packetevents.protocol.packettype.PacketType;
import com.github.retrooper.packetevents.protocol.player.User;
import me.dragon.frostac.util.FlagingSystem;
import me.dragon.frostac.util.checks.CheckTypes;
import me.dragon.frostac.util.checks.FlagTypes;
import org.bukkit.entity.Player;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class FlyHack  extends PacketListenerAbstract implements PacketListener {

    private static  FlagingSystem flagingSystem;

    private  static  final ExecutorService EXECUTOR_SERVICE = Executors.newSingleThreadExecutor();

    public FlyHack() {
        super (PacketListenerPriority.LOW);
    }

    @Override
    public void onPacketReceive(PacketReceiveEvent event) {

        Player player = (Player) event.getPlayer();

        if (event.getPacketType() == PacketType.Play.Client.PLAYER_FLYING && !player.isFlying()){
            flagingSystem.flag(player, CheckTypes.Movement, FlagTypes.FlyHack," ");

        }

    }

}
`

**Expected behavior**
Load the plugin 

**Screenshots**

**Additional context**

**Comment by wordandahalf** [comment]
You need to either shade PacketEvents into your plugin, or add it to your server.

**Comment by Nerd10000** [comment]
Okay thanks.I will try it.

**Comment by retrooper** [comment]
The solution has already been mentioned, for further help please join our discord.
