### ISSUE TITLE
Incompatibility with no CB relocation

### ISSUE THREAD

**Issue by vytskalt** [retrooper/packetevents#678]
**Describe the bug**
PaperMC is planning on removing the server version from the craftbukkit package in the future. They have published experimental server jars for testing. PacketEvents crashes when running on them.
See: https://forums.papermc.io/threads/paper-velocity-1-20-4.998/#post-2955

**Software brand**
https://github.com/PaperMC/testing/releases/tag/no-relocation

**Plugins**
PacketEvents 2.2.1

**How To Reproduce**
Start the server
```
[20:11:43 ERROR]: [packetevents] Error initializing plugin 'packetevents-spigot-2.2.1.jar' in folder 'plugins/.paper-remapped' (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:104) ~[packetevents-spigot-2.2.1.jar:?]
	at io.github.retrooper.packetevents.PacketEventsPlugin.onLoad(PacketEventsPlugin.java:32) ~[packetevents-spigot-2.2.1.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.4.jar:git-Paper-"e52cfa1"]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.4.jar:git-Paper-"e52cfa1"]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.4.jar:git-Paper-"e52cfa1"]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-"e52cfa1"]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:507) ~[paper-1.20.4.jar:git-Paper-"e52cfa1"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-"e52cfa1"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1133) ~[paper-1.20.4.jar:git-Paper-"e52cfa1"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-"e52cfa1"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at io.github.retrooper.packetevents.util.SpigotReflectionUtil.<clinit>(SpigotReflectionUtil.java:54) ~[packetevents-spigot-2.2.1.jar:?]
```

**Comment by retrooper** [comment]
Fixed in https://github.com/retrooper/packetevents/commit/651de583b6676b75dab626267d2aebc3fd597c91
