### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by LIWKK** [retrooper/packetevents#681]
**Describe the bug**
Error comes on join

**Software brand**
Please let us know what software you are using.
kSpigot 1.12.2

**Plugins**
Please give us a list of your plugins. Sometimes we run into incompatibilities. Having an overview of the plugins on your server can really help identify the problem quicker.
Eg. ViaVersion, ProtocolLib, HolographicDisplays
You may also provide a screenshot. 
https://gyazo.com/2007ce9adedd6ac893025b495aef70ee

**How To Reproduce**
*Example:*
1. Join with the 1.12.2 vanilla minecraft client.
2. See error

**Additional context**

[21:54:29 WARN]: Exception in thread "karhu-user-thread-0" java.lang.IndexOutOfBoundsException: readerIndex(47) + length(2) exceeds writerIndex(47): UnpooledDuplicatedByteBuf(ridx: 47, widx: 47, cap: 256, unwrapped: PooledUnsafeDirectByteBuf(ridx: 46, widx: 46, cap: 256))
[21:54:29 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405)
[21:54:29 WARN]:        at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:726)
[21:54:29 WARN]:        at io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readShort(ByteBufOperatorModernImpl.java:79)
[21:54:29 WARN]:        at com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readShort(ByteBufHelper.java:95)
[21:54:29 WARN]:        at com.github.retrooper.packetevents.wrapper.PacketWrapper.readShort(PacketWrapper.java:577)
[21:54:29 WARN]:        at com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:408)
[21:54:29 WARN]:        at com.github.retrooper.packetevents.wrapper.PacketWrapper.readEntityMetadata(PacketWrapper.java:796)
[21:54:29 WARN]:        at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityMetadata.read(WrapperPlayServerEntityMetadata.java:52)
[21:54:29 WARN]:        at com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:233)
[21:54:29 WARN]:        at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:143)
[21:54:29 WARN]:        at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:133)
[21:54:29 WARN]:        at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityMetadata.<init>(WrapperPlayServerEntityMetadata.java:36)
[21:54:29 WARN]:        at me.liwk.karhu.handler.global.TransactionHandler.handlePacketPlaySend(TransactionHandler.java:533)
[21:54:29 WARN]:        at me.liwk.karhu.handler.global.PacketProcessor.handlePacketPlaySend(PacketProcessor.java:1326)
[21:54:29 WARN]:        at me.liwk.karhu.handler.global.PacketProcessor.lambda$onPacketPlaySend$4(PacketProcessor.java:393)
[21:54:29 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[21:54:29 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[21:54:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by retrooper** [comment]
The only way I can envision this error occuring, is if PacketEvents fails to detect the server version.

**Comment by retrooper** [comment]
Which is very likely caused by their server software. Since there are no easily obtainable jars of such software, I can't look further into it.
