### ISSUE TITLE
block place 1.9 field not found

### ISSUE THREAD

**Issue by WizzardHub** [retrooper/packetevents#70]
[19:27:47 WARN]: io.github.retrooper.packetevents.exceptions.WrapperFieldNotFoundException: The class you are trying to read fields from does not contain any fields!
[19:27:47 WARN]:        at io.github.retrooper.packetevents.packetwrappers.WrappedPacket.readObject(WrappedPacket.java:450)
[19:27:47 WARN]:        at io.github.retrooper.packetevents.packetwrappers.in.blockplace.WrappedPacketInBlockPlace_1_9.getX(WrappedPacketInBlockPlace_1_9.java:49)
[19:27:47 WARN]:        at io.github.retrooper.packetevents.packetwrappers.in.blockplace.WrappedPacketInBlockPlace.getX(WrappedPacketInBlockPlace.java:61)
[19:27:47 WARN]:        at me.wizzard.anticheat.check.type.badpackets.BadPacketsS.handlePacket(BadPacketsS.java:20)
[19:27:47 WARN]:        at me.wizzard.anticheat.player.PlayerData.lambda$processPacket$11(PlayerData.java:338)
[19:27:47 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[19:27:47 WARN]:        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[19:27:47 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[19:27:47 WARN]:        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[19:27:47 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[19:27:47 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[19:27:47 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[19:27:47 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[19:27:47 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[19:27:47 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[19:27:47 WARN]:        at me.wizzard.anticheat.player.PlayerData.processPacket(PlayerData.java:338)
[19:27:47 WARN]:        at me.wizzard.anticheat.packet.PacketProcessor.onPacketReceive(PacketProcessor.java:18)
[19:27:47 WARN]:        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[19:27:47 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:27:47 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[19:27:47 WARN]:        at io.github.retrooper.packetevents.event.manager.EventManagerLegacy.callEvent(EventManagerLegacy.java:56)
[19:27:47 WARN]:        at io.github.retrooper.packetevents.event.manager.EventManager.callEvent(EventManager.java:37)
[19:27:47 WARN]:        at io.github.retrooper.packetevents.packetmanager.PacketManager.read(PacketManager.java:188)
[19:27:47 WARN]:        at io.github.retrooper.packetevents.packetmanager.tinyprotocol.TinyProtocol8.onPacketInAsync(TinyProtocol8.java:250)
[19:27:47 WARN]:        at io.github.retrooper.packetevents.packetmanager.tinyprotocol.TinyProtocol8$PacketInterceptor.channelRead(TinyProtocol8.java:522)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:27:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:27:47 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.lambda$sendRawPacketToServerServerSide$3(UserConnection.java:274)
[19:27:47 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.sendRawPacketToServerServerSide(UserConnection.java:280)
[19:27:47 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.sendRawPacketToServer(UserConnection.java:255)
[19:27:47 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.sendToServer(PacketWrapper.java:526)
[19:27:47 WARN]:        at de.gerrygames.viarewind.utils.PacketUtil.sendToServer(PacketUtil.java:19)
[19:27:47 WARN]:        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$15$3.handle(PlayerPackets.java:528)
[19:27:47 WARN]:        at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[19:27:47 WARN]:        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[19:27:47 WARN]:        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[19:27:47 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:454)
[19:27:47 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[19:27:47 WARN]:        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[19:27:47 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[19:27:47 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:395)
[19:27:47 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:38)
[19:27:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[19:27:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:27:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:27:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:27:47 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:27:47 WARN]:        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:27:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:27:47 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[19:27:47 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
[19:27:47 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
[19:27:47 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
[19:27:47 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
[19:27:47 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
[19:27:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[19:27:47 WARN]:        at java.lang.Thread.run(Unknown Source)

it happens when you click with a block in hand in air

**Comment by retrooper** [comment]
Use this commit: https://jitpack.io/#retrooper/packetevents/dev-59d25df76b-1

Before using the wrapper, use my util to determine if it really was a block place and not right click interaction that I added one commit ago.
```java
if(PacketType.Client.Util.isBlockPlace(event.getPacketId()) {
        WrappedPacketInBlockPlace bp = new WrappedPacketInBlockPlace(event.getNMSPacket());
}
```
