### ISSUE TITLE
class java.lang.String cannot be cast to class

### ISSUE THREAD

**Issue by scarfacered** [retrooper/packetevents#728]
Paper 1.20.6, Grim with latest packevents https://github.com/retrooper/packetevents/commit/be414fceb64ff5939220794a484bbcf2fbe84303
getFacing returns String now?

```
[12:01:37] [Netty Server IO #1/WARN]: java.lang.ClassCastException: class java.lang.String cannot be cast to class ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.BlockFace (java.lang.String is in module java.base of loader 'bootstrap'; ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.BlockFace is in unnamed module of loader 'Grim.jar' @43bd5c19)
[12:01:37] [Netty Server IO #1/WARN]: 	at Grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.states.WrappedBlockState.getFacing(WrappedBlockState.java:600)
[12:01:37] [Netty Server IO #1/WARN]: 	at Grim.jar//ac.grim.grimac.utils.collisions.blocks.TrapDoorHandler.fetch(TrapDoorHandler.java:18)
[12:01:37] [Netty Server IO #1/WARN]: 	at Grim.jar//ac.grim.grimac.utils.collisions.datatypes.DynamicCollisionBox.downCast(DynamicCollisionBox.java:49)
[12:01:37] [Netty Server IO #1/WARN]: 	at Grim.jar//ac.grim.grimac.utils.collisions.datatypes.SimpleCollisionBox.isIntersected(SimpleCollisionBox.java:200)
[12:01:37] [Netty Server IO #1/WARN]: 	at Grim.jar//ac.grim.grimac.predictionengine.PointThreeEstimator.handleChangeBlock(PointThreeEstimator.java:127)
[12:01:37] [Netty Server IO #1/WARN]: 	at Grim.jar//ac.grim.grimac.utils.latency.CompensatedWorld.updateBlock(CompensatedWorld.java:289)
[12:01:37] [Netty Server IO #1/WARN]: 	at Grim.jar//ac.grim.grimac.events.packets.worldreader.BasePacketWorldReader.lambda$handleMultiBlockChange$3(BasePacketWorldReader.java:174)
[12:01:37] [Netty Server IO #1/WARN]: 	at Grim.jar//ac.grim.grimac.utils.latency.LatencyUtils.handleNettySyncTransaction(LatencyUtils.java:44)
[12:01:37] [Netty Server IO #1/WARN]: 	at Grim.jar//ac.grim.grimac.player.GrimPlayer.addTransactionResponse(GrimPlayer.java:323)
[12:01:37] [Netty Server IO #1/WARN]: 	at Grim.jar//ac.grim.grimac.events.packets.PacketPingListener.onPacketReceive(PacketPingListener.java:62)
[12:01:37] [Netty Server IO #1/WARN]: 	at Grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45)
[12:01:37] [Netty Server IO #1/WARN]: 	at Grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52)
```

**Comment by AoElite** [comment]
@scarfacered 1.20.5+ support is being worked on.
