### ISSUE TITLE
[Bug] WrapperPlayServerEntityEquipment issue on 1.20.5/6

### ISSUE THREAD

**Issue by Bram1903** [retrooper/packetevents#741]
**Describe the bug**
When receiving and wrapping a `WrapperPlayServerEntityEquipment` packet an `IndexOutOfBoundsException` is being thrown.

**Software brand**
Paper 1.20.6

**Plugins**
ViaVersion, test plugin

**How To Reproduce**
1. Read Entity Equipment packets and wrap them into a `WrapperPlayServerEntityEquipment` wrapper. 
2. When an item is being enchanted or damaged an error is being thrown. 

**Expected behavior**
No errors ;-)

**Strack Trace**
```
[23:44:04 WARN]: [com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex: 83, writerIndex: 27 (expected: 0 <= readerIndex <= writerIndex <= capacity(256))
	at io.netty.buffer.AbstractByteBuf.checkIndexBounds(AbstractByteBuf.java:112) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:121) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readerIndex(ByteBufOperatorModernImpl.java:44) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readerIndex(ByteBufHelper.java:39) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:583) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:571) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAdventurePredicate$PropertyMatcher.read(ItemAdventurePredicate.java:177) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readCollection(PacketWrapper.java:1342) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readList(PacketWrapper.java:1355) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAdventurePredicate$BlockPredicate.read(ItemAdventurePredicate.java:107) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readCollection(PacketWrapper.java:1342) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readList(PacketWrapper.java:1355) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAdventurePredicate.read(ItemAdventurePredicate.java:44) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.protocol.component.ComponentTypes$1.read(ComponentTypes.java:79) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStackModern(PacketWrapper.java:425) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:444) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityEquipment.read(WrapperPlayServerEntityEquipment.java:59) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:243) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:148) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:138) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityEquipment.<init>(WrapperPlayServerEntityEquipment.java:37) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at spigot-2.0.1-all-1714858177841.jar/com.deathmotion.antihealthindicator.packetlisteners.spoofers.EntityEquipmentListener.onPacketSend(EntityEquipmentListener.java:85) ~[spigot-2.0.1-all-1714858177841.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:44) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection$2.write(Connection.java:748) ~[paper-1.20.6.jar:git-Paper-38]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:503) ~[paper-1.20.6.jar:git-Paper-38]
	at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:488) ~[paper-1.20.6.jar:git-Paper-38]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by booky10** [comment]
Can't reproduce this with placing a diamond chestplate with protection 1 and damage on an armor stand
`/give @s minecraft:diamond_chestplate[enchantments={levels:{"minecraft:protection":1}},damage=1]`

**Comment by Bram1903** [comment]
> Can't reproduce this with placing a diamond chestplate with protection 1 and damage on an armor stand
> 
> `/give @s minecraft:diamond_chestplate[enchantments={levels:{"minecraft:protection":1}},damage=1]`

I'll grab my MacBook rq, and I'll try and provide more details

**Comment by Bram1903** [comment]
> Can't reproduce this with placing a diamond chestplate with protection 1 and damage on an armor stand `/give @s minecraft:diamond_chestplate[enchantments={levels:{"minecraft:protection":1}},damage=1]`

When trying this with an armor stand it seems to be fine. It's when another player is wearing armor that is either damaged or enchanted when the error is being thrown.

Link to the location where I am receiving the error:
https://github.com/Bram1903/AntiHealthIndicator/blob/main/common/src/main/java/com/deathmotion/antihealthindicator/packetlisteners/spoofers/EntityEquipmentListener.java#L85
