### ISSUE TITLE
Conflict Issue

### ISSUE THREAD

**Issue by Buttercuq** [retrooper/packetevents#766]
**Describe the bug**
localhoste works on its own but not when transferred to the server

**Software brand**
PurPur 1.17.1-1.19.4

**Plugins**
Plugins (74): AdvanceParticle, AlphaChest, Announcer, AntiCaps,
 AntiCurse, AntiCheatAddition, AquaticCrates, BanItem, BetterProfiles, BroadcastPlus, Citizens, Cit
izensGUI, ClearLag, CommandForward, CommandNPC, DecentHolograms, DeluxeMenus, De
luxeWithdraw, DeluxeWithdrawVaultAddon, DisableVillagerTrade, DiscordSRV, Econom
yShopGUI-Premium, eGlow, Ersatz, Essentials, ExcellentCrates-5.0.0, GrimAC, GSit
, HeadDrops, iKoth, InventoryFullPlus, ItemEdit, ItemsAdder, LeaderOS, LocketteP
ro, LoneLibs, LPX, LuckPerms, ModelEngine, Multiverse-Core, MuteManager, MythicM
obs, NBTAPI, NexEngine, OreRegenerator, OrmanSistemi, Pl-Hide-Pro, PlaceholderAP
I, PlotSquared, ProtocolLib, PvPManager, ScreenEffects, Shopkeepers, SkBee, Skel
lett, SkinsRestorer, SkQuery, skRayFall, Skript, skUtilities, TAB-Bridge, TradeS
ystem, UltimateClans, Vault, Vegas, ViaVersion, VoidGen, Votifier, VotingPlugin,
 WebSender, WorldEdit, WorldGuard, Wraith, zAuctionHouseV3

**How To Reproduce**
*Example:*
1. I opened the server
2. Player Entered the Presenter
3. See error

**Error**
[04:00:24] [Netty Server IO #2/WARN]: [com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "<parameter1>" is null
	at de.photon.anticheataddition.user.User.getUser(User.java:100) ~[AntiCheatAddition-9.0.1.jar:?]
	at de.photon.anticheataddition.user.User.getUser(User.java:90) ~[AntiCheatAddition-9.0.1.jar:?]
	at de.photon.anticheataddition.util.protocol.PacketAdapterBuilder.runPacketReceiveEventBiConsumer(PacketAdapterBuilder.java:97) ~[AntiCheatAddition-9.0.1.jar:?]
	at de.photon.anticheataddition.util.protocol.PacketAdapterBuilder$2.onPacketReceive(PacketAdapterBuilder.java:135) ~[AntiCheatAddition-9.0.1.jar:?]
	at com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[packetevents-spigot-2.2.1.jar:?]
	at com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[packetevents-spigot-2.2.1.jar:?]
	at com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:82) ~[packetevents-spigot-2.2.1.jar:?]
	at io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:51) ~[packetevents-spigot-2.2.1.jar:?]
	at io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:58) ~[packetevents-spigot-2.2.1.jar:?]
	at io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:35) ~[packetevents-spigot-2.2.1.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Comment by Buttercuq** [comment]
When I put "AntiCheatAddition-9.0.1" without installing your plugin, it did not give a problem when the player entered, but when I put this plugin because it was mandatory, this problem appeared here

**Comment by retrooper** [comment]
Please contact the author of the plugin. This error seems to be a mistake on his end. You may request him to contact us via our Discord Server.
