### ISSUE TITLE
NullPointerException on CRAFT_PARTICLE_PARTICLES_FIELD

### ISSUE THREAD

**Issue by CubBossa** [retrooper/packetevents#773]
**Describe the bug**
`SpigotConversionUtil.toBukkitParticle(ParticleTypes.DUST)`
causes
```log
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "de.cubbossa.pathfinder.lib.packetevents.impl.util.SpigotReflectionUtil.CRAFT_PARTICLE_PARTICLES_FIELD" is null
                    at PathFinder-5.0.0.jar/de.cubbossa.pathfinder.lib.packetevents.impl.util.SpigotReflectionUtil.fromPacketEventsParticle(SpigotReflectionUtil.java:1088) ~[PathFinder-5.0.0.jar:?]
                    at PathFinder-5.0.0.jar/de.cubbossa.pathfinder.lib.packetevents.impl.util.SpigotConversionUtil.toBukkitParticle(SpigotConversionUtil.java:166) ~[PathFinder-5.0.0.jar:?]
                    at PathFinder-5.0.0.jar/de.cubbossa.pathfinder.editmode.renderer.ParticleEdgeRenderer.lambda$startTask$15(ParticleEdgeRenderer.java:208) ~[PathFinder-5.0.0.jar:?]
```

**Software brand**
Paper 1.20.6-64, last version of PacketEvents

**Plugins**
Only the issue causing. It has packetevents shaded

**How To Reproduce**
Run the code above

**Expected behavior**
No error

**Screenshots**

**Additional context**

**Comment by retrooper** [comment]
Fixed in https://github.com/retrooper/packetevents/commit/499d2eea6c4e717748a4731588b1d7b208432a5d
