### ISSUE TITLE
arraycopy: source index -256 out of bounds for byte[0]

### ISSUE THREAD

**Issue by adiantek** [retrooper/packetevents#784]
**Describe the bug**
1.8 doesn't have "unload chunk" packet

**Software brand**
PaperSpigot 1.8.8

**Plugins**
packetevents & listener

**How To Reproduce**
*Example:*
1. Join the server 1.8
2. Fly
3. If the server sends to player unload the chunk request, it will cause an exception

**Expected behavior**
No exception

**Screenshots**
```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: source index -256 out of bounds for byte[0]
        at java.base/java.util.Arrays.copyOfRange(Arrays.java:3823) ~[?:?]
        at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerChunkData.read(WrapperPlayServerChunkData.java:196) ~[packetevents-spigot-2.3.1-CUSTOM.jar:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:244) ~[packetevents-spigot-2.3.1-CUSTOM.jar:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:149) ~[packetevents-spigot-2.3.1-CUSTOM.jar:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:139) ~[packetevents-spigot-2.3.1-CUSTOM.jar:?]
        at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerChunkData.<init>(WrapperPlayServerChunkData.java:72) ~[packetevents-spigot-2.3.1-CUSTOM.jar:?]
```

**Additional context**
https://github.com/retrooper/packetevents/blob/2.0/api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerChunkData.java#L151
This line should be false if:
- version 1.8 AND
- `fullChunk` is true AND
- `chunkMask.isEmpty()` is true

**Comment by booky10** [comment]
The code seems to line up with what the server sends, I also can't seem to reproduce your issue

![image](https://github.com/retrooper/packetevents/assets/53302036/027caa5b-ff6a-4de1-859d-0c2e8a771a3f)

The server always writes the biome data (always length of 256) at the end of the packet, even when just unloading chunks

---

Are you sure you are using plain Paper 1.8.8?

**Comment by adiantek** [comment]
Sorry, I forgot to meant to enable `cache-chunk-maps` in paper.yml

**Comment by booky10** [comment]
![image](https://github.com/retrooper/packetevents/assets/53302036/7cdd855f-4ea8-4e2f-b65d-68f6eb5e96da)

:+1: seems like a simple fix then

**Comment by adiantek** [comment]
Yep, if you modify paper special for packet events. But I think it should be more universal and packet events should accept empty data for 1.8 with full chunk true (which means unload chunk)
