### ISSUE TITLE
doesn't work on paper 1.20.6 without remapping

### ISSUE THREAD

**Issue by IssueDescription** [retrooper/packetevents#793]
**Describe the bug**
If you have remapping disabled on paper, packetevents doesnt work, because packet events is still using spigot obfuscated nms calls, there should be support for mojang mapped, which is what paper is using now since 1.20.5

```
[14:32:21 INFO]: [packetevents] Enabling packetevents v2.3.1
[14:32:21 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.<init>(net.minecraft.world.item.Item,int)
[14:32:21 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3761)
[14:32:21 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2442)
[14:32:21 WARN]:        at packetevents-spigot-latest.jar//io.github.retrooper.packetevents.util.SpigotReflectionUtil.initConstructors(SpigotReflectionUtil.java:134)
[14:32:21 WARN]:        at packetevents-spigot-latest.jar//io.github.retrooper.packetevents.util.SpigotReflectionUtil.init(SpigotReflectionUtil.java:392)
[14:32:21 WARN]:        at packetevents-spigot-latest.jar//io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:103)
[14:32:21 WARN]:        at packetevents-spigot-latest.jar//io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.init(SpigotPacketEventsBuilder.java:137)
[14:32:21 WARN]:        at packetevents-spigot-latest.jar//io.github.retrooper.packetevents.PacketEventsPlugin.onEnable(PacketEventsPlugin.java:47)
[14:32:21 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[14:32:21 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[14:32:21 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[14:32:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[14:32:21 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604)
[14:32:21 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553)
[14:32:21 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678)
[14:32:21 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[14:32:21 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323)
[14:32:21 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1139)
[14:32:21 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[14:32:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[14:32:21 ERROR]: Error occurred while enabling packetevents v2.3.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because the return value of "com.github.retrooper.packetevents.util.reflection.Reflection.getField(java.lang.Class, java.lang.Class, int)" is null
        at packetevents-spigot-latest.jar/io.github.retrooper.packetevents.util.SpigotReflectionUtil.getMinecraftServerConnectionInstance(SpigotReflectionUtil.java:438) ~[packetevents-spigot-latest.jar:?]
        at packetevents-spigot-latest.jar/io.github.retrooper.packetevents.injector.SpigotChannelInjector.isServerBound(SpigotChannelInjector.java:63) ~[packetevents-spigot-latest.jar:?]
        at packetevents-spigot-latest.jar/io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:115) ~[packetevents-spigot-latest.jar:?]
        at packetevents-spigot-latest.jar/io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.init(SpigotPacketEventsBuilder.java:137) ~[packetevents-spigot-latest.jar:?]
        at packetevents-spigot-latest.jar/io.github.retrooper.packetevents.PacketEventsPlugin.onEnable(PacketEventsPlugin.java:47) ~[packetevents-spigot-latest.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1139) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:32:21 INFO]: [packetevents] Disabling packetevents v2.3.1
```

**Software brand**
This server is running Paper version 1.20.6-DEV-master@9bf4855 (2024-05-21T12:41:52Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
Unknown version
Previous version: 1.20.6-86-9bf4855 (MC: 1.20.6)

**Plugins**
Just using packet events by itself

**How To Reproduce**
Load it on latest paper (with remapping disabled)
Issue is that paper since 1.20.5 doesn't use obfuscated nms anymore, its mojang mapping

**Expected behavior**
Should load

**Comment by SamB440** [comment]
There is already support for this, are you using packetevents with the library loading?

**Comment by SamB440** [comment]
Oh you said you had remapping disabled, didn't see that.

**Comment by booky10** [comment]
same issue as #764 but with the actual cause mentioned

**Comment by PukPukov** [comment]
Probably should work once and fork paper that breaks everything and decline all idiotic patches instead of constant work to make plugins run on this pile of crap after another breaking change.

**Comment by retrooper** [comment]
> Probably should work once and fork paper that breaks everything and decline all idiotic patches instead of constant work to make plugins run on this pile of crap after another breaking change.

Chill. 🚶

**Comment by PukPukov** [comment]
> > Probably should work once and fork paper that breaks everything and decline all idiotic patches instead of constant work to make plugins run on this pile of crap after another breaking change.
> 
> what does this even mean

1. Fork paper.
2. Delete patch that forcing remapping.

**Comment by PukPukov** [comment]
> There is a flag to disable force remapping `-Dpaper.disable-plugin-rewriting=true`
But there is no reobf jar anymore. This flag is basically "Dpaper.do-not-attempt-to-fix-what-we-broken=true".
