### ISSUE TITLE
Unable to use libraries that use Paper's instance of Adventure/MiniMessage

### ISSUE THREAD

**Issue by OakLoaf** [retrooper/packetevents#796]
**Describe the bug**
I have a chat message library that adds MiniMessage support to servers using Paper. It does this by depending on Paper's shaded instance of Adventure/MiniMessage. 

I am shading PacketEvents into my plugin and cannot work out how to relocate Adventure in a way that doesn't also relocate all imports of my library as currently it is.

**Software brand**
Paper 1.20.6

**How To Reproduce**
1. Depend on PacketEvents and a library that soft-depends on MiniMessage (eg. [ChatColorHandler](https://github.com/OakLoaf/ChatColorHandler/))
2. Use a player to audience cast (likely other castt issues too)
3. See error in console

**Additional context**
Here is an error that I was getting:
```
Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.entity.CraftPlayer cannot be cast to class org.lushplugins.followers.libraries.kyori.adventure.audience.Audience (org.bukkit.craftbukkit.entity.CraftPlayer is in unnamed module of loader java.net.URLClassLoader @192d3247; org.lushplugins.followers.libraries.kyori.adventure.audience.Audience is in unnamed module of loader 'Followers-2.0.0-BETA.jar' @6544218f)
    at Followers-2.0.0-BETA.jar/org.lushplugins.followers.libraries.lushlib.libraries.chatcolor.messengers.MiniMessageMessenger.sendMessage(MiniMessageMessenger.java:30) ~[Followers-2.0.0-BETA.jar:?]
    at Followers-2.0.0-BETA.jar/org.lushplugins.followers.libraries.lushlib.libraries.chatcolor.ChatColorHandler.sendMessage(ChatColorHandler.java:70) ~[Followers-2.0.0-BETA.jar:?]
    at Followers-2.0.0-BETA.jar/org.lushplugins.followers.commands.FollowerCmd$CreateCmd.execute(FollowerCmd.java:75) ~[Followers-2.0.0-BETA.jar:?]
    at Followers-2.0.0-BETA.jar/org.lushplugins.followers.libraries.lushlib.command.Command.onCommand(Command.java:55) ~[Followers-2.0.0-BETA.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
    ... 26 more
```

**Comment by AbhigyaKrishna** [comment]
This is an issue on your own end as you have relocated `Audiences` and not using native paper adventure. Not a issue of packetevents!

**Comment by AbhigyaKrishna** [comment]
If you want to use native paper adventure, you either have to exclude the classes where you are using it from your shadow plugin or not relocate the `kyori` library. You can't have both at a time. The wiki is for simple use case scenarios and not for something as complex as yours, so you have find a workaround according to your use case.

**Comment by OakLoaf** [comment]
Yeah that makes sense, do you happen to know about the `from` method in relocate? I'm wondering if that could be helpful to me. No worries if you don't have the time to help though, I understand that this isn't a PE issue.

**Comment by AbhigyaKrishna** [comment]
If you need help, we can continue this on discord as it seems irrelevant here.
