### ISSUE TITLE
NullPointerException on SpigotReflectionUtil.CRAFT_PLAYER_CLASS

### ISSUE THREAD

**Issue by CubBossa** [retrooper/packetevents#802]
**Describe the bug**
```log
[09:31:30] [ForkJoinPool.commonPool-worker-3/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.cast(Object)" because "de.cubbossa.pathfinder.lib.cliententities.lib.packetevents.impl.util.SpigotReflectionUtil.CRAFT_PLAYER_CLASS" is null
[09:31:30] [ForkJoinPool.commonPool-worker-3/WARN]: 	at PathFinder-5.1.0.jar//de.cubbossa.pathfinder.lib.cliententities.lib.packetevents.impl.util.SpigotReflectionUtil.getCraftPlayer(SpigotReflectionUtil.java:496)
[09:31:30] [ForkJoinPool.commonPool-worker-3/WARN]: 	at PathFinder-5.1.0.jar//de.cubbossa.pathfinder.lib.cliententities.lib.packetevents.impl.util.SpigotReflectionUtil.getEntityPlayer(SpigotReflectionUtil.java:500)
[09:31:30] [ForkJoinPool.commonPool-worker-3/WARN]: 	at PathFinder-5.1.0.jar//de.cubbossa.pathfinder.lib.cliententities.lib.packetevents.impl.util.SpigotReflectionUtil.getPlayerConnection(SpigotReflectionUtil.java:510)
[09:31:30] [ForkJoinPool.commonPool-worker-3/WARN]: 	at PathFinder-5.1.0.jar//de.cubbossa.pathfinder.lib.cliententities.lib.packetevents.impl.util.SpigotReflectionUtil.getNetworkManager(SpigotReflectionUtil.java:560)
[09:31:30] [ForkJoinPool.commonPool-worker-3/WARN]: 	at PathFinder-5.1.0.jar//de.cubbossa.pathfinder.lib.cliententities.lib.packetevents.impl.util.SpigotReflectionUtil.getChannel(SpigotReflectionUtil.java:584)
[09:31:30] [ForkJoinPool.commonPool-worker-3/WARN]: 	at PathFinder-5.1.0.jar//de.cubbossa.pathfinder.lib.cliententities.lib.packetevents.impl.manager.player.PlayerManagerImpl.getChannel(PlayerManagerImpl.java:77)
[09:31:30] [ForkJoinPool.commonPool-worker-3/WARN]: 	at PathFinder-5.1.0.jar//de.cubbossa.pathfinder.lib.cliententities.lib.packetevents.api.manager.player.PlayerManager.sendPacket(PlayerManager.java:45)
[09:31:30] [ForkJoinPool.commonPool-worker-3/WARN]: 	at PathFinder-5.1.0.jar//de.cubbossa.pathfinder.lib.cliententities.PlayerSpaceImpl.lambda$handleUpdateInfoList$14(PlayerSpaceImpl.java:291)
```

**Software brand**
Paper 1.20.4, packetevents 2.3.1-SNAPSHOT

**Plugins**
None but the one that causes the issue

**How To Reproduce**
Use `PlayerManager.sendPacket(Player, PacketWrapper)`

The line from the stack trace:
```Java
    var pm = PacketEvents.getAPI().getPlayerManager();
    for(Player player : players) {
      wrappers.forEach(p -> pm.sendPacket(player, p));
    }
```

**Comment by retrooper** [comment]
Show us your main class.

**Comment by CubBossa** [comment]
My Plugin main class? The API initialization happens [here](https://github.com/CubBossa/PathFinder/blob/main/pathfinder-editmode/src/main/java/de/cubbossa/pathfinder/editmode/RoadMapEditorExtension.java#L28)
And after initializing it in the startup phase of the server I use it [here](https://github.com/CubBossa/ClientEntities/blob/2f3b7003721a0ca3a781aa18aa312b6ffdce28b0/src/main/java/de/cubbossa/cliententities/PlayerSpaceImpl.java#L289)
If you were not able to reproduce I can try to make a minimal setup, I use packetevents a lot and am glad if we get it working on 1.20.6 soon

**Comment by CubBossa** [comment]
I cannot reproduce any longer, seems like recompiling against latest snapshot solved the issue or some weird things were going on. Thanks for taking your time! My plugins seem to work fine on 1.20.6 now
