### ISSUE TITLE
Cant join on spigot server 1.12.2 with Bungeecord

### ISSUE THREAD

**Issue by AyakaShizumy** [retrooper/packetevents#808]
**Describe the bug**
Error when trying to log into the server

**Software brand**
Spigot 1.12.2, Game project that runs on Bungecord 

**Plugins**
ViaVersion, ProtocolLib others are self-written. (Removing them does not help solve the problem)

**How To Reproduce**
1. Join with the 1.12.2 vanilla minecraft client.
2. Got error in console

**Expected behavior**
I'm not expecting anything, I was just trying to at least start the server with this plugin.

**Video**
https://youtu.be/rgKn196nj_M

**Additional context**
I use PacketEvents 2.3.0 and others versions for Bukkit, but none of them worked

`[19:05:51 WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.isOpen()" because "this.channel" is null' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.isOpen()" because "this.channel" is null
        at net.minecraft.server.v1_12_R1.NetworkManager.close(NetworkManager.java:290) ~[paper.jar:?]
        at net.minecraft.server.v1_12_R1.NetworkManager.channelInactive(NetworkManager.java:111) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[paper.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392) ~[paper.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:357) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[paper.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392) ~[paper.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:357) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[paper.jar:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[paper.jar:?]
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[paper.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[paper.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[paper.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[paper.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[paper.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[paper.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[paper.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[paper.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:394) ~[paper.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[paper.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[paper.jar:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]`

**Comment by retrooper** [comment]
Try again, maybe things work now on BungeeCord?
