### ISSUE TITLE
Velocity: Failed to initialize a channel

### ISSUE THREAD

**Issue by Nononitas** [retrooper/packetevents#820]
**Describe the bug**
```
[io.netty.channel.ChannelInitializer]: Failed to initialize a channel. Closing: [id: 0x890c6048, L:/:25577 - R:/:57806]
java.util.NoSuchElementException: packet-decoder
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.github.retrooper.packetevents.injector.ServerConnectionInitializer.addChannelHandlers(ServerConnectionInitializer.java:36) ~[?:?]
        at io.github.retrooper.packetevents.injector.ServerConnectionInitializer.initChannel(ServerConnectionInitializer.java:52) ~[?:?]
        at io.github.retrooper.packetevents.injector.VelocityChannelInitializer.initChannel(VelocityChannelInitializer.java:45) ~[?:?]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1130) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-1c36b66d-b394)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Software brand**
Velocity 3.3.0 Build 369

**Plugins**
None

**How To Reproduce**

- Start the proxy
- Ping or join the proxy

**Additional context**
You can't join the proxy at all.

**Comment by Nononitas** [comment]
Fixed in newer commits apparently
