### ISSUE TITLE
Plugin doesn't work on Folia 1.20.4

### ISSUE THREAD

**Issue by J4n-T** [retrooper/packetevents#824]
**Describe the bug**
The plugin doesn't work on Folia 1.20.4. I've tried building it myself but that didn't help either

**Software brand**
Folia 1.20.4-ec6b172

**Plugins**
- CoreProtect 
- LuckPerms 
- TAB
- ViaBackwards
- ViaVersion

**How To Reproduce**
Put the Plugin into the plugins folder
Start the server

**Expected behavior**
The plugin should load

**Additional context**
Stacktrace:
[23:09:49 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.<init>(net.minecraft.world.item.Item,int)
[23:09:49 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3761)
[23:09:49 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2442)
[23:09:49 WARN]:        at packetevents-spigot-2.3.1-SNAPSHOT.jar//io.github.retrooper.packetevents.util.SpigotReflectionUtil.initConstructors(SpigotReflectionUtil.java:134)
[23:09:49 WARN]:        at packetevents-spigot-2.3.1-SNAPSHOT.jar//io.github.retrooper.packetevents.util.SpigotReflectionUtil.init(SpigotReflectionUtil.java:392)
[23:09:49 WARN]:        at packetevents-spigot-2.3.1-SNAPSHOT.jar//io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:103)
[23:09:49 WARN]:        at packetevents-spigot-2.3.1-SNAPSHOT.jar//io.github.retrooper.packetevents.PacketEventsPlugin.onLoad(PacketEventsPlugin.java:40)
[23:09:49 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[23:09:49 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[23:09:49 WARN]:        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[23:09:49 WARN]:        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[23:09:49 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:513)
[23:09:49 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274)
[23:09:49 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217)
[23:09:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346)
[23:09:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:09:51 ERROR]: [packetevents] Error initializing plugin 'packetevents-spigot-2.3.1-SNAPSHOT.jar' in folder 'plugins' (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because the return value of "com.github.retrooper.packetevents.util.reflection.Reflection.getField(java.lang.Class, java.lang.Class, int)" is null
        at io.github.retrooper.packetevents.util.SpigotReflectionUtil.getMinecraftServerConnectionInstance(SpigotReflectionUtil.java:438) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
        at io.github.retrooper.packetevents.injector.SpigotChannelInjector.isServerBound(SpigotChannelInjector.java:63) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
        at io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:115) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
        at io.github.retrooper.packetevents.PacketEventsPlugin.onLoad(PacketEventsPlugin.java:40) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:513) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]

**Comment by booky10** [comment]
Possibly related to #793? Though mojang-mapped server runtimes were only introduced with 1.20.5/1.20.6

**Comment by J4n-T** [comment]
> Possibly related to #793? Though mojang-mapped server runtimes were only introduced with 1.20.5/1.20.6

Folia started adopting them in 1.20.4

**Comment by booky10** [comment]
Oh ok, this is definitely a duplicate then - still seems strange as the craftbukkit relocation is present

**Comment by J4n-T** [comment]
Would it be possible to check if the plugin runs on folia and use the mojang mappings on 1.20.4?

**Comment by booky10** [comment]
You can test if #794 works on folia 1.20.4

**Comment by J4n-T** [comment]
I'll try, give me a few minutes

**Comment by J4n-T** [comment]
> You can test if #794 works on folia 1.20.4

Works on 1.20.4

**Comment by J4n-T** [comment]
I have applied the changes from IssueDescription and modified the build.gradle.kts file :D
