### ISSUE TITLE
WrapperPlayServerChunkData Bug

### ISSUE THREAD

**Issue by Kooperlol** [retrooper/packetevents#830]
**Describe the bug**
Sending the WrapperPlayServerChunkData packet causes an error.

**Software brand**
Packet events 2.3.0
Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

**Plugins**
![Screenshot_16](https://github.com/retrooper/packetevents/assets/74805059/a3515bbb-b2f5-4757-8bfe-f8beb47535fd)

**How To Reproduce**
1. Create column data
2. Create WrapperPlayServerChunkData packet
3. Send packet
4. Error in console & packet does not get sent

**Expected behavior**
I expected the ChunkData packet to be sent to the user.

**Code Segment**
```
public void sendChunkPacket(Stage stage, Player player, BlockifyChunk chunk, ConcurrentHashMap<BlockifyChunk, ConcurrentHashMap<BlockifyPosition, BlockData>> blockChanges) {
        // Get the user from PacketEvents API
        final User user = PacketEvents.getAPI().getPlayerManager().getUser(player);

        // Loop through the chunks y positions
        List<BaseChunk> chunks = new ArrayList<>();
        for (int chunkY = stage.getMinPosition().getY() >> 4; chunkY <= stage.getMaxPosition().getY() >> 4; chunkY++) {

            // Loop through the blocks to send
            BaseChunk baseChunk = BaseChunk.create();
            for (Map.Entry<BlockifyPosition, BlockData> entry : blockChanges.get(chunk).entrySet()) {
                BlockifyPosition position = entry.getKey();
                int blockY = position.getY();

                // Check if the block is in the current y section
                if (blockY >> 4 == chunkY) {
                    BlockData blockData = entry.getValue();

                    int x = position.getX() & 0xF;
                    int y = position.getY() & 0xF;
                    int z = position.getZ() & 0xF;

                    // Add the encoded block to the list
                    baseChunk.set(x, y, z, blockDataToId.computeIfAbsent(blockData, bd -> WrappedBlockState.getByString(PacketEvents.getAPI().getServerManager().getVersion().toClientVersion(), bd.getAsString(false)).getGlobalId()));
                }
            }
            chunks.add(baseChunk);
        }

        // Send the packet to the player
        Column column = new Column(chunk.x(), chunk.z(), false, chunks.toArray(new BaseChunk[0]), null);
        WrapperPlayServerChunkData wrapper = new WrapperPlayServerChunkData(column);
        if (user == null || !player.isOnline()) return;
        user.sendPacket(wrapper);
    }

```
**Console Error**
`[02:34:23 WARN]: [com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: Cannot invoke "java.util.BitSet.toLongArray()" because "chunkMask" is null
        at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerChunkData.writeChunkMask(WrapperPlayServerChunkData.java:100) ~[packetevents-spigot-2.3.0.jar:?]
        at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerChunkData.write(WrapperPlayServerChunkData.java:442) ~[packetevents-spigot-2.3.0.jar:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.prepareForSend(PacketWrapper.java:216) ~[packetevents-spigot-2.3.0.jar:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.prepareForSend(PacketWrapper.java:221) ~[packetevents-spigot-2.3.0.jar:?]
        at com.github.retrooper.packetevents.manager.protocol.ProtocolManager.transformWrappers(ProtocolManager.java:107) ~[packetevents-spigot-2.3.0.jar:?]
        at com.github.retrooper.packetevents.manager.protocol.ProtocolManager.sendPacket(ProtocolManager.java:116) ~[packetevents-spigot-2.3.0.jar:?]
        at com.github.retrooper.packetevents.protocol.player.User.sendPacket(User.java:146) ~[packetevents-spigot-2.3.0.jar:?]
        at codes.kooper.blockify.managers.BlockChangeManager.sendChunkPacket(BlockChangeManager.java:259) ~[Blockify-1.1.6-beta.jar:?]
        at codes.kooper.blockify.protocol.ChunkLoadAdapter.onPacketPlaySend(ChunkLoadAdapter.java:45) ~[Blockify-1.1.6-beta.jar:?]
        at com.github.retrooper.packetevents.event.SimplePacketListenerAbstract.onPacketSend(SimplePacketListenerAbstract.java:64) ~[packetevents-spigot-2.3.0.jar:?]
        at com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[packetevents-spigot-2.3.0.jar:?]
        at com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[packetevents-spigot-2.3.0.jar:?]
        at com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:44) ~[packetevents-spigot-2.3.0.jar:?]
        at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[packetevents-spigot-2.3.0.jar:?]
        at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[packetevents-spigot-2.3.0.jar:?]
        at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[packetevents-spigot-2.3.0.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[packetevents-spigot-2.3.0.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:115) ~[TAB v4.1.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:449) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:434) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Additional context**
I am trying to send huge block changes using this and it does not seem to work.

**Comment by booky10** [comment]
Youll need to also add light data to the packet, but packetevents doesnt have getters or setters for this currently, seems like they were just forgotton?

Specific to your usecase it would probably be better if you would use the WrapperPlayServerMultiBlockChange

**Comment by Kooperlol** [comment]
> Youll need to also add light data to the packet, but packetevents doesnt have getters or setters for this currently, seems like they were just forgotton?
> 
> Specific to your usecase it would probably be better if you would use the WrapperPlayServerMultiBlockChange

> Youll need to also add light data to the packet, but packetevents doesnt have getters or setters for this currently, seems like they were just forgotton?
> 
> Specific to your usecase it would probably be better if you would use the WrapperPlayServerMultiBlockChange

That is what I am currently using, but it seems that sending one per chunk section with like a 100x100x100 region or so can cause a lot of FPS lag for the user. I was just wondering if there was a better way to do this without sending so many packets. (Also I accidentally closed this sorry about that)

**Comment by Kooperlol** [comment]
> Youll need to also add light data to the packet, but packetevents doesnt have getters or setters for this currently, seems like they were just forgotton?
> 
> Specific to your usecase it would probably be better if you would use the WrapperPlayServerMultiBlockChange

> Youll need to also add light data to the packet, but packetevents doesnt have getters or setters for this currently, seems like they were just forgotton?
> 
> Specific to your usecase it would probably be better if you would use the WrapperPlayServerMultiBlockChange

That is what I am currently using, but it seems that sending one per chunk section with like a 100x100x100 region or so can cause a lot of FPS lag for the user. I was just wondering if there was a better way to do this without sending so many packets. (Also I accidentally closed this sorry about that)

**Comment by KoutaChan** [comment]
#715 fixes this

**Comment by booky10** [comment]
see above comment, the pr has been merged
