### ISSUE TITLE
NoSuchMethodError when trying to send a Title

### ISSUE THREAD

**Issue by Wruczek** [retrooper/packetevents#856]
**Describe the bug**
Trying to send a Title using the following code:
```java
PacketEvents.getAPI().getPlayerManager().getUser(player).sendTitle("title", "test", 20, 100, 20);
```
throws an exception:
```
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component io.github.retrooper.packetevents.adventure.serializer.legacy.LegacyComponentSerializer.deserializeOrNull(java.lang.Object)'
        at com.github.retrooper.packetevents.util.adventure.AdventureSerializer.fromLegacyFormat(AdventureSerializer.java:76) ~[?:?]
        at com.github.retrooper.packetevents.protocol.player.User.sendTitle(User.java:206) ~[?:?]
```

**Software brand**
Paper version git-Paper-"a39466f01" (MC: 1.16.5)

**Plugins**
pre-build packetevents version 2.3.0

**Comment by AbhigyaKrishna** [comment]
This has been resolved in latest snapshot. Please switch to version [2.3.1-SNAPSHOT](https://ci.codemc.io/job/retrooper/job/packetevents/).
