### ISSUE TITLE
packet events spigot 2.40 snapshot release bad omen bug

### ISSUE THREAD

**Issue by jtwebhomer** [retrooper/packetevents#863]
**Describe the bug**
upon giving myself bad omen via command, or by killing a raid captain and drinking an omenous bottle i recieve a client crash this crash effects everyone on the server

**Software brand**
purpur 1.21 

**Plugins**
![image](https://github.com/retrooper/packetevents/assets/94643886/6ca6bc1c-b95e-4813-95c7-ca6fa90f663e)

**How To Reproduce**
*Example:*
1. drink omenous bottle
2. crash instantly
3. ....

**Expected behavior**
bad omen should be given to the player

**Screenshots**
![image](https://github.com/retrooper/packetevents/assets/94643886/b16e170f-9930-4423-853c-72e92af7b2a9)

**Additional context**
[21:42:48 WARN]: [com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: null
[21:42:48 WARN]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.mapper.MappedEntity.isRegistered()" because "entity" is null
[21:42:48 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[21:42:48 WARN]:        at packetevents-spigot-2.4.0-SNAPSHOT.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:42:48 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:42:48 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:42:48 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:42:48 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[21:42:48 WARN]:        at net.minecraft.network.Connection$2.write(Connection.java:765)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:42:48 WARN]:        at oraxen-1.177.0.jar//io.th0rgal.oraxen.nms.v1_21_R1.NMSHandler$1.write(NMSHandler.java:81)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:42:48 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[21:42:48 WARN]:        at Vulcan-2.8.9.jar//io.github.repooper.packetevents.injector.modern.PlayerChannelHandlerModern.write(PlayerChannelHandlerModern.java:61)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:42:48 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[21:42:48 WARN]:        at TAB v4.1.6.jar//me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:115)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:42:48 WARN]:        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[21:42:48 WARN]:        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[21:42:48 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[21:42:48 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[21:42:48 WARN]:        at net.minecraft.network.Connection.doSendPacket(Connection.java:513)
[21:42:48 WARN]:        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498)
[21:42:48 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49)
[21:42:48 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[21:42:48 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[21:42:48 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[21:42:48 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[21:42:48 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[21:42:48 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:42:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[21:42:48 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.mapper.MappedEntity.isRegistered()" because "entity" is null
[21:42:48 WARN]:        at packetevents-spigot-2.4.0-SNAPSHOT.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.writeMappedEntityOrDirect(PacketWrapper.java:1500)
[21:42:48 WARN]:        at packetevents-spigot-2.4.0-SNAPSHOT.jar//com.github.retrooper.packetevents.protocol.sound.Sound.write(Sound.java:44)
[21:42:48 WARN]:        at packetevents-spigot-2.4.0-SNAPSHOT.jar//com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerSoundEffect.write(WrapperPlayServerSoundEffect.java:106)
[21:42:48 WARN]:        at packetevents-spigot-2.4.0-SNAPSHOT.jar//com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:54)
[21:42:48 WARN]:        at packetevents-spigot-2.4.0-SNAPSHOT.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82)
[21:42:48 WARN]:        at packetevents-spigot-2.4.0-SNAPSHOT.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67)
[21:42:48 WARN]:        at packetevents-spigot-2.4.0-SNAPSHOT.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46)
[21:42:48 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[21:42:48 WARN]:        ... 57 more

**Comment by booky10** [comment]
Please install [this jar of packetevents](https://github.com/retrooper/packetevents/actions/runs/9728547203/artifacts/1651996772) and test if your issue is fixed - sounds weren't updated to 1.21

**Comment by jtwebhomer** [comment]
this fixed the issue thanks :D
