### ISSUE TITLE
Disconnect when going near a player with an item enchanted using EcoEnchants

### ISSUE THREAD

**Issue by freausan** [retrooper/packetevents#869]
**Describe the bug**

Player disconnects when going near another player with an item enchanted with a custom EcoEnchants enchant.

![image](https://github.com/retrooper/packetevents/assets/103167311/8e455bdf-3c40-4409-a5bd-cff52b77e12d)
`[LibsDisguises] Task #13907 for LibsDisguises v10.0.44-SNAPSHOT generated an exception
java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.item.enchantment.type.EnchantmentType.getId(com.github.retrooper.packetevents.protocol.player.ClientVersion)" because "enchantment" is null
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemEnchantments.lambda$write$1(ItemEnchantments.java:62) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.writeMap(PacketWrapper.java:438) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemEnchantments.write(ItemEnchantments.java:61) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.ComponentTypes$1.write(ComponentTypes.java:94) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.writeItemStackModern(PacketWrapper.java:553) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.writeItemStack(PacketWrapper.java:578) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityEquipment.write(WrapperPlayServerEntityEquipment.java:85) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.prepareForSend(PacketWrapper.java:242) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.prepareForSend(PacketWrapper.java:247) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.manager.protocol.ProtocolManager.transformWrappers(ProtocolManager.java:107) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.manager.protocol.ProtocolManager.sendPacketSilently(ProtocolManager.java:121) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.manager.player.PlayerManager.sendPacketSilently(PlayerManager.java:53) ~[packetevents-spigot-2.4.0.jar:?]
        at LibsDisguises.jar/me.libraryaddict.disguise.utilities.packets.LibsPackets.lambda$sendDelayed$2(LibsPackets.java:86) ~[LibsDisguises.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-37-dd49fba]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1654) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1538) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]`

**Software brand**
Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

**Plugins**
![image](https://github.com/retrooper/packetevents/assets/103167311/b1d8e219-ffce-4a55-ae70-56a5a43aaa7d)
eco 6.71.3
EcoEnchants  12.10.1
packetevents 2.4.0
ProtocolLib 5.3.0-SNAPSHOT-721
LibsDisguises 10.0.44-SNAPSHOT

**How To Reproduce**
*Example:*
1. Enchant an item with a custom EcoEnchants enchantment
2. Have another play go near the player with the enchanted item in inventory
3. Disconnect 
![image](https://github.com/retrooper/packetevents/assets/103167311/2a6cb603-837a-47ce-af62-8b90ac9dfb2f)

**Expected behavior**
no crash?

**Screenshots**

**Additional context**
Probably not specific to ecoenchants enchants but i would imagine generally all enchants registered with the new 1.21 system.

**Comment by dawon** [comment]
Known issue, being fixed in #866...

**Comment by Castiella** [comment]
Is there a stable build of eco enchants that stops this?

> **Describe the bug** A clear and concise description of what the bug is.
> 
> Player disconnects when going near another player with an item enchanted with a custom EcoEnchants enchant.
> 
> ![image](https://private-user-images.githubusercontent.com/103167311/344607319-8e455bdf-3c40-4409-a5bd-cff52b77e12d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzY2ODcsIm5iZiI6MTcyMjUzNjM4NywicGF0aCI6Ii8xMDMxNjczMTEvMzQ0NjA3MzE5LThlNDU1YmRmLTNjNDAtNDQwOS1hNWJkLWNmZjUyYjc3ZTEyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxODE5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTZiMzVhOGU2MjJjZWVhZjUzNWRjOTM4YjJhMTBlMDYwMjA4ZGQwNTA3OTcyY2U4N2M2NjJkM2M0YWRhZTc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zACQl2PPCZeFaPj-yNoIA_RRmDX7q8-BaYBOD01Xk14) `[LibsDisguises] Task #13907 for LibsDisguises v10.0.44-SNAPSHOT generated an exception java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.item.enchantment.type.EnchantmentType.getId(com.github.retrooper.packetevents.protocol.player.ClientVersion)" because "enchantment" is null at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemEnchantments.lambda$write$1(ItemEnchantments.java:62) ~[packetevents-spigot-2.4.0.jar:?] at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.writeMap(PacketWrapper.java:438) ~[packetevents-spigot-2.4.0.jar:?] at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemEnchantments.write(ItemEnchantments.java:61) ~[packetevents-spigot-2.4.0.jar:?] at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.ComponentTypes$1.write(ComponentTypes.java:94) ~[packetevents-spigot-2.4.0.jar:?] at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.writeItemStackModern(PacketWrapper.java:553) ~[packetevents-spigot-2.4.0.jar:?] at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.writeItemStack(PacketWrapper.java:578) ~[packetevents-spigot-2.4.0.jar:?] at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityEquipment.write(WrapperPlayServerEntityEquipment.java:85) ~[packetevents-spigot-2.4.0.jar:?] at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.prepareForSend(PacketWrapper.java:242) ~[packetevents-spigot-2.4.0.jar:?] at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.prepareForSend(PacketWrapper.java:247) ~[packetevents-spigot-2.4.0.jar:?] at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.manager.protocol.ProtocolManager.transformWrappers(ProtocolManager.java:107) ~[packetevents-spigot-2.4.0.jar:?] at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.manager.protocol.ProtocolManager.sendPacketSilently(ProtocolManager.java:121) ~[packetevents-spigot-2.4.0.jar:?] at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.manager.player.PlayerManager.sendPacketSilently(PlayerManager.java:53) ~[packetevents-spigot-2.4.0.jar:?] at LibsDisguises.jar/me.libraryaddict.disguise.utilities.packets.LibsPackets.lambda$sendDelayed$2(LibsPackets.java:86) ~[LibsDisguises.jar:?] at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-37-dd49fba] at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.21.jar:1.21-37-dd49fba] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1654) ~[paper-1.21.jar:1.21-37-dd49fba] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-37-dd49fba] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1538) ~[paper-1.21.jar:1.21-37-dd49fba] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-37-dd49fba] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba] at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]`
> 
> **Software brand** Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
> 
> **Plugins** ![image](https://private-user-images.githubusercontent.com/103167311/344606301-b1d8e219-ffce-4a55-ae70-56a5a43aaa7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzY2ODcsIm5iZiI6MTcyMjUzNjM4NywicGF0aCI6Ii8xMDMxNjczMTEvMzQ0NjA2MzAxLWIxZDhlMjE5LWZmY2UtNGE1NS1hZTcwLTU2YTVhNDNhYWE3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxODE5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2ZhYzg4OTkzYjUwNjdiY2ZjY2M0N2U2YzA1ODNmZTc0NGRmOGQyZjhmMDYwZWE2NTEyNDFmZjYzNDAwNTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4o3BpW5HqrcvyusnwlODeeRQ6tvZxebCTzMEiKbeuik) eco 6.71.3 EcoEnchants 12.10.1 packetevents 2.4.0 ProtocolLib 5.3.0-SNAPSHOT-721 LibsDisguises 10.0.44-SNAPSHOT
> 
> **How To Reproduce** Steps to reproduce the behavior: _Example:_
> 
> 1. Enchant an item with a custom EcoEnchants enchantment
> 2. Have another play go near the player with the enchanted item in inventory
> 3. Disconnect
>    ![image](https://private-user-images.githubusercontent.com/103167311/344606962-2a6cb603-837a-47ce-af62-8b90ac9dfb2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzY2ODcsIm5iZiI6MTcyMjUzNjM4NywicGF0aCI6Ii8xMDMxNjczMTEvMzQ0NjA2OTYyLTJhNmNiNjAzLTgzN2EtNDdjZS1hZjYyLThiOTBhYzlkZmIyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxODE5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Mjg3ZmY3NDQ4NmNmMTJmMTNhN2RjMWFmNDBlYTVkODc4Y2ZhZGQ2MzM4OTEyOGU3M2MzNGI2NWJlZDdlZWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t9Tr8xlXGCC7YOgiIUhmf-elv_0l9YPEeYyichlSNmw)
> 
> **Expected behavior** no crash?
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Additional context** Probably not specific to ecoenchants enchants but i would imagine generally all enchants registered with the new 1.21 system.

Is there a stable build of eco enchants that stops this?

**Comment by unnamed199cz** [comment]
We get this error but with excellent enchants plugin
![image](https://github.com/user-attachments/assets/7ffb4ded-daed-4250-b898-337fe26ff264)
