### ISSUE TITLE
Bug. Kick for the boat.

### ISSUE THREAD

**Issue by TheFaik** [retrooper/packetevents#887]
The player gets into the boat and gets kicked. There are no errors in the server logs, but the client shows this:

Description: Packet handling error

```
java.lang.IllegalStateException: Invalid entity data item type for field 9 on entity class_1690['Дубовая лодка'/288, l='ClientLevel', x=144.74, y=79.00, z=85.45]: old=1(class java.lang.Integer), new=0.5(class java.lang.Float)
	at net.minecraft.class_2945.method_12785(class_2945.java:126)
	at net.minecraft.class_2945.method_12779(class_2945.java:117)
	at net.minecraft.class_634.method_11093(class_634.java:553)
	at net.minecraft.class_2739.method_11808(class_2739.java:54)
	at net.minecraft.class_2739.method_11054(class_2739.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2945.method_12785(class_2945.java:126)
	at net.minecraft.class_2945.method_12779(class_2945.java:117)
Mixins in Stacktrace: None found

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:set_entity_data
	Is Terminal: false
	Is Skippable: false
Stacktrace:
	at net.minecraft.class_2600.method_59803(class_2600.java:56)
	at net.minecraft.class_8673.method_60882(class_8673.java:136)
	at net.minecraft.class_8673.method_59807(class_8673.java:113)
	at net.minecraft.class_2600.method_11072(class_2600.java:32)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

Server core: Leaf 1.21
Client: Fabric 1.21 (Fabulously Optimized)
Also used Vanilla client and the error is the same

Used the latest build of PacketEvents

**Comment by booky10** [comment]
Which plugins do you have installed?

**Comment by TheFaik** [comment]
https://github.com/user-attachments/assets/acf7ad7e-61c1-4b93-9f78-b9a6faab5c0b

**Comment by booky10** [comment]
Have you tried searching for the plugin which causes this issue? You have multiple plugins installed which are using packetevents

**Comment by TheFaik** [comment]
> Have you tried searching for the plugin which causes this issue? You have multiple plugins installed which are using packetevents
> 
> You can find packetevents plugins using this tool: https://github.com/Jo0001/FindPacketevents

I disabled those plugins that are related to PacketEvents and the result is the same, but I will try to disable those plugins that do not even use PacketEvents
