### ISSUE TITLE
Can't create packet wrapper for WINDOW_ITEMS event when an item has a custom attribute modifier

### ISSUE THREAD

**Issue by 123DontMindMe** [retrooper/packetevents#896]
**Describe the bug**
An IndexOutOfBoundsException occurs when creating a wrapper for a WINDOW_ITEMS event when the player's inventory has an item with a custom attribute modifier.

**Software brand**
Paper 1.21 (platform Spigot)

**Plugins**
No other plugins

**How To Reproduce**
1. Register a PacketListener to EventManager that creates a new WrapperPlayServerWindowItems object when receiving a Play.Server.WINDOW_ITEMS event
```java
public class MyListener implements PacketListener {
	@Override
	public void onPacketSend(PacketSendEvent event) {
		if (event.getPacketType() == PacketType.Play.Server.WINDOW_ITEMS)
			new WrapperPlayServerWindowItems(event);
	}
}
```
```java
public final class MyPlugin extends JavaPlugin {
	@Override
	public void onEnable() {
		PacketEvents.getAPI().getEventManager().registerListener(new MyListener(), PacketListenerPriority.NORMAL);
	}
}
```
2. Give yourself an item with any custom attribute modifier:
/give @p egg[attribute_modifiers=[{id:"armor",type:"generic.armor",amount:1,operation:"add_value"}]] 1
3. Open a chest
4. See error:
`[com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex: 146, writerIndex: 105 (expected: 0 <= readerIndex <= writerIndex <= capacity(256))
	at io.netty.buffer.AbstractByteBuf.checkIndexBounds(AbstractByteBuf.java:112) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:121) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
	at packetevents-spigot-2.4.0.jar/io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readerIndex(ByteBufOperatorModernImpl.java:44) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readerIndex(ByteBufHelper.java:39) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:635) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:623) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$Modifier.read(ItemAttributeModifiers.java:185) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$ModifierEntry.read(ItemAttributeModifiers.java:113) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readCollection(PacketWrapper.java:1426) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readList(PacketWrapper.java:1439) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers.read(ItemAttributeModifiers.java:50) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.ComponentTypes$1.read(ComponentTypes.java:88) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStackModern(PacketWrapper.java:477) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:496) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerWindowItems.read(WrapperPlayServerWindowItems.java:61) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:270) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:175) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:165) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerWindowItems.<init>(WrapperPlayServerWindowItems.java:39) ~[packetevents-spigot-2.4.0.jar:?]
	at IridiusLoreUpdater.jar/me.talula.iridiusloreupdater.MyListener.onPacketSend(MyListener.java:12) ~[IridiusLoreUpdater.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.event.PacketListener$1.onPacketSend(PacketListener.java:46) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:45) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[packetevents-spigot-2.4.0.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at packetevents-spigot-2.4.0.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[packetevents-spigot-2.4.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection$2.write(Connection.java:756) ~[paper-1.21.jar:1.21-40-b45d9b6]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:513) ~[paper-1.21.jar:1.21-40-b45d9b6]
	at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498) ~[paper-1.21.jar:1.21-40-b45d9b6]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]`

**Expected behavior**
An IndexOutOfBoundsException should not occur.

**Comment by 123DontMindMe** [comment]
After testing, I think the problem is that ItemAttributeModifiers.Modifier.read is still reading the UUID for attribute modifiers, even though (I think) attribute modifiers no longer use UUIDs in 1.21.

When I read the attribute modifier component manually and skip over the UUID, the error no longer occurs:
```java
@Override
public void onPacketSend(PacketSendEvent event) {
    if (event.getPacketType() != PacketType.Play.Server.WINDOW_ITEMS)
        return;
    PacketWrapper<?> packet = new PacketWrapper<>(event, false);
    logger.info("window id: {}", packet.readUnsignedByte());
    logger.info("state id: {}", packet.readVarInt());
    
    int slotCount = packet.readVarInt();
    logger.info("count: {}", slotCount);

    for (int slot = 0; slot < slotCount; slot++) {
        logger.info("---");
        int itemCount = packet.readVarInt();
        logger.info("[{}] item count: {}", slot, itemCount);
        if (itemCount == 0)
            continue;
            
        logger.info("item id: {}", packet.readVarInt());
        int numComponentsToAdd = packet.readVarInt();
        logger.info("num components to add: {}", numComponentsToAdd);
        int numComponentsToRemove = packet.readVarInt();
        logger.info("num components to remove: {}", numComponentsToRemove);
        
        logger.info("components to add:");
        for (int componentIndex = 0; componentIndex < numComponentsToAdd; componentIndex++) {
            int componentTypeId = packet.readVarInt();
            ComponentType<?> componentType = ComponentTypes.getById(ClientVersion.V_1_21, componentTypeId);
            logger.info("- [{}] type: {} (id = {})", componentIndex, componentType.getName().getKey(), componentTypeId);
            if (componentType != ComponentTypes.ATTRIBUTE_MODIFIERS) {
                logger.info("don't know how to read this component");
                return;
        }
        
        int numAttributes = packet.readVarInt();
        logger.info("- num attribute modifiers: {}", numAttributes);
        logger.info("- attributes modifiers:");
        for (int attributeModifierIndex = 0; attributeModifierIndex < numAttributes; attributeModifierIndex++) {
            int attributeId = packet.readVarInt();
            Attribute attribute = Attributes.getById(ClientVersion.V_1_21, attributeId);
            logger.info("- - [{}] attribute: {} (id = {})", attributeModifierIndex, attribute.getName(), attributeId);
            // don't read UUID here
            logger.info("- - key: {}", packet.readString());
            logger.info("- - amount: {}", packet.readDouble());
            logger.info("- - operation: {}", packet.readVarInt());
            logger.info("- - slot: {}", packet.readVarInt());
        }
        logger.info("- show in tooltip: {}", packet.readBoolean());
    }
    return;
}
```

The potential problem in ItemAttributeModifiers.java:
```java
public static Modifier read(PacketWrapper<?> wrapper) {
	UUID id = wrapper.readUUID();  // <-- skip?
	String name = wrapper.readString();
	double value = wrapper.readDouble();
	AttributeOperation operation = wrapper.readEnum(AttributeOperation.values());
	return new Modifier(id, name, value, operation);
}
```

**Comment by 123DontMindMe** [comment]
**Nevermind, I'm stupid and I don't understand how GitHub works and didn't realize this was fixed 2 weeks ago.**
