### ISSUE TITLE
Can't convert item to packetevents' itemstack

### ISSUE THREAD

**Issue by bindglam** [retrooper/packetevents#903]
**Describe the bug**
An error occurred when converting Bukkit's itemstack to packetevents' itemstack with SpigotConversionUtil.

**Software brand**
Purpur 1.21-2273-61b63b1 (MC: 1.21)*

**Plugins**
![image](https://github.com/user-attachments/assets/46f28621-7e58-4acf-8a54-27d79ba965d7)

**How To Reproduce**
1. Put "SpigotConversionUtil.fromBukkitItemStack(...)" in your code.
2. Run it.
3. See error

**Expected behavior**
I think it happens when SpigotConversionUtil converts Bukkit's itemstack to packetevents' itemstack because SpigotConversionUtil can't get bukkit's itemstack's attributes.

**Screenshots**
```
[08:43:23 ERROR]: Could not pass event InventoryClickEvent to WeirdCosmetic v1.0
java.lang.ArrayIndexOutOfBoundsException: Index 101 out of bounds for length 3
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readEnum(PacketWrapper.java:1471) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$Modifier.read(ItemAttributeModifiers.java:187) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$ModifierEntry.read(ItemAttributeModifiers.java:113) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readCollection(PacketWrapper.java:1426) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readList(PacketWrapper.java:1439) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers.read(ItemAttributeModifiers.java:50) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.ComponentTypes$1.read(ComponentTypes.java:88) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStackModern(PacketWrapper.java:477) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:496) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/io.github.retrooper.packetevents.util.SpigotReflectionUtil.decodeBukkitItemStack(SpigotReflectionUtil.java:809) ~[packetevents-spigot-2.4.0.jar:?]
	at packetevents-spigot-2.4.0.jar/io.github.retrooper.packetevents.util.SpigotConversionUtil.fromBukkitItemStack(SpigotConversionUtil.java:150) ~[packetevents-spigot-2.4.0.jar:?]
	at WeirdCosmetic.jar/io.github.bindglam.weirdcosmetic.players.CosmeticPlayer.updateEquipment(CosmeticPlayer.kt:41) ~[WeirdCosmetic.jar:?]
	at WeirdCosmetic.jar/io.github.bindglam.weirdcosmetic.cosmetics.HatCosmetic.onEquip(HatCosmetic.kt:14) ~[WeirdCosmetic.jar:?]
	at WeirdCosmetic.jar/io.github.bindglam.weirdcosmetic.guis.ClosetGui.onClick(ClosetGui.kt:84) ~[WeirdCosmetic.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor327.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3204) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by booky10** [comment]
Already fixed with #883, the snapshot version includes the fix for this
