### ISSUE TITLE
DimensionType decode NullPointerException on 1.16.5

### ISSUE THREAD

**Issue by LeeGodSRC** [retrooper/packetevents#928]
**Describe the bug**
NullPointerException occurs whenever DimensionType.decode (everytime a player logins).
```
[23:38:34 WARN]: [io.fairyproject.libs.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "monsterSpawnBlockLightLimit" is null
        at io.fairyproject.libs.packetevents.protocol.world.dimension.DimensionType.decode(DimensionType.java:142) ~[?:?]
        at io.fairyproject.libs.packetevents.protocol.world.dimension.DimensionTypeRef$DataRef.resolve(DimensionTypeRef.java:175) ~[?:?]
        at io.fairyproject.libs.packetevents.wrapper.play.server.WrapperPlayServerRespawn.getDimensionType(WrapperPlayServerRespawn.java:271) ~[?:?]
        at io.fairyproject.libs.packetevents.manager.InternalPacketListener.onPacketSend(InternalPacketListener.java:115) ~[?:?]
        at io.fairyproject.libs.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[?:?]
        at io.fairyproject.libs.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[?:?]
        at io.fairyproject.libs.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:45) ~[?:?]
        at io.fairyproject.libs.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[?:?]
        at io.fairyproject.libs.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[?:?]
        at io.fairyproject.libs.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.fairyproject.libs.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.github.repooper.packetevents.injector.modern.PlayerChannelHandlerModern.write(PlayerChannelHandlerModern.java:61) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.16.5.jar:git-Purpur-1171]
        at me.neznamy.tab.bridge.bukkit.BridgeChannelDuplexHandler.write(BridgeChannelDuplexHandler.java:31) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299) ~[patched_1.16.5.jar:git-Purpur-1171]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager$1.run(NetworkManager.java:450) ~[patched_1.16.5.jar:git-Purpur-1171]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Software brand**
Purpur & Paper 1.16.5

**Plugins**
No other plugins

**How To Reproduce**
*Example:*
1. Join the server
2. Error appears

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/ca725b68a546a4eeaf9b8d8d5f42e15ceb0ded22

**Comment by retrooper** [comment]
Thanks for reporting.
