### ISSUE TITLE
Spam Error

### ISSUE THREAD

**Issue by MathsAnalysis** [retrooper/packetevents#936]
Spam:
```
 PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: Cannot invoke "ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.dimension.DimensionType.isUltraWarm()" because "this.player.dimensionType" is null
	at ac.grim.grimac.predictionengine.PlayerBaseTick.updateInWaterStateAndDoFluidPushing(PlayerBaseTick.java:136) ~[?:?]
	at ac.grim.grimac.predictionengine.PlayerBaseTick.doBaseTick(PlayerBaseTick.java:51) ~[?:?]
	at ac.grim.grimac.predictionengine.MovementCheckRunner.check(MovementCheckRunner.java:485) ~[?:?]
	at ac.grim.grimac.predictionengine.MovementCheckRunner.processAndCheckMovementPacket(MovementCheckRunner.java:72) ~[?:?]
	at ac.grim.grimac.checks.impl.movement.PredictionRunner.onPositionUpdate(PredictionRunner.java:16) ~[?:?]
	at ac.grim.grimac.manager.CheckManager.onPositionUpdate(CheckManager.java:221) ~[?:?]
	at ac.grim.grimac.events.packets.CheckManagerListener.handleFlying(CheckManagerListener.java:739) ~[?:?]
	at ac.grim.grimac.events.packets.CheckManagerListener.onPacketReceive(CheckManagerListener.java:431) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:44) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:84) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:57) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:64) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:41) ~[?:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:git-ObsSpigot-PaperEdition]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:git-ObsSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
```
I'm using grimac and it gives this error the author of grim says it's a packetsevent problem
I'm using paperspigot 1.8.9

**Comment by booky10** [comment]
tell them to update packetevents, this has been fixed with #932
