### ISSUE TITLE
World height is wrong on join

### ISSUE THREAD

**Issue by SamB440** [retrooper/packetevents#962]
**Describe the bug**
https://github.com/GrimAnticheat/Grim/commit/12385556503531cb0d469f30a1f6d86cec0d628a

User#getTotalWorldHeight seems to return the overworld value on join. Switching dimensions works as expected, it just seems to be on join.

**Software brand**
Paper 1.21

**Plugins**
Grim

**How To Reproduce**
Enter the nether, disconnect, join again, the world height will be wrong

**Expected behavior**
World height to return the correct values

**Screenshots**

**Additional context**

**Comment by SamB440** [comment]
Odd, considering `InternalPacketListener` listens to these

**Comment by booky10** [comment]
```
[18:33:42 INFO]: UUID of player booky10 is d20c8b3b-9f9e-48da-94c4-2c614dd76e29
[18:33:42 INFO]: [packetevents] [STDOUT] {JOIN} CHANGED DIMENSION TO minecraft:the_end / TYPE: minecraft:the_end [FROM 0 TO 256]
```
```
[18:36:20 INFO]: UUID of player booky10 is d20c8b3b-9f9e-48da-94c4-2c614dd76e29
[18:36:20 INFO]: [packetevents] [STDOUT] {JOIN} CHANGED DIMENSION TO minecraft:the_nether / TYPE: minecraft:the_nether [FROM 0 TO 256]
```
works for me in both the nether and the end, when adding some log messages and also listening to chunk packets

<details>
<summary>paper version</summary>

This server is running Paper version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-26-52ae4ad (MC: 1.21.1)

</details>

---

is there some reproduction step or some grim-specific feature missing?
the listeners priorities shouldn't be an issue, grim tracks the dimension type at priority `HIGH`, while packetevents sets them at priority `LOWEST`

**Comment by SamB440** [comment]
Have you tried installing the terralith datapack?

**Comment by booky10** [comment]
Installing Terralith doesn't change anything in neither the nether nor the end
The datapack also only modifies the overworld, at least the one I downloaded from [here](https://modrinth.com/mod/terralith/version/Mm6TmSwo)

**Comment by booky10** [comment]
See commit description of https://github.com/booky10/packetevents/commit/c9d42f8e8ee8e430d357cb8d8fe22f2db59999ae for a possible cause to this issue
This may be reproducible when modifying world height of the overworld, nether or end, but I didn't test this yet

**Comment by SamB440** [comment]
It seems to still be happening, I should have mentioned also that I used Paper 1.19.4 to test (idk why I put 1.21)

You should see an error like
```
[15:44:12 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IllegalStateException: null
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.stream.NetStreamInput.readUnsignedByte(NetStreamInput.java:62) ~[grimac-2.3.67.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.stream.NetStreamInput.readUnsignedShort(NetStreamInput.java:75) ~[grimac-2.3.67.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.stream.NetStreamInput.readShort(NetStreamInput.java:70) ~[grimac-2.3.67.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.chunk.impl.v_1_18.Chunk_v1_18.read(Chunk_v1_18.java:50) ~[grimac-2.3.67.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.chunk.reader.impl.ChunkReader_v1_18.read(ChunkReader_v1_18.java:35) ~[grimac-2.3.67.jar:?]
        at ac.grim.grimac.events.packets.worldreader.PacketWorldReaderEighteen.handleMapChunk(PacketWorldReaderEighteen.java:27) ~[grimac-2.3.67.jar:?]
```
When logging into the nether due to the world height being wrong

**Comment by SamB440** [comment]
Someone reported having world height issues in the nether on 1.21 with this datapack
[NWMQXch.zip](https://github.com/user-attachments/files/16877029/NWMQXch.zip)
