### ISSUE TITLE
Error when joining the server

### ISSUE THREAD

**Issue by andrei1111111111** [retrooper/packetevents#973]
[17:49:39 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IllegalStateException: NBTList value tags type has unexpected type, expected class ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.NBTCompound, but got class ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.NBTEnd
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.NBTCompound.getTagListOfTypeOrThrow(NBTCompound.java:89) ~[grimac-2.3.66.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.NBTCompound.getCompoundListTagOrThrow(NBTCompound.java:128) ~[grimac-2.3.66.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.mappings.SynchronizedRegistriesHandler.handleLegacyRegistries(SynchronizedRegistriesHandler.java:126) ~[grimac-2.3.66.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.manager.InternalPacketListener.onPacketSend(InternalPacketListener.java:105) ~[grimac-2.3.66.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[grimac-2.3.66.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[grimac-2.3.66.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:45) ~[grimac-2.3.66.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[grimac-2.3.66.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[grimac-2.3.66.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[grimac-2.3.66.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[grimac-2.3.66.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:943) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:469) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:443) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Software brand**
Paper - 1.19.4

**Plugins**
Screaming BedWars (https://www.spigotmc.org/resources/screaming-bedwars-1-8-8-1-21-1.63714/) ✅
BladeWars 1st Lobby Plugin (Own) ✅
BladeWars 2nd Lobby Plugin (Own) ✅
BladeWars 1st Sections Plugin (Own) ✅
BladeWars 2nd Sections Plugin (Own) ✅
mcMMO (https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/) ✅
Citizens2 (https://www.spigotmc.org/resources/citizens.13811/) ✅
DeluxeMenus: https://www.spigotmc.org/resources/deluxemenus.11734/) ✅
ViaVersion:https://www.spigotmc.org/resources/viaversion.19254/) ✅
ViaBackwards: https://www.spigotmc.org/resources/viabackwards.27448/) ✅
ViaRewind: https://www.spigotmc.org/resources/viarewind.52109/) ✅
EssentialsX: https://www.spigotmc.org/resources/essentialsx.9089/) ✅
FeatherBoard: https://www.spigotmc.org/resources/featherboard.2691/) ✅
LiteBans (https://www.spigotmc.org/resources/litebans.3715/) ✅
NoVPN (https://www.spigotmc.org/resources/novpn-block-vpn-mcleaks-thealtening.36511/) ✅
Illusion (https://www.spigotmc.org/resources/illusion-custom-hologram-creator-by-magemonkey-studio-formerly-holographicdisplays.112186/) ✅
PlaceholderAPI (https://www.spigotmc.org/resources/placeholderapi.6245/) ✅
FAWE (https://www.spigotmc.org/resources/fastasyncworldedit.13932/) ✅
ArmorStandTools (https://www.spigotmc.org/resources/armor-stand-tools.2237/) ✅
HeadDB (https://www.spigotmc.org/resources/headdb.84967/reviews) ✅
WorldGuard (https://dev.bukkit.org/projects/worldguard) ✅
ItemJoin (https://www.spigotmc.org/resources/itemjoin.12661/) ✅
eco (https://github.com/Auxilor/eco/releases) ✅
EcoCrates ([https://www.spigotmc.org/resources/ecocrates-⭕-create-crates-easily-✅-custom-item-support-✨-import-crates.100855/](https://www.spigotmc.org/resources/ecocrates-%E2%AD%95-create-crates-easily-%E2%9C%85-custom-item-support-%E2%9C%A8-import-crates.100855/)) ✅
ProtocolLib (https://www.spigotmc.org/resources/protocollib.1997/) ✅
QuakeCraft ([https://www.spigotmc.org/resources/quake-free-•-highly-customizable-•-db-support-•-leaderboards-•-bungee-mode.45928/](https://www.spigotmc.org/resources/quake-free-%E2%80%A2-highly-customizable-%E2%80%A2-db-support-%E2%80%A2-leaderboards-%E2%80%A2-bungee-mode.45928/)) ✅
MissileWars (https://www.spigotmc.org/resources/missilewars-unique-fast-and-fun-minigame.62947/) ✅
Spark (https://spark.lucko.me/) ✅
Vault (https://www.spigotmc.org/resources/vault.34315/) ✅
The Bridge (https://www.spigotmc.org/resources/the-bridge-1-8-8-1-21.87320/) ✅
Village Defense (https://www.spigotmc.org/resources/village-defense-1-8-8-1-20.41869/) ✅
Build Battle (https://www.spigotmc.org/resources/build-battle-guessthebuild-1-8-8-1-21.44703/) ✅
Murder Mystery (https://www.spigotmc.org/resources/murder-mystery-1-8-8-1-21.66614/) ✅
ZombieApocalypse (https://www.spigotmc.org/resources/zombieapocalypse-8-zombie-types-1-21-support.82106/) ✅
SkyWarsReloaded (https://www.spigotmc.org/resources/skywarsreloaded-updated-recoded-1-20-2-support-new-features-supports-all-mc-versions.69436/) ✅
SkywarsReloaded Extension (https://www.spigotmc.org/resources/skywarsreloaded-extension-new-playagain-feature-kit-menu-editor-npcs-1-8x-1-20x.69111/) ✅
GroupManager (https://www.spigotmc.org/resources/groupmanager.38875/) ✅
AuthMeReloaded (https://www.spigotmc.org/resources/authmereloaded.6269/) ✅
AuthMeBungee (https://www.spigotmc.org/resources/authmebungee.50219/) ✅
QuestCreator (https://www.spigotmc.org/resources/questcreator.38734/) ✅ (Future Updates)
RewardPro (https://www.spigotmc.org/resources/rewardpro-daily-rewards-rank-reward-delivery-man.24346/) ✅

**How To Reproduce**
1. Start server
2. Join server with 1.19.4
3. Error in console appears

**Expected behavior**
To not appear error

**Comment by booky10** [comment]
Update GrimAC or tell them to use a newer packetevents version

(I've already told you on discord that this is not a packetevents issue, see https://canary.discord.com/channels/811396969670901800/1132037476345716776/1278732315819905185)
