### ISSUE TITLE
Disconnect error when switching servers on Velocity

### ISSUE THREAD

**Issue by JerichoTorrent** [retrooper/packetevents#981]
**Describe the bug**
When a player switches servers on Velocity. Seems to specifically be happening when switching to my creative server. 

**Software brand**
Velocity 3.3.0 SNAPSHOT build #128
Paper 1.21

**Plugins**
![image](https://github.com/user-attachments/assets/64456023-a378-4a03-99a7-95a0d3a6b5b5)

**How To Reproduce**
1. Join hub server
2. Switch to another subserver
3. Get disconnected

**Expected behavior**
Player is able to switch to any server of his choice

**Screenshots**
Don't really have any as is all explained in the error

**Additional context**
Error:
```
[19:08:07 ERROR]: [connected player] SashaPa (<ip address withheld>): exception encountered in com.velocitypowered.proxy.connection.client.ClientConfigSessionHandler@1f027062
--
2 | io.netty.handler.codec.DecoderException: com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 28 to a PacketType constant. Bound: SERVER, Connection state: CONFIGURATION, Server version: 1.21
3 | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
4 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
5 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
6 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
7 | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
8 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
9 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
10 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
11 | at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
12 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
13 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
14 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
15 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
16 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
17 | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
18 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
19 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
20 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
21 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
22 | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
23 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
24 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
25 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
26 | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
27 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
28 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
29 | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
30 | at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
31 | at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
32 | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
33 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
34 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
35 | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
36 | at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
37 | Caused by: com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 28 to a PacketType constant. Bound: SERVER, Connection state: CONFIGURATION, Server version: 1.21
38 | at com.github.retrooper.packetevents.event.ProtocolPacketEvent.<init>(ProtocolPacketEvent.java:89) ~[?:?]
39 | at com.github.retrooper.packetevents.event.PacketReceiveEvent.<init>(PacketReceiveEvent.java:32) ~[?:?]
40 | at com.github.retrooper.packetevents.event.simple.PacketConfigReceiveEvent.<init>(PacketConfigReceiveEvent.java:34) ~[?:?]
41 | at com.github.retrooper.packetevents.util.EventCreationUtil.createReceiveEvent(EventCreationUtil.java:40) ~[?:?]
42 | at io.github.retrooper.packetevents.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:54) ~[?:?]
43 | at io.github.retrooper.packetevents.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:80) ~[?:?]
44 | at io.github.retrooper.packetevents.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:40) ~[?:?]
45 | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
46 | ... 33 more
47 | [19:08:07 INFO]: [server connection] SashaPa -> Creative has disconnected

<!--EndFragment-->
</body>
</html>
[19:08:07 ERROR]: [connected player] SashaPa (<ip address withheld>): exception encountered in com.velocitypowered.proxy.connection.client.ClientConfigSessionHandler@1f027062
io.netty.handler.codec.DecoderException: com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID [2](https://mclo.gs/4eQeSCT#L2)8 to a PacketType constant. Bound: SERVER, Connection state: CONFIGURATION, Server version: 1.21
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:[3](https://mclo.gs/4eQeSCT#L3).3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:[4](https://mclo.gs/4eQeSCT#L4)20) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-6100e67[5](https://mclo.gs/4eQeSCT#L5)-b416)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b41[6](https://mclo.gs/4eQeSCT#L6))]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.3.0-SNAPSHOT (git-6100e6[7](https://mclo.gs/4eQeSCT#L7)5-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:2[8](https://mclo.gs/4eQeSCT#L8)6) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:2[9](https://mclo.gs/4eQeSCT#L9)0) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.3.0-SNAPSHOT (git-6[10](https://mclo.gs/4eQeSCT#L10)0e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:4[12](https://mclo.gs/4eQeSCT#L12)) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:[14](https://mclo.gs/4eQeSCT#L14)10) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at java.base/java.lang.Thread.run(Thread.java:[15](https://mclo.gs/4eQeSCT#L15)83) [?:?]
Caused by: com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 28 to a PacketType constant. Bound: SERVER, Connection state: CONFIGURATION, Server version: 1.21
        at com.github.retrooper.packetevents.event.ProtocolPacketEvent.<init>(ProtocolPacketEvent.java:89) ~[?:?]
        at com.github.retrooper.packetevents.event.PacketReceiveEvent.<init>(PacketReceiveEvent.java:32) ~[?:?]
        at com.github.retrooper.packetevents.event.simple.PacketConfigReceiveEvent.<init>(PacketConfigReceiveEvent.java:34) ~[?:?]
        at com.github.retrooper.packetevents.util.EventCreationUtil.createReceiveEvent(EventCreationUtil.java:40) ~[?:?]
        at io.github.retrooper.packetevents.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:54) ~[?:?]
        at io.github.retrooper.packetevents.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:80) ~[?:?]
        at io.github.retrooper.packetevents.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:40) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b4[16](https://mclo.gs/4eQeSCT#L16))]
        ... 33 more
[19:08:07 INFO]: [server connection] SashaPa -> Creative has disconnected
```

**Comment by JerichoTorrent** [comment]
If needed here is the list of plugins on my proxy:
![image](https://github.com/user-attachments/assets/46fe7fd3-c0b7-48ec-8971-d9a5cf83d37e)
Also for additional context, I have 2 proxy servers. This is only affecting the second one, but they are basically 1:1 to each other. The main difference though, is that the 2nd proxy is proxied through Minehut, using their API and haproxy protocol. However, it worked just fine for some time.

**Comment by JerichoTorrent** [comment]
Hello?

**Comment by Ghost-Kokoro** [comment]
I have this bug too, how did you solve it then?
