### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [retrooper/packetevents#984]
[03:10:16 WARN]: [net.square.sierra.packetevents.api.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.netty.buffer.ByteBufOperatorModernImpl.readByte(ByteBufOperatorModernImpl.java:74) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.netty.buffer.ByteBufHelper.readByte(ByteBufHelper.java:67) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.wrapper.PacketWrapper.readByte(PacketWrapper.java:349) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.wrapper.PacketWrapper.readVarInt(PacketWrapper.java:389) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.wrapper.PacketWrapper.readItemStackModern(PacketWrapper.java:461) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:498) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/de.feelix.sierra.check.impl.book.BookValidation.handlePickItem(BookValidation.java:138) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/de.feelix.sierra.check.impl.book.BookValidation.handle(BookValidation.java:60) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/de.feelix.sierra.check.CheckManager.processAvailableChecksReceive(CheckManager.java:47) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/de.feelix.sierra.listener.PacketReceiveListener.onPacketReceive(PacketReceiveListener.java:63) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.event.PacketReceiveEvent.call(PacketReceiveEvent.java:44) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.event.EventManager.callEvent(EventManager.java:84) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:84) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.injector.ha

**Comment by TDMidkwhatisxd** [comment]
purpur 1.21.1 and packetevent latest, dev build

**Comment by booky10** [comment]
This is not caused by packetevents, the plugin you are using [does some non-functioning stuff](https://github.com/Interlink-Media/Sierra/blob/9e5f246898dbf181001ec1818fa169f177964ce1/src/main/java/de/feelix/sierra/check/impl/book/BookValidation.java#L128-L154)
Please report this to [the plugin](https://github.com/Interlink-Media/Sierra), and if there is indeed an issue with packetevents here, comment again in this issue
